PROCESS BEFORE OUTPUT.
* MODULE STATUS_0700.
MODULE SCREEN_LAYOUT.

PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0700.
 .

    PROCESS ON VALUE-REQUEST.
    FIELD ZEWAY_MULTI_VEH-FROMSTATECODE MODULE INPUT_STATE.
    FIELD ZEWAY_MULTI_VEH-TO_STATE MODULE INPUT_STATE1.
    FIELD ZEWAY_MULTI_VEH-group1 MODULE INPUT_group1.
