*----------------------------------------------------------------------*
***INCLUDE LZASSET_TABLEF01.
*----------------------------------------------------------------------*
FORM CHECK_ENTRY.

*  BREAK-POINT.

  DATA : WA_ZASSET_TABLE TYPE ZASSET_TABLE.

  DATA : IT_ZASSET_TABLE TYPE TABLE OF ZASSET_TABLE.

  SELECT * FROM ZASSET_TABLE
    INTO TABLE IT_ZASSET_TABLE
    WHERE ANLKL = ZASSET_TABLE-ANLKL.

    IF SY-SUBRC = 0.

      MESSAGE 'ASSET CLASS ALREADY ASIGNED' TYPE 'E'.

      ELSEIF ZASSET_TABLE-HEADING = 'FREEHOLD LAND' OR ZASSET_TABLE-HEADING = 'BUILDINGS' OR ZASSET_TABLE-HEADING = 'PLANT AND MACHINERY' OR
    ZASSET_TABLE-HEADING = 'OFFICE EQUIPMENT' OR ZASSET_TABLE-HEADING = 'COMPUTERS' OR ZASSET_TABLE-HEADING = 'FURNITURE AND FIXTURES' OR
    ZASSET_TABLE-HEADING = 'VEHICLES' OR ZASSET_TABLE-HEADING = 'ASSETS UNDER FINANCE LEASE' OR ZASSET_TABLE-HEADING = 'COMPUTER SOFTWARE'.

    MESSAGE 'HEADING IS MATCHED' TYPE 'I'.

    ELSE.

      MESSAGE 'ENTER VALID HEADING' TYPE 'E'.

      ENDIF.

      IF ZASSET_TABLE-HEADING = ' '.

        MESSAGE 'PLEASE ENTER HEADING' TYPE 'E'.

       ENDIF.
      IF ZASSET_TABLE-ANLKL = ' '.

        MESSAGE 'PLEASE ENTER ASSET CLASS' TYPE 'E'.

        ENDIF.


      ENDFORM.
