PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZAUTO_COSTH1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZAUTO_COSTH1-HEADER .
    FIELD ZAUTO_COSTH1-PLANT .
    FIELD ZAUTO_COSTH1-SO_DATE .
    FIELD ZAUTO_COSTH1-IDNRK .
    FIELD ZAUTO_COSTH1-OJTXP .
    FIELD ZAUTO_COSTH1-MNGLG .
    FIELD ZAUTO_COSTH1-EBELN .
    FIELD ZAUTO_COSTH1-WAERS .
    FIELD ZAUTO_COSTH1-VERPR .
    FIELD ZAUTO_COSTH1-NETPR .
    FIELD ZAUTO_COSTH1-ZESC .
    FIELD ZAUTO_COSTH1-KBETR .
    FIELD ZAUTO_COSTH1-ZLIP .
    FIELD ZAUTO_COSTH1-ZESC_QTY .
    FIELD ZAUTO_COSTH1-ZLIP_QTY .
    FIELD ZAUTO_COSTH1-DATAB .
    FIELD ZAUTO_COSTH1-DATBI .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZAUTO_COSTH1-HEADER .
    FIELD ZAUTO_COSTH1-PLANT .
    FIELD ZAUTO_COSTH1-SO_DATE .
    FIELD ZAUTO_COSTH1-IDNRK .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
