PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBILLINGTYPES CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBILLINGTYPES-BUKRS .
    FIELD ZBILLINGTYPES-VKORG .
    FIELD ZBILLINGTYPES-FKART .
    FIELD ZBILLINGTYPES-ZSUPPLY .
    FIELD ZBILLINGTYPES-ZSUBSUPPLY .
    FIELD ZBILLINGTYPES-ZDOCTYPE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBILLINGTYPES-BUKRS .
    FIELD ZBILLINGTYPES-VKORG .
    FIELD ZBILLINGTYPES-FKART .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
