PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCASHFLOW CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCASHFLOW-BUKRS .
    FIELD ZCASHFLOW-KTOPL .
    FIELD ZCASHFLOW-HEAD .
    FIELD ZCASHFLOW-ITEM .
    FIELD ZCASHFLOW-SAKNR .
    FIELD ZCASHFLOW-ZBIND .
    FIELD ZCASHFLOW-ZCND .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCASHFLOW-BUKRS .
    FIELD ZCASHFLOW-KTOPL .
    FIELD ZCASHFLOW-HEAD .
    FIELD ZCASHFLOW-ITEM .
    FIELD ZCASHFLOW-SAKNR .
    FIELD ZCASHFLOW-ZBIND .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
