PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCFG_SLOC_FLAG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCFG_SLOC_FLAG-WERKS .
    FIELD ZCFG_SLOC_FLAG-LGORT .
    FIELD ZCFG_SLOC_FLAG-FLAG_NAME .
    FIELD ZCFG_SLOC_FLAG-PATTERN .
    FIELD ZCFG_SLOC_FLAG-ACTIVE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCFG_SLOC_FLAG-WERKS .
    FIELD ZCFG_SLOC_FLAG-LGORT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
