"Name: \PR:SAPLCOKO1\FO:OK_CODE_PREP\SE:END\EI
ENHANCEMENT 0 ZCO02_LGORT_CHECK.
  IF AFPOD-PWERK = 'PL01' AND SY-TCODE = 'CO02' AND SY-UCOMM = 'YES'.
*    IF SY-UCOMM = 'YES'.
    IF AFPOD-LGORT = ''.
       LEAVE TO SCREEN 0.

    ENDIF.
*    ENDIF.
  ENDIF.
ENDENHANCEMENT.
