*----------------------------------------------------------------------*
***INCLUDE ZDBBRFSEL.
*----------------------------------------------------------------------*
*DATA BRDKUNNR.

* INCLUDE DBBRFSEL
SELECTION-SCREEN DYNAMIC SELECTIONS FOR TABLE BKPF.
SELECTION-SCREEN DYNAMIC SELECTIONS FOR TABLE FAGLFREESEL.
SELECTION-SCREEN FIELD SELECTION FOR TABLE BKPF.
SELECTION-SCREEN FIELD SELECTION FOR TABLE BSEG.
SELECTION-SCREEN FIELD SELECTION FOR TABLE KNA1.
SELECTION-SCREEN FIELD SELECTION FOR TABLE KNB1.
SELECTION-SCREEN FIELD SELECTION FOR TABLE LFA1.
SELECTION-SCREEN FIELD SELECTION FOR TABLE LFB1.
SELECTION-SCREEN FIELD SELECTION FOR TABLE SKA1.
SELECTION-SCREEN FIELD SELECTION FOR TABLE SKB1.


SELECT-OPTIONS: BR_BUKRS FOR BKPF-BUKRS.
SELECT-OPTIONS: BR_BELNR FOR BKPF-BELNR.
SELECT-OPTIONS: BR_GJAHR FOR BKPF-GJAHR.
**********SWITCH EHP4

SELECT-OPTIONS: BR_RLDNR FOR BKPF-RLDNR MODIF ID LDG
                                        NO-EXTENSION
                                        NO INTERVALS
                                        MATCHCODE OBJECT FAGL_RLDNR.


SELECT-OPTIONS: BR_LDGRP for bKPF-LDgrp MODIF ID GRP
                                        NO-EXTENSION
                                        NO INTERVALS.
**********SWIT EHP4 End

SELECTION-SCREEN SKIP FOR TABLE BKPF.

SELECTION-SCREEN BEGIN OF BLOCK BR_0 WITH FRAME TITLE TEXT-000.
SELECT-OPTIONS: BR_BLART FOR BKPF-BLART.
SELECT-OPTIONS: BR_BUDAT FOR BKPF-BUDAT.
SELECT-OPTIONS: BR_CPUDT FOR BKPF-CPUDT.
SELECT-OPTIONS: BR_XBLNR FOR BKPF-XBLNR.
SELECT-OPTIONS: BR_AWTYP FOR BKPF-AWTYP.
SELECT-OPTIONS: BR_AWKEY FOR BKPF-AWKEY.
SELECT-OPTIONS: BR_AWSYS FOR BKPF-AWSYS.

*--- begin of alternative Hauswährung  -------------------  "<<<< euro
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(31) TEXT-021  FOR FIELD ALCUR MODIF ID EUR.
PARAMETERS: ALCUR LIKE T000F-XALHW     FOR TABLE BKPF  MODIF ID EUR.
* parameters: alcur like rfpdo-xbrsequ     for table bkpf  modif id eur.
SELECTION-SCREEN COMMENT 37(20) TEXT-022 FOR FIELD EXCDT MODIF ID EUR.
PARAMETERS: EXCDT LIKE RFPDO3-UMSEXCHDAT FOR TABLE BKPF  MODIF ID EUR.
SELECTION-SCREEN END OF LINE.
*--- end of alternative Hauswährung   --------------------- <<<< euro

SELECTION-SCREEN END OF   BLOCK BR_0.

SELECTION-SCREEN BEGIN OF BLOCK BR_1 WITH FRAME TITLE TEXT-100.
PARAMETERS: BR_SEQ LIKE RFPDO-XBRSEQU FOR TABLE BKPF MODIF ID SEQ.

PARAMETERS: XUSEDB   TYPE BOOLE_D FOR TABLE BKPF            "997117
                                         NO-DISPLAY,        "997117
            XUSEAR TYPE BOOLE_D   FOR TABLE BKPF            "997117
                                         NO-DISPLAY,        "997117
            XUSEAS   TYPE BOOLE_D   FOR TABLE BKPF          "997117
                                         NO-DISPLAY,        "997117
            ARCHOBJ  LIKE ADMI_RUN-OBJECT FOR TABLE BKPF    "997117
                                         NO-DISPLAY,        "997117
            XEMUCNV  LIKE DTINP-XEMUCNV  FOR TABLE BKPF     "997117
                                         NO-DISPLAY,        "997117
            ARUSETYP LIKE DTINP-ARUSETYP FOR TABLE BKPF     "997117
                     DEFAULT 'READ'      NO-DISPLAY.        "997117
SELECT-OPTIONS: ARCH_SEL FOR BKPF-AWKEY  NO-DISPLAY.        "997117
"tricky: awkey <=> arkey to fool logDB
SELECTION-SCREEN END OF   BLOCK BR_1.

SELECT-OPTIONS: BR_BLDAT FOR BKPF-BLDAT  NO-DISPLAY.
SELECT-OPTIONS: BR_USNAM FOR BKPF-USNAM  NO-DISPLAY.

SELECT-OPTIONS: BR_VATDT FOR BKPF-VATDATE NO-DISPLAY        "N1023317
                                          MODIF ID VAT.     "N1023317
SELECT-OPTIONS: BRDKUNNR FOR KNA1-KUNNR  NO-DISPLAY.
SELECT-OPTIONS: BRDGJAHR FOR KNC1-GJAHR  NO-DISPLAY.

SELECT-OPTIONS: BRKLIFNR FOR LFA1-LIFNR  NO-DISPLAY.
SELECT-OPTIONS: BRKGJAHR FOR LFC1-GJAHR  NO-DISPLAY.

SELECT-OPTIONS: BRSSAKNR FOR SKA1-SAKNR  NO-DISPLAY.
SELECT-OPTIONS: BRSGJAHR FOR SKC1A-GJAHR NO-DISPLAY.
SELECT-OPTIONS: BRSGSBER FOR SKC1A-GSBER NO-DISPLAY.

PARAMETERS:     STATISTK(1)  TYPE C FOR TABLE BOSG NO-DISPLAY.
PARAMETERS:     AUTH_BUK(1) TYPE C FOR TABLE BOSG NO-DISPLAY."<-- 31H
PARAMETERS:     AUTBEXNO(1) TYPE C FOR TABLE BOSG NO-DISPLAY.
PARAMETERS:     AUTH_LDR(1) TYPE C FOR TABLE BOSG NO-DISPLAY."1035181
PARAMETERS:     SELNEWGL(1) TYPE C FOR TABLE BOSG NO-DISPLAY. "1358937

*----- begin extensions for In memory DB
SELECT-OPTIONS: gr_bstat FOR bkpf-bstat NO-DISPLAY.
PARAMETERS:     xhana    TYPE FIN_LDB_MODE FOR TABLE BOSG NO-DISPLAY.
*----- end extensions for In memory DB

SELECTION-SCREEN FUNCTION KEY 5 FOR TABLE BKPF ID 999.      "997117

SELECTION-SCREEN BEGIN OF VERSION 950 TEXT-950.
SELECTION-SCREEN EXCLUDE SELECT-OPTIONS: BR_CPUDT, BR_BLART,
                                         BR_AWTYP, BR_AWKEY, BR_AWSYS.
SELECTION-SCREEN EXCLUDE IDS 999.                           "997117

SELECTION-SCREEN END   OF VERSION 950.

SELECTION-SCREEN BEGIN OF VERSION 900 TEXT-900.
SELECTION-SCREEN EXCLUDE SELECT-OPTIONS: BR_CPUDT, BR_BUDAT, BR_BLART,
                                         BR_BELNR, BR_GJAHR, BR_XBLNR,
                                         BR_AWTYP, BR_AWKEY, BR_AWSYS.
SELECTION-SCREEN EXCLUDE PARAMETERS: BR_SEQ. ",
SELECTION-SCREEN EXCLUDE IDS 999.                           "997117

SELECTION-SCREEN END   OF VERSION 900.

SELECTION-SCREEN BEGIN OF VERSION 901 TEXT-901.
SELECTION-SCREEN EXCLUDE SELECT-OPTIONS: BR_CPUDT, BR_BLART,
                                         BR_AWTYP, BR_AWKEY, BR_AWSYS.
SELECTION-SCREEN END   OF VERSION 901.

SELECTION-SCREEN BEGIN OF VERSION 902 TEXT-902.
SELECTION-SCREEN EXCLUDE SELECT-OPTIONS: BR_CPUDT, BR_BUDAT, BR_BLART,
                                         BR_BELNR, BR_GJAHR, BR_XBLNR,
                                         BR_AWTYP, BR_AWKEY, BR_AWSYS.
SELECTION-SCREEN EXCLUDE PARAMETERS: BR_SEQ.
SELECTION-SCREEN END   OF VERSION 902.

SELECTION-SCREEN BEGIN OF VERSION 903 TEXT-903.
SELECTION-SCREEN EXCLUDE PARAMETERS: BR_SEQ. ",
SELECTION-SCREEN EXCLUDE IDS 999.                           "997117

SELECTION-SCREEN END   OF VERSION 903.

SELECTION-SCREEN BEGIN OF VERSION 904 TEXT-904.                "1415591
  SELECTION-SCREEN EXCLUDE PARAMETERS: BR_SEQ. ",              "1415591
SELECTION-SCREEN END   OF VERSION 904.                         "1415591


DATA: ARCH_MSSG_SENT(1).                   "was archive warning sent?

INCLUDE ZRFDBRMAC.
