"Name: \PR:SAPLV61A\FO:FRM_KOND_BASIS_362\SE:END\EI
ENHANCEMENT 0 ZEH_PRINCINGCAL_SAR.
*
** ADDED BY PRIYANKA JADHAV ON 12 OCT 23
*  IF KOMP-WERKS = 'SU01'.
*  ZWRBTR = KONV-KAWRT.
*  ENDIF.
** ENDED BY PRIYANKA JADHAV ON 12 OCT 23
*GGG
* ADDED BY SANJAY KESERWANI ON 03.11.2023
IF ( SY-TCODE  = 'ME21N'  OR SY-TCODE  = 'ME22N' OR  SY-TCODE  = 'ME23N' ) AND KOMP-WERKS = 'SU01' AND KONV-MWSK1 = 'I1'.
  zwrbtr = KONV-KAWRT.
*  KOMP-NETWR = zwrbtr.
*  MODIFY KOMP TRANSPORTING
  ENDIF.
* ENDED BY SANJAY KESERWANI ON 03.11.2023
ENDENHANCEMENT.
