*&---------------------------------------------------------------------*
*& Report ZEINV_CREATION_PROG
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEINV_CREATION_PROG_N_PRIM.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE text-001.
  PARAMETERS: A1 RADIOBUTTON GROUP R,
              A2 RADIOBUTTON GROUP R,
              A3 RADIOBUTTON GROUP R,
              A4 RADIOBUTTON GROUP R.
*              A5 RADIOBUTTON GROUP R,
*              A6 RADIOBUTTON GROUP R.
SELECTION-SCREEN:END OF BLOCK B1.


IF A1 EQ 'X'.

  SUBMIT  ZEINV_CUSTOMER_INV_PRIM VIA SELECTION-SCREEN AND RETURN.

ELSEIF A2 EQ 'X'.

  SUBMIT ZEINV_CUST_CREDIT_DEBIT_PRIM  VIA SELECTION-SCREEN AND RETURN.

ELSEIF A3 EQ 'X'.

  SUBMIT ZEINV_FI_CEDIT_DEBIT__PRIM  VIA SELECTION-SCREEN AND RETURN.

ELSEIF A4 EQ 'X'.

  SUBMIT ZEINV_MIRO_PRIM VIA SELECTION-SCREEN AND RETURN.
*
*ELSEIF A5 EQ 'X'.
*
*SUBMIT ZEINV_FI_DEBIT_INVOICE VIA SELECTION-SCREEN AND RETURN .
*
*ELSEIF A6 EQ 'X'.

*SUBMIT ZEINV_FI_CEDIT_DEBIT_FB60_65 VIA SELECTION-SCREEN AND RETURN .


ENDIF.
