"Name: \PR:SAPLV60A\FO:USEREXIT_PRICING_PREPARE_TKOMP\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_FIELD_GRAYOUT_VF02.
*
IF SY-TCODE = 'VF01' OR SY-TCODE = 'VF02'.

  DATA : LV_KNUMV TYPE VBRK-KNUMV,
         LV_KINAK TYPE KONV-KINAK.

  SELECT SINGLE KNUMV
                FROM VBRK
                INTO LV_KNUMV
                WHERE VBELN = XVBUK-VBELN.

  EXPORT LV_KNUMV TO MEMORY ID 'CON_TYPE'.

ENDIF.

ENDENHANCEMENT.
