PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZENHNS_ACT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZENHNS_ACT-TITLE .
    FIELD ZENHNS_ACT-WERKS .
    FIELD ZENHNS_ACT-EXIT_DESC .
    FIELD ZENHNS_ACT-VLDTL .
    FIELD ZENHNS_ACT-ACTIV .
    FIELD ZENHNS_ACT-MODDT .
    FIELD ZENHNS_ACT-MODTM .
    FIELD ZENHNS_ACT-MODUSR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZENHNS_ACT-TITLE .
    FIELD ZENHNS_ACT-WERKS .
    FIELD ZENHNS_ACT-EXIT_DESC .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
