"Name: \PR:SAPLV69A\FO:USEREXIT_FIELD_MODIFICATION\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_FIELD_GRAYOUT.
*
IF SY-TCODE = 'VF01' OR SY-TCODE = 'VF02'.

  TYPES : BEGIN OF TY_KONV,
          KNUMV TYPE KONV-KNUMV,
          KPOSN TYPE KONV-KPOSN,
          STUNR TYPE KONV-STUNR,
          ZAEHK TYPE KONV-ZAEHK,
          KSCHL TYPE KONV-KSCHL,
          KINAK TYPE KONV-KINAK,
          END OF TY_KONV.

  DATA : LT_KONV TYPE STANDARD TABLE OF TY_KONV,
         LS_KONV TYPE TY_KONV.

  DATA : LV_KNUMV TYPE VBRK-KNUMV.
  DATA : LV_KINAK TYPE KONV-KINAK.

  IMPORT LV_KNUMV FROM MEMORY ID 'CON_TYPE'.

  SELECT KNUMV
         KPOSN
         STUNR
         ZAEHK
         KSCHL
         KINAK
         FROM KONV
         INTO TABLE LT_KONV
         WHERE KNUMV = LV_KNUMV
         AND   KSCHL = 'ZPR0'.
  READ TABLE LT_KONV INTO LS_KONV WITH KEY KNUMV = LV_KNUMV
                                           KSCHL = 'ZPR0'.
  IF SY-SUBRC = 0.
     LV_KINAK = LS_KONV-KINAK.
  ENDIF.

  IF LV_KINAK IS INITIAL.
    IF SCREEN-NAME = 'KOMV-KBETR'.
       SCREEN-INPUT = 0.
    ENDIF.

    IF SCREEN-NAME = 'RV61A-KOEIN'.
       SCREEN-INPUT = 0.
    ENDIF.

    IF SCREEN-NAME = 'KOMV-KPEIN'.
       SCREEN-INPUT = 0.
    ENDIF.

    IF SCREEN-NAME = 'KOMV-KMEIN'.
       SCREEN-INPUT = 0.
    ENDIF.

    IF SCREEN-NAME = 'KOMV-KWERT'.
       SCREEN-INPUT = 0.
    ENDIF.

  ENDIF.

ENDIF.

ENDENHANCEMENT.
