
SELECT SINGLE * FROM VBAK INTO GV_VBAK
  WHERE VBELN = LV_VBELN.

SELECT SINGLE * FROM VBKD INTO GV_VBKD
  WHERE VBELN = LV_VBELN.
*************Sale Order Date
CONCATENATE  GV_VBAK-ERDAT+4(2) GV_VBAK-ERDAT+6(2) GV_VBAK-ERDAT+0(4)
                INTO GV_SALE_DT SEPARATED BY '-'.
**************PO DATE

CONCATENATE  GV_VBKD-BSTDK+4(2) GV_VBKD-BSTDK+6(2) GV_VBKD-BSTDK+0(4)
                INTO GV_PO_DT SEPARATED BY '-'.

************CDD Date

CONCATENATE GV_VBAK-VDATU+4(2) GV_VBAK-VDATU+6(2) GV_VBAK-VDATU+0(4)
            INTO GV_CDD_DT SEPARATED BY '-'.

************OFM Date
*BREAK-POINT.
CONDENSE WA_FINAL-LV_LINES1.
MOVE WA_FINAL-LV_LINES1 TO GV_OFM_DT.


*CONCATENATE GV_OFM_DT+6(4) GV_OFM_DT+3(2) GV_OFM_DT+0(2)
CONCATENATE  GV_OFM_DT+3(2) GV_OFM_DT+0(2) GV_OFM_DT+6(4)
INTO GV_OFM_DT SEPARATED BY '.'.



*CONCATENATE  WA_FINAL-DELDATE+4(2) WA_FINAL-DELDATE+6(2) WA_FINAL-DELDATE+0(4)
*                INTO GV_DEL_DT SEPARATED BY '-'.
*
