PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZEINV_LINK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZEINV_LINK-BUKRS .
    FIELD ZEINV_LINK-VKORG .
    FIELD ZEINV_LINK-FKART .
    FIELD ZEINV_LINK-BASE_KSCHL .
    FIELD ZEINV_LINK-DISC_KSCHL .
    FIELD ZEINV_LINK-OTHER_KSCHL .
    FIELD ZEINV_LINK-TYPE .
    FIELD ZEINV_LINK-CATEGORY .
    FIELD ZEINV_LINK-EXPCAT .
    FIELD ZEINV_LINK-FLAG .
    FIELD ZEINV_LINK-FOC_FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZEINV_LINK-BUKRS .
    FIELD ZEINV_LINK-VKORG .
    FIELD ZEINV_LINK-FKART .
    FIELD ZEINV_LINK-BASE_KSCHL .
    FIELD ZEINV_LINK-DISC_KSCHL .
    FIELD ZEINV_LINK-OTHER_KSCHL .
    FIELD ZEINV_LINK-TYPE .
    FIELD ZEINV_LINK-CATEGORY .
    FIELD ZEINV_LINK-EXPCAT .
    FIELD ZEINV_LINK-FLAG .
    FIELD ZEINV_LINK-FOC_FLAG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
