PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZOFM_BOOKING CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZOFM_BOOKING-ZSOREF .
    FIELD ZOFM_BOOKING-ZSCOPE .
    FIELD ZOFM_BOOKING-ZOFM_REV_NO .
    FIELD ZOFM_BOOKING-ZREV_DATE .
    FIELD ZOFM_BOOKING-ZBOOKING_CURR .
    FIELD ZOFM_BOOKING-ZCUR_CONV .
    FIELD ZOFM_BOOKING-ZBOOK_VALUE .
    FIELD ZOFM_BOOKING-ZINR_VAL .
    FIELD ZOFM_BOOKING-ZAGRR_VAL .
    FIELD ZOFM_BOOKING-ZPRICE .
    FIELD ZOFM_BOOKING-ZBUTT .
    FIELD ZOFM_BOOKING-ZBALL_VALES .
    FIELD ZOFM_BOOKING-ZOFFSET_VAL .
    FIELD ZOFM_BOOKING-ZACT_CNT .
    FIELD ZOFM_BOOKING-ZSERVICE .
    FIELD ZOFM_BOOKING-ZREMARK .
    FIELD ZOFM_BOOKING-ZGROSS_M .
    FIELD ZOFM_BOOKING-BRANCH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZOFM_BOOKING-ZSOREF .
    FIELD ZOFM_BOOKING-ZSCOPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
