PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZEINV_LINK_FI CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZEINV_LINK_FI-BUKRS .
    FIELD ZEINV_LINK_FI-BUPLA .
    FIELD ZEINV_LINK_FI-GSBER .
    FIELD ZEINV_LINK_FI-BLART .
    FIELD ZEINV_LINK_FI-FB60_65_FLAG .
    FIELD ZEINV_LINK_FI-FB70_75_FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZEINV_LINK_FI-BUKRS .
    FIELD ZEINV_LINK_FI-BUPLA .
    FIELD ZEINV_LINK_FI-GSBER .
    FIELD ZEINV_LINK_FI-BLART .
    FIELD ZEINV_LINK_FI-FB60_65_FLAG .
    FIELD ZEINV_LINK_FI-FB70_75_FLAG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
