*----------------------------------------------------------------------*
***INCLUDE LZFG_JSON_CONVERSIONF01.
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  GET_DATA_ALL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_LT_RETMSG  text
*      -->P_VBELN  text
*      -->P_GJAHR  text
*----------------------------------------------------------------------*
FORM GET_DATA_ALL  TABLES LT_RETMSG STRUCTURE BAPIRET2
                          LT_DOCS STRUCTURE ZSTR_VBELN
                  USING VBELN TYPE VBELN
                        GJAHR TYPE GJAHR
                        LV_MODE TYPE FLAG
                        LV_UCOMM TYPE SY-UCOMM    .

  REFRESH LT_FINAL.
  DATA LC_VBELN TYPE VBELN.
  DATA : LV_DATE TYPE STRING.
  DATA: LV_LINES TYPE I.
  DATA : I_TEXT TYPE CHAR100,
         E_TEXT TYPE CHAR100.

  IF LT_DOCS[] IS NOT INITIAL.
    DESCRIBE TABLE LT_DOCS LINES LV_LINES.
  ENDIF.

  LC_VBELN = VBELN.




  "===============================================================================================
  " Data Fetch all
  "===============================================================================================

  IF LC_VBELN IS NOT INITIAL.
    SELECT
      VBELN FKART WAERK  KNUMV FKDAT GJAHR RFBSK ZTERM BUKRS XBLNR ZUONR BUPLA VKORG VTWEG LAND1
       FROM VBRK
               INTO TABLE LT_VBRK
               WHERE VBELN EQ LC_VBELN.

  ENDIF.

  IF LT_VBRK IS NOT INITIAL.
    DESCRIBE TABLE LT_VBRK LINES LV_DOCS.
    SELECT
      VBELN POSNR FKIMG VRKME NTGEW NETWR MATNR ARKTX PSTYV WERKS VGBEL "LGORT "lgort added by jyoti on 18.06.2024
       FROM VBRP
            INTO TABLE LT_VBRP
            FOR ALL ENTRIES IN LT_VBRK
            WHERE VBELN = LT_VBRK-VBELN.

    "----Eway details---------------------------------------------------------------------

    IF LT_VBRP IS NOT INITIAL.

      SELECT VBELN POSNR PARVW LIFNR
        FROM VBPA INTO TABLE LT_VBPA_EWAY
        FOR ALL ENTRIES IN LT_VBRP
        WHERE VBELN = LT_VBRP-VGBEL AND
              PARVW = 'LF'.

      IF LT_VBPA_EWAY IS NOT INITIAL.
        SELECT LIFNR NAME1 STCD3 FROM
        LFA1 INTO TABLE LT_LFA1_EWAY
         FOR ALL ENTRIES IN LT_VBPA_EWAY
          WHERE LIFNR = LT_VBPA_EWAY-LIFNR.
      ENDIF.

      SELECT VBELN,BOLNR FROM LIKP
        INTO TABLE @DATA(LT_LIKP_EWAY)
        FOR ALL ENTRIES IN @LT_VBRP
        WHERE VBELN = @LT_VBRP-VGBEL.


      WAIT UP TO 1 SECONDS.

      SELECT
        VBELN
        TRNS_MD
        TRANS_DOC
        DOC_DT
        TRANS_ID
        TRANS_NAME
        VEHICAL_NO
        VEHICAL_TYPE
        DISTANCE
        FROM ZEWAY_BILL INTO TABLE LT_ZEWAY_TAB
        FOR ALL ENTRIES IN LT_VBRK
        WHERE VBELN = LT_VBRK-VBELN.

    ENDIF.
*-----------------------------------------------------------------------------------------



    SELECT
      BUKRS BRANCH GSTIN
       FROM J_1BBRANCH
            INTO TABLE LT_J_1BBRANCH
            FOR ALL ENTRIES IN LT_VBRK
            WHERE BUKRS = LT_VBRK-BUKRS AND
                  BRANCH = LT_VBRK-BUPLA.

    SELECT * FROM T001
             INTO CORRESPONDING FIELDS OF TABLE LT_T001
             FOR ALL ENTRIES IN LT_VBRK
             WHERE BUKRS = LT_VBRK-BUKRS.

    SELECT
         BUKRS
         VKORG
         FKART
         BASE_KSCHL
         DISC_KSCHL
         OTHER_KSCHL
         TYPE
         CATEGORY
         EXPCAT
         FLAG
         FOC_FLAG
      FROM ZEINV_LINK INTO TABLE LT_ZEINV_LINK
      FOR ALL ENTRIES IN LT_VBRK
      WHERE
      BUKRS = LT_VBRK-BUKRS AND
      FKART = LT_VBRK-FKART AND
      VKORG = LT_VBRK-VKORG.


    SELECT ZTERM TEXT1 FROM T052U INTO TABLE LT_T052U
      FOR ALL ENTRIES IN LT_VBRK
      WHERE ZTERM = LT_VBRK-ZTERM.



    IF LT_VBRP IS NOT INITIAL.

      SELECT MATNR WERKS STEUC FROM MARC INTO TABLE LT_MARC
        FOR ALL ENTRIES IN LT_VBRP
        WHERE MATNR = LT_VBRP-MATNR AND
              WERKS = LT_VBRP-WERKS.

      SELECT VBELN VKORG VSTEL
        KUNNR
        KUNAG
        FROM LIKP
        INTO TABLE LT_LIKP
        FOR ALL ENTRIES IN LT_VBRP
        WHERE VBELN = LT_VBRP-VGBEL.


      SELECT
        WERKS NAME1  KUNNR LIFNR ADRNR
          FROM T001W
                INTO  TABLE LT_T001W
                FOR ALL ENTRIES IN LT_VBRP
                WHERE WERKS = LT_VBRP-WERKS.


      IF LT_T001W IS NOT INITIAL.
        SELECT
          ADDRNUMBER
          NAME1
          CITY1
          POST_CODE1
          STREET
          STR_SUPPL1
          STR_SUPPL2
          LOCATION
          COUNTRY
          REGION
          SORT1
          MC_CITY1
          TEL_NUMBER

           FROM ADRC
                 INTO CORRESPONDING FIELDS OF TABLE LT_ADRC
                 FOR ALL ENTRIES IN LT_T001W
                 WHERE ADDRNUMBER = LT_T001W-ADRNR.
      ENDIF.
    ENDIF.

    IF LT_ADRC IS NOT INITIAL.

      SELECT
        ZSTCODE
        ZSAPCODE
        ZSTDECR
        FROM ZSTATE_CODE
        INTO TABLE LT_ZSTATE_CODE
        FOR ALL ENTRIES IN LT_ADRC
        WHERE ZSAPCODE EQ LT_ADRC-REGION.

    ENDIF.


    IF LT_LIKP IS NOT INITIAL.
      SELECT
        KUNNR LAND1 NAME1 PSTLZ REGIO ADRNR STCD3
         FROM KNA1
               INTO TABLE LT_KNA1
               FOR ALL ENTRIES IN LT_LIKP
               WHERE KUNNR = LT_LIKP-KUNNR.


      SELECT VBELN POSNR PARVW KUNNR FROM VBPA
        INTO TABLE LT_VBPA
        FOR ALL ENTRIES IN LT_LIKP WHERE
        VBELN = LT_LIKP-VBELN AND PARVW = 'ZS'.

      IF LT_VBPA[] IS NOT INITIAL.
        SELECT KUNNR LOCCO FROM KNA1 INTO TABLE LT_KNA1_EXP
          FOR ALL ENTRIES IN LT_VBPA
          WHERE KUNNR = LT_VBPA-KUNNR.


        LOOP AT LT_VBPA INTO LS_VBPA.

          READ TABLE LT_KNA1_EXP INTO LS_KNA1_EXP WITH KEY KUNNR = LS_VBPA-KUNNR.
          IF SY-SUBRC EQ 0.
            LOOP AT LT_LIKP INTO LS_LIKP WHERE VBELN  = LS_VBPA-VBELN .
              LS_LIKP-KUNNR = LS_KNA1_EXP-KUNNR.
              MODIFY LT_LIKP FROM LS_LIKP TRANSPORTING KUNNR.
            ENDLOOP.
          ENDIF.
        ENDLOOP.
      ENDIF.
*         ENDIF.



      SELECT KUNNR ALAND TATYP TAXKD
      FROM KNVI INTO TABLE LT_KNVI_EXPWP
       FOR ALL ENTRIES IN LT_LIKP
      WHERE KUNNR = LT_LIKP-KUNAG AND TAXKD = '0' AND TATYP =  'JOIG'.

      SELECT KUNNR ALAND TATYP TAXKD
      FROM KNVI INTO TABLE LT_KNVI_DEXP
       FOR ALL ENTRIES IN LT_LIKP
      WHERE KUNNR = LT_LIKP-KUNAG AND TAXKD = '3' AND ( TATYP = 'JOCG'  OR TATYP =  'JOIG' OR TATYP = 'JOSG' ).

      DESCRIBE TABLE LT_KNVI_DEXP LINES LV_RECORS_D.




      SELECT KUNNR ALAND TATYP TAXKD
      FROM KNVI INTO TABLE LT_KNVI_SEZEXP
       FOR ALL ENTRIES IN LT_LIKP
      WHERE KUNNR = LT_LIKP-KUNAG AND TAXKD = '2' AND ( TATYP = 'JOCG'  OR TATYP =  'JOIG' OR TATYP = 'JOSG' ).

      DESCRIBE TABLE LT_KNVI_SEZEXP LINES LV_RECORS_S.

    ENDIF.

  ELSE.

    LS_RETMSG-ID = 'E'.
    LS_RETMSG-MESSAGE = 'No Data Available'.
    LV_ERROR = 'X'.
    APPEND LS_RETMSG TO LT_RETMSG.
    CLEAR LS_RETMSG.
    EXIT.
    LEAVE LIST-PROCESSING.

  ENDIF.

*  PERFORM process_data CHANGING lt_final.


  "===============================================================================================
  " Process Data
  "===============================================================================================

  "--New Code-----------------------------------------
*BREAK PRIMUS.
  LOOP AT LT_VBRK INTO LS_VBRK.


    IF LS_VBRK-RFBSK = 'C'.  "--Check is posting is completed or not 'C' = posting Done.
      READ TABLE LT_VBRP INTO LS_VBRP WITH KEY VBELN = LS_VBRK-VBELN.
      IF SY-SUBRC IS INITIAL.
        READ TABLE LT_LIKP INTO LS_LIKP WITH KEY  VBELN = LS_VBRP-VGBEL.
        IF SY-SUBRC IS INITIAL.

          IF LS_VBRP-WERKS EQ  LS_LIKP-VSTEL AND LS_LIKP-KUNAG EQ LS_LIKP-KUNNR.
            LV_TYP = LC_TYP_REG.                            "'REG'.
          ELSEIF LS_LIKP-VSTEL NE LS_VBRP-WERKS AND LS_LIKP-KUNAG EQ LS_LIKP-KUNNR.
            LV_TYP  = LC_TYP_DIS.
          ELSEIF LS_LIKP-KUNAG NE LS_LIKP-KUNNR.
            LV_TYP  = LC_TYP_SHP.
          ELSEIF LS_LIKP-VSTEL NE LS_VBRP-WERKS AND LS_LIKP-KUNAG NE LS_LIKP-KUNNR.
            LV_TYP  = LC_TYP_CMB.
          ENDIF.
        ELSE.
          IF LS_VBRK-FKART = 'ZSER' OR LS_VBRK-FKART = 'ZESS' OR LS_VBRK-FKART = 'ZLIS' .

            LV_TYP  = LC_TYP_SER.

          ENDIF.
        ENDIF.
      ENDIF.
      "--Addr Details for REG  DIS SHP CMB

      CALL FUNCTION 'ZEINV_GET_ADRC_DATA'
        EXPORTING
          I_VBRP     = LS_VBRP
          I_LIKP     = LS_LIKP
          I_INVTYP   = LV_TYP
        IMPORTING
          E_SEL_ADDR = LS_SEL_ADDR
          E_DIS_ADDR = LS_DIS_ADDR
          E_BUY_ADDR = LS_BUY_ADDR
          E_SHP_ADDR = LS_SHP_ADDR.

************************************************************************************
      "--INR Details
************************************************************************************
      LS_FINAL-VERSION = LC_VERSION.            "'1.0'.
      LS_FINAL-IRN = ''.
************************************************************************************
      "--TranDtls (Transaction Details)---------
************************************************************************************

      READ TABLE LT_ZEINV_LINK INTO LS_ZEINV_LINK WITH KEY BUKRS = LS_VBRK-BUKRS  FKART = LS_VBRK-FKART VKORG = LS_VBRK-VKORG.
      IF SY-SUBRC IS INITIAL .
        LS_FINAL-TRANDTLS-TAXSCH = LC_TAXSCH.  "'GST'.
        LS_FINAL-TRANDTLS-REGREV = LC_REGREV.               "Y/N
        LS_FINAL-TRANDTLS-ECMGSTIN = LC_NULL.

        IF LS_ZEINV_LINK-CATEGORY IS NOT INITIAL. "'B2B'..
          LS_FINAL-TRANDTLS-SUPTYP = LS_ZEINV_LINK-CATEGORY. "'B2B'.
        ELSE.
          READ TABLE LT_KNVI_DEXP INTO LS_KNVI_DEXP WITH KEY KUNNR = LS_LIKP-KUNAG.
          IF SY-SUBRC EQ 0 AND LV_RECORS_D EQ '3' AND LS_BUY_ADDR-COUNTRY EQ 'IN'.
            LS_FINAL-TRANDTLS-SUPTYP = 'DEXP'.
          ENDIF.

          READ TABLE LT_KNVI_EXPWP INTO LS_KNVI_EXPWP WITH KEY KUNNR = LS_LIKP-KUNAG.
          IF SY-SUBRC EQ 0 AND LS_BUY_ADDR-COUNTRY NE 'IN'.

            SELECT SINGLE  KNUMV KSCHL KSTAT FROM PRCD_ELEMENTS  INTO LS_KONV_EXP
*            SELECT SINGLE  knumv kschl kstat FROM konv INTO ls_konv_exp  " commented by amit
            WHERE KNUMV = LS_VBRK-KNUMV AND KSCHL = LS_ZEINV_LINK-BASE_KSCHL.
            IF SY-SUBRC EQ 0.
              IF LS_KONV_EXP-KSTAT = 'X'.
                LS_FINAL-TRANDTLS-SUPTYP = 'EXPWOP'.
              ELSE.
                LS_FINAL-TRANDTLS-SUPTYP = 'EXPWP'.
              ENDIF.
            ENDIF.
          ENDIF.


          READ TABLE LT_KNVI_SEZEXP INTO LS_KNVI_SEZEXP WITH KEY KUNNR = LS_LIKP-KUNAG.
          IF SY-SUBRC EQ 0 AND LV_RECORS_S EQ '3'.
            SELECT SINGLE  KNUMV KSCHL KSTAT FROM PRCD_ELEMENTS INTO LS_KONV_EXP
*            SELECT SINGLE  knumv kschl kstat FROM konv INTO ls_konv_exp  "commented by amit
            WHERE KNUMV = LS_VBRK-KNUMV AND KSCHL = LS_ZEINV_LINK-BASE_KSCHL.
            IF SY-SUBRC EQ 0.
              IF LS_KONV_EXP-KSTAT = 'X'.
                LS_FINAL-TRANDTLS-SUPTYP = 'SEZWOP'.
              ELSE.
                LS_FINAL-TRANDTLS-SUPTYP = 'SEZWP'.
              ENDIF.
            ENDIF.
          ENDIF.


        ENDIF.

        IF LS_VBRK-FKART = 'ZSER' AND LS_VBRK-VTWEG = '20'.
          LS_FINAL-TRANDTLS-SUPTYP = 'SEZWOP'.
        ELSEIF LS_VBRK-FKART = 'ZFRS' AND LS_VBRK-VTWEG = '20'.
          LS_FINAL-TRANDTLS-SUPTYP = 'SEZWOP'.
        ELSEIF LS_VBRK-FKART = 'ZFRS' AND LS_VBRK-VTWEG = '30'.  "Added By Nilay On 15.06.2023
          LS_FINAL-TRANDTLS-SUPTYP = 'EXPWOP'.
        ENDIF.

************        Avinash Bhagat
        IF LS_VBRK-FKART = 'ZFOC' AND LS_VBRK-WAERK NE 'INR' .
          LS_FINAL-TRANDTLS-SUPTYP = 'EXPWOP'.
        ENDIF.
***        end Avinash Bhagat

        IF LS_FINAL-TRANDTLS-ECMGSTIN IS NOT INITIAL.
          LS_UPDATE-TRANDTLS = 'X'.
        ENDIF.
************************************************************************************
        "--DocDtls (Document Details)--------------
************************************************************************************

        CONCATENATE LS_VBRK-FKDAT+6(02) '/' LS_VBRK-FKDAT+4(02) '/' LS_VBRK-FKDAT(04)  INTO LV_DATE.
*       CONCATENATE sy-datum+6(02) '/' sy-datum+4(02) '/' sy-datum(04)  INTO lv_date.                        " ??????????????????????????????

        LS_FINAL-ZDOCDTLS-ZTYP = LS_ZEINV_LINK-TYPE.

        SHIFT LS_VBRK-XBLNR LEFT DELETING LEADING '0'.
        LS_FINAL-ZDOCDTLS-ZNO  = LS_VBRK-XBLNR.
        LS_FINAL-ZDOCDTLS-ZDT  = LV_DATE.
      ELSE.
        MESSAGE E000 WITH LS_VBRK-BUKRS LS_VBRK-FKART LS_VBRK-VKORG. "'Please maintain zirn_link table '   TYPE 'E' DISPLAY LIKE 'E'.
      ENDIF.
************************************************************************************
      "--SellerDtls (Seller Details)------------------
************************************************************************************
      READ TABLE LT_T001 INTO LS_T001 WITH KEY BUKRS = LS_VBRK-BUKRS.
      IF SY-SUBRC IS INITIAL.
        LS_FINAL-SELLERDTLS-LGLNM  = LS_T001-BUTXT.
        LS_FINAL-SELLERDTLS-TRDNM  = LS_T001-BUTXT.
      ENDIF.

      READ TABLE LT_J_1BBRANCH INTO LS_J_1BBRANCH WITH KEY BUKRS = LS_VBRK-BUKRS BRANCH = LS_VBRK-BUPLA.
      IF SY-SUBRC IS INITIAL.
        IF LV_MODE = 'X'.
          LS_FINAL-SELLERDTLS-GSTIN  =  LS_J_1BBRANCH-GSTIN."'27AACCD2898L1Z4'."'24AAAPI3182M002'. "ls_t001-gstin
        ELSE.
          LS_FINAL-SELLERDTLS-GSTIN  =  LS_J_1BBRANCH-GSTIN." '24AAAPI3182M002'. "ls_t001-gstin
        ENDIF.

      ELSE.
        LS_FINAL-SELLERDTLS-GSTIN  = 'URP'.
      ENDIF.
      LS_FINAL-SELLERDTLS-ADDR1  =  LS_SEL_ADDR-STR_SUPPL1.

      IF LS_SEL_ADDR-STR_SUPPL2 IS INITIAL.
        LS_FINAL-SELLERDTLS-ADDR2  = LC_NULL.
      ELSE.
        LS_FINAL-SELLERDTLS-ADDR2  = LS_SEL_ADDR-STR_SUPPL2.
      ENDIF.

      LS_FINAL-SELLERDTLS-ZLOC    = LS_SEL_ADDR-MC_CITY1.
      LS_FINAL-SELLERDTLS-ZPIN    = LS_SEL_ADDR-POST_CODE1.
      IF LV_MODE = 'X'.
        LS_FINAL-SELLERDTLS-ZSTATE  = LS_SEL_ADDR-REGION."'MAHARASHTRA'.
      ELSE.
        LS_FINAL-SELLERDTLS-ZSTATE  = LS_SEL_ADDR-REGION.
      ENDIF.

      LS_FINAL-SELLERDTLS-ZEM     = LC_NULL.
      IF LS_SEL_ADDR-TEL_NUMBER IS NOT INITIAL.
        LS_FINAL-SELLERDTLS-ZPH     = LC_NULL."ls_sel_addr-tel_number.

      ELSE.
        LS_FINAL-SELLERDTLS-ZPH = LC_NULL.
      ENDIF.


      "Code to remove Special Char.
      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-LGLNM WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SELLERDTLS-LGLNM WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SELLERDTLS-LGLNM WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-SELLERDTLS-LGLNM TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-SELLERDTLS-LGLNM.
      CLEAR : E_TEXT, I_TEXT.
      "end of  remove speccial char.


      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-TRDNM WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-TRDNM WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-TRDNM WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-SELLERDTLS-TRDNM TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-SELLERDTLS-TRDNM.
      CLEAR : E_TEXT, I_TEXT.



      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-ADDR1 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SELLERDTLS-ADDR1 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SELLERDTLS-ADDR1 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-SELLERDTLS-ADDR1 TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-SELLERDTLS-ADDR1.
      CLEAR : E_TEXT, I_TEXT.




      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-ADDR2 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SELLERDTLS-ADDR2 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SELLERDTLS-ADDR2 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-SELLERDTLS-ADDR2 TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-SELLERDTLS-ADDR2.
      CLEAR : E_TEXT, I_TEXT.


      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-ZLOC WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SELLERDTLS-ZLOC WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SELLERDTLS-ZLOC WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-SELLERDTLS-ZLOC TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-SELLERDTLS-ZLOC.
      CLEAR : E_TEXT, I_TEXT.


      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SELLERDTLS-ZSTATE  WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SELLERDTLS-ZSTATE  WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SELLERDTLS-ZSTATE  WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-SELLERDTLS-ZSTATE TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-SELLERDTLS-ZSTATE.
      CLEAR : E_TEXT, I_TEXT.






************************************************************************************
      "--BuyerDtls (Buyers Details)------
************************************************************************************

*      IF lv_mode = 'X'.
*        ls_final-buyerdtls-gstin   = 'URP'."'23AAACJ3929N1ZE'.
*      ELSE.
*
*      ENDIF.
*
*      IF ls_final-buyerdtls-gstin IS INITIAL.
*        IF ls_final-trandtls-suptyp = 'EXPWP' OR ls_final-trandtls-suptyp = 'EXPWOP' OR ls_final-trandtls-suptyp = 'DEXP' .
*          ls_final-buyerdtls-gstin   = 'URP'.                                       "?????????????????????
*        ELSE.
*          ls_final-buyerdtls-gstin   = ls_buy_addr-gstin. "
*        ENDIF.
*
*      ENDIF.

      IF LS_BUY_ADDR-COUNTRY  NE 'IN'.
        LS_FINAL-BUYERDTLS-GSTIN   = 'URP'.
      ELSE.
        LS_FINAL-BUYERDTLS-GSTIN   = LS_BUY_ADDR-GSTIN. "
      ENDIF.
      LS_FINAL-BUYERDTLS-LGLNM   = LS_BUY_ADDR-NAME1.
      LS_FINAL-BUYERDTLS-TRDNM   = LS_BUY_ADDR-NAME1.

      LS_FINAL-BUYERDTLS-ZPOS     = LS_BUY_ADDR-REGION.
      IF LS_BUY_ADDR-COUNTRY  NE 'IN'.
        LS_FINAL-BUYERDTLS-ZPOS = '96'.
      ENDIF.
      LS_FINAL-BUYERDTLS-ADDR1   = LS_BUY_ADDR-STREET. "ls_buy_addr-str_suppl1.temp>>>>>>>>>>>>>>>>>>>>>>>>>>

      IF LS_BUY_ADDR-STR_SUPPL2 IS INITIAL.
        LS_FINAL-BUYERDTLS-ADDR2   = LC_NULL.
      ELSE.
        LS_FINAL-BUYERDTLS-ADDR2   = LS_BUY_ADDR-STR_SUPPL2.
      ENDIF.

      LS_FINAL-BUYERDTLS-ZLOC     = LS_BUY_ADDR-MC_CITY1.

      IF LV_MODE = 'X'.
        LS_FINAL-BUYERDTLS-ZSTATE   = LS_BUY_ADDR-REGION.
      ELSE.
        LS_FINAL-BUYERDTLS-ZSTATE   = LS_BUY_ADDR-REGION.
      ENDIF.
      IF LS_BUY_ADDR-COUNTRY  NE 'IN'.
        LS_FINAL-BUYERDTLS-ZSTATE   = '96'.   "State Code Shuold be 96 for export case
        LS_FINAL-BUYERDTLS-ZPIN      = '999999'.
      ELSE.

        LS_FINAL-BUYERDTLS-ZPIN      = LS_BUY_ADDR-POST_CODE1.
      ENDIF.


      LS_FINAL-BUYERDTLS-ZPH      = LC_NULL."ls_buy_addr-tel_number.

      IF LS_BUY_ADDR-TEL_NUMBER IS INITIAL.
        LS_FINAL-BUYERDTLS-ZPH = LC_NULL.
      ENDIF.

      LS_FINAL-BUYERDTLS-ZEM      = LC_NULL.

      "Code to remove Special Char----------------------------------------------------------------------------

      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-BUYERDTLS-LGLNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-BUYERDTLS-LGLNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-BUYERDTLS-LGLNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-BUYERDTLS-LGLNM TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-BUYERDTLS-LGLNM.
      CLEAR : E_TEXT, I_TEXT.


      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-BUYERDTLS-TRDNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-BUYERDTLS-TRDNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-BUYERDTLS-TRDNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-BUYERDTLS-TRDNM TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-BUYERDTLS-TRDNM.
      CLEAR : E_TEXT, I_TEXT.



      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-BUYERDTLS-ADDR1    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-BUYERDTLS-ADDR1    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-BUYERDTLS-ADDR1    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-BUYERDTLS-ADDR1 TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-BUYERDTLS-ADDR1.
      CLEAR : E_TEXT, I_TEXT.



      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-BUYERDTLS-ADDR2    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-BUYERDTLS-ADDR2    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-BUYERDTLS-ADDR2    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-BUYERDTLS-ADDR2 TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-BUYERDTLS-ADDR2.
      CLEAR : E_TEXT, I_TEXT.



      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-BUYERDTLS-ZLOC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-BUYERDTLS-ZLOC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-BUYERDTLS-ZLOC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-BUYERDTLS-ZLOC TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-BUYERDTLS-ZLOC.
      CLEAR : E_TEXT, I_TEXT.



      REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-BUYERDTLS-ZSTATE    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-BUYERDTLS-ZSTATE    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-BUYERDTLS-ZSTATE    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
      MOVE LS_FINAL-BUYERDTLS-ZSTATE TO I_TEXT.
      PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
      MOVE E_TEXT TO LS_FINAL-BUYERDTLS-ZSTATE.
      CLEAR : E_TEXT, I_TEXT.

      "End of Remove Special Char----------------------------------------------------------------------------------




************************************************************************************
      "--DispDtls (Display Details)------------
************************************************************************************
      IF LS_DIS_ADDR IS NOT INITIAL.
        LS_FINAL-DISPDTLS-ZNM     =   LS_DIS_ADDR-NAME1.      "Required
        LS_FINAL-DISPDTLS-ADDR1   =   LS_DIS_ADDR-STR_SUPPL1.
        IF LS_DIS_ADDR-STR_SUPPL2 IS INITIAL.
          LS_FINAL-DISPDTLS-ADDR2   =   LC_NULL.
        ELSE.
          LS_FINAL-DISPDTLS-ADDR2   =   LS_DIS_ADDR-STR_SUPPL2.
        ENDIF.

        LS_FINAL-DISPDTLS-ZLOC     =   LS_DIS_ADDR-MC_CITY1.   "Required
        LS_FINAL-DISPDTLS-ZPIN     =   LS_DIS_ADDR-POST_CODE1. "Required
        LS_FINAL-DISPDTLS-STCD    =   LS_DIS_ADDR-REGION.     "Required

        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-DISPDTLS-ZNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-DISPDTLS-ZNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-DISPDTLS-ZNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-DISPDTLS-ZNM TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-DISPDTLS-ZNM.
        CLEAR : E_TEXT, I_TEXT.



        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-DISPDTLS-ADDR1 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-DISPDTLS-ADDR1 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-DISPDTLS-ADDR1 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-DISPDTLS-ADDR1 TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-DISPDTLS-ADDR1.
        CLEAR : E_TEXT, I_TEXT.


        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-DISPDTLS-ADDR2 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-DISPDTLS-ADDR2 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-DISPDTLS-ADDR2 WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-DISPDTLS-ADDR2 TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-DISPDTLS-ADDR2.
        CLEAR : E_TEXT, I_TEXT.


        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-DISPDTLS-ZLOC   WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '%' IN LS_FINAL-DISPDTLS-ZLOC   WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-DISPDTLS-ZLOC   WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-DISPDTLS-ZLOC TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-DISPDTLS-ZLOC.
        CLEAR : E_TEXT, I_TEXT.


        LS_UPDATE-DISPDTLS = 'X'.
      ENDIF.
************************************************************************************
      "--ShipDtls (Shipping Details)------------
************************************************************************************
      IF LS_SHP_ADDR IS NOT INITIAL.
        IF LV_MODE = 'X'.
          LS_FINAL-SHIPDTLS-GSTIN   =   LS_SHP_ADDR-GSTIN."'23AAACJ3929N1ZE'.
        ELSE.
          LS_FINAL-SHIPDTLS-GSTIN   =   LS_SHP_ADDR-GSTIN.
        ENDIF.

        IF LS_SHP_ADDR-GSTIN IS INITIAL.
          LS_FINAL-SHIPDTLS-GSTIN   = 'URP'.
        ENDIF.
        LS_FINAL-SHIPDTLS-LGLNM   =   LS_SHP_ADDR-NAME1.
        LS_FINAL-SHIPDTLS-TRDNM   =   LS_SHP_ADDR-NAME1.
        LS_FINAL-SHIPDTLS-ADDR1   =   LS_SHP_ADDR-STREET."ls_shp_addr-str_suppl1. temp>>>>>>>>>>>>>>>>>>>>

        IF LS_SHP_ADDR-STR_SUPPL2 IS INITIAL.
          LS_FINAL-SHIPDTLS-ADDR2   =  LC_NULL.
        ELSE.
          LS_FINAL-SHIPDTLS-ADDR2   =   LS_SHP_ADDR-STR_SUPPL2.
        ENDIF.

        LS_FINAL-SHIPDTLS-ZLOC     =   LS_SHP_ADDR-MC_CITY1.
*        ls_final-shipdtls-zpin     =   ls_shp_addr-post_code1.
*        IF ls_shp_addr-region IS NOT INITIAL.
*          ls_final-shipdtls-stcd    =   ls_shp_addr-region.
*        ENDIF.

        IF LS_SHP_ADDR-COUNTRY NE 'IN'.
          LS_FINAL-SHIPDTLS-ZPIN     =  '999999'."ls_shp_addr-post_code1.
          LS_FINAL-SHIPDTLS-STCD    =   '96'."ls_shp_addr-region.
        ELSE.
          LS_FINAL-SHIPDTLS-ZPIN     =   LS_SHP_ADDR-POST_CODE1.
          IF LS_SHP_ADDR-REGION IS NOT INITIAL..
            LS_FINAL-SHIPDTLS-STCD    =   LS_SHP_ADDR-REGION.
          ENDIF.
        ENDIF.

        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SHIPDTLS-LGLNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SHIPDTLS-LGLNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SHIPDTLS-LGLNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-SHIPDTLS-LGLNM TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-SHIPDTLS-LGLNM.
        CLEAR : E_TEXT, I_TEXT.


        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SHIPDTLS-TRDNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SHIPDTLS-TRDNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SHIPDTLS-TRDNM    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-SHIPDTLS-TRDNM TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-SHIPDTLS-TRDNM.
        CLEAR : E_TEXT, I_TEXT.



        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SHIPDTLS-ADDR1    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SHIPDTLS-ADDR1    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SHIPDTLS-ADDR1    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-SHIPDTLS-ADDR1 TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-SHIPDTLS-ADDR1.
        CLEAR : E_TEXT, I_TEXT.



        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SHIPDTLS-ADDR2    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SHIPDTLS-ADDR2    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SHIPDTLS-ADDR2    WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-SHIPDTLS-ADDR2 TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-SHIPDTLS-ADDR2.
        CLEAR : E_TEXT, I_TEXT.



        REPLACE ALL OCCURRENCES OF ',' IN LS_FINAL-SHIPDTLS-ZLOC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_FINAL-SHIPDTLS-ZLOC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_FINAL-SHIPDTLS-ZLOC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        MOVE LS_FINAL-SHIPDTLS-ZLOC TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_FINAL-SHIPDTLS-ZLOC.
        CLEAR : E_TEXT, I_TEXT.

        LS_UPDATE-SHIPDTLS = 'X'.
      ENDIF.
************************************************************************************
      "--itemlist (Item Details)------------
************************************************************************************
      LOOP AT LT_VBRP INTO LS_VBRP WHERE VBELN = LS_VBRK-VBELN.


        LS_ITEMLIST-ZSLNO                 = LS_VBRP-POSNR.
        LS_ITEMLIST-PRDDESC              = LS_VBRP-ARKTX.

        REPLACE ALL OCCURRENCES OF ',' IN LS_ITEMLIST-PRDDESC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '&' IN LS_ITEMLIST-PRDDESC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '/' IN LS_ITEMLIST-PRDDESC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '\' IN LS_ITEMLIST-PRDDESC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
        REPLACE ALL OCCURRENCES OF '"'  IN LS_ITEMLIST-PRDDESC      WITH CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.

        MOVE LS_ITEMLIST-PRDDESC TO I_TEXT.
        PERFORM ES_REMOVE_SPECIAL_CHARACTER USING I_TEXT CHANGING E_TEXT.
        MOVE E_TEXT TO LS_ITEMLIST-PRDDESC.
        CLEAR : E_TEXT, I_TEXT.


        READ TABLE LT_MARC INTO LS_MARC WITH KEY MATNR = LS_VBRP-MATNR WERKS = LS_VBRP-WERKS.
        IF SY-SUBRC IS INITIAL.
*          ls_itemlist-hsncd                =   ls_marc-steuc(06). "Changed by Nilay B. on 15.12.2023
          LS_ITEMLIST-HSNCD                =   LS_MARC-STEUC(08). "Changed by jyoti on 04.12.2024
          "'23099010'."   ??????????????????????????????????????????????????


          IF LS_MARC-STEUC+0(2) = '99'.
            LS_ITEMLIST-ISSERVC  = 'Y'.
          ELSE.
            LS_ITEMLIST-ISSERVC              =  'N' .
          ENDIF.

        ENDIF.
        LS_ITEMLIST-BARCDE               =   LC_NULL.
        LS_ITEMLIST-QNTY                  =   LS_VBRP-FKIMG.


        READ TABLE LT_ZEINV_LINK INTO LS_ZEINV_LINK WITH KEY BUKRS = LS_VBRK-BUKRS  FKART = LS_VBRK-FKART VKORG = LS_VBRK-VKORG FOC_FLAG = 'X' .
        IF SY-SUBRC IS INITIAL.
          LS_ITEMLIST-FREEQTY              =   LS_VBRP-FKIMG.
        ELSE.
          LS_ITEMLIST-FREEQTY              =   '0'.
        ENDIF.

        "Convert  SAP Unit to IRP Unit.
        CALL FUNCTION 'ZEINV_UNIT_CONVERT'
          EXPORTING
            VRKME = LS_VBRP-VRKME
          IMPORTING
            UNIT  = LS_ITEMLIST-UNITS.
        " Get unitprice and totamt

        IF LS_VBRK-WAERK EQ 'INR'.


          SELECT SINGLE KBETR KWERT
                              FROM PRCD_ELEMENTS INTO ( LS_ITEMLIST-UNITPRICE, LS_ITEMLIST-TOTAMT  )
*                              FROM konv INTO ( ls_itemlist-unitprice, ls_itemlist-totamt  )  "commented by Amit
                              WHERE KNUMV = LS_VBRK-KNUMV AND
                                    KPOSN = LS_VBRP-POSNR AND
                                    ( KSCHL = LS_ZEINV_LINK-BASE_KSCHL )."'ZPRO' ).

        ELSEIF LS_VBRK-WAERK NE 'INR'.

          SELECT SINGLE KBETR KWERT
                              FROM PRCD_ELEMENTS INTO ( LS_ITEMLIST-UNITPRICE, LS_ITEMLIST-TOTAMT )
*                              FROM konv INTO ( ls_itemlist-unitprice, ls_itemlist-totamt )  "commenetd by  Amit
                              WHERE KNUMV = LS_VBRK-KNUMV AND
                                    KPOSN = LS_VBRP-POSNR AND
                                    ( KSCHL = LS_ZEINV_LINK-BASE_KSCHL )."'ZPRO' ).

          SELECT SINGLE KKURS
                              FROM PRCD_ELEMENTS INTO LS_KKURS
*                              FROM konv INTO ls_kkurs    "COMMENTED BY AMIT
                              WHERE KNUMV = LS_VBRK-KNUMV AND
                                    KPOSN = LS_VBRP-POSNR AND
                                    ( KSCHL = 'VPRS' ).


          LS_ITEMLIST-UNITPRICE = LS_ITEMLIST-UNITPRICE * LS_KKURS.
          LS_ITEMLIST-TOTAMT = LS_ITEMLIST-TOTAMT * LS_KKURS.

        ENDIF.

        "------------Other Condition------------
        SELECT  KBETR KWERT KSCHL FROM PRCD_ELEMENTS
*        SELECT  kbetr kwert kschl FROM konv  "COMMENTED BY AMIT
                    INTO CORRESPONDING FIELDS OF TABLE LT_KONV_T
                    FOR ALL ENTRIES IN LT_ZEINV_LINK
                    WHERE KNUMV = LS_VBRK-KNUMV AND
                          KPOSN = LS_VBRP-POSNR AND
                          ( KSCHL = LT_ZEINV_LINK-OTHER_KSCHL ).
        LOOP AT LT_KONV_T.
          LS_ITEMLIST-OTHCHRG             =  LS_ITEMLIST-OTHCHRG + ( LT_KONV_T-KWERT * -1 ).
        ENDLOOP.
        IF LS_ITEMLIST-OTHCHRG LT 0.
          LS_ITEMLIST-OTHCHRG  = LS_ITEMLIST-OTHCHRG * -1.
        ENDIF.
*        ls_itemlist-assamt = ls_itemlist-assamt." + ls_itemlist-othchrg." . ???Commented (other charge added in totamt )
        REFRESH LT_KONV_T.
        BREAK PRIMUS.
        IF LS_VBRK-WAERK NE 'INR'.
          LS_ITEMLIST-OTHCHRG = LS_ITEMLIST-OTHCHRG * LS_KKURS.
        ENDIF.


        "code added to sum tot amt and other charge.
        LS_ITEMLIST-TOTAMT = LS_ITEMLIST-TOTAMT + LS_ITEMLIST-OTHCHRG.
        "End of add.



        "------------Discount Condition------------

        SELECT  KBETR KWERT KSCHL FROM PRCD_ELEMENTS
*        SELECT  kbetr kwert kschl FROM konv    "COMMENTED BY AMIT
                    INTO CORRESPONDING FIELDS OF TABLE LT_KONV_T
                    FOR ALL ENTRIES IN LT_ZEINV_LINK
                    WHERE KNUMV   = LS_VBRK-KNUMV AND
                          KPOSN   = LS_VBRP-POSNR AND
                          ( KSCHL = LT_ZEINV_LINK-DISC_KSCHL ).
        LOOP AT LT_KONV_T.
          LS_ITEMLIST-DISCOUNT    =  LS_ITEMLIST-DISCOUNT + ( LT_KONV_T-KWERT * -1 ).
        ENDLOOP.
        REFRESH LT_KONV_T.

        LS_ITEMLIST-PRETAXVAL     ='0.00'.
        LS_ITEMLIST-ASSAMT        = LS_ITEMLIST-TOTAMT - LS_ITEMLIST-DISCOUNT.
        IF LS_ITEMLIST-ASSAMT LT 0.
          LS_ITEMLIST-ASSAMT       = LS_ITEMLIST-ASSAMT * -1.
        ENDIF.


        "------------GST Condition------------

        SELECT  KBETR KWERT KSCHL KKURS FROM PRCD_ELEMENTS
*        SELECT  kbetr kwert kschl kkurs FROM konv  "COMMENTED BY AMIT
                            INTO CORRESPONDING FIELDS OF TABLE LT_KONV_T
                            WHERE KNUMV = LS_VBRK-KNUMV AND
                                  KPOSN = LS_VBRP-POSNR AND
                                   ( KSCHL = 'JOCG' OR KSCHL = 'JOSG' OR KSCHL = 'JOIG')
                                  AND KSTAT NE 'X'.

        LOOP AT LT_KONV_T.
          IF LT_KONV_T-KSCHL    = 'JOIG'.
            IF  LT_KONV_T-KBETR NE 0.
              LS_ITEMLIST-GSTRT   = LT_KONV_T-KBETR." / 10.
              IF LS_VBRK-WAERK EQ 'INR'.
                LS_ITEMLIST-IGSTAMT = LT_KONV_T-KWERT.
              ELSEIF LS_VBRK-WAERK NE 'INR'.
                LS_ITEMLIST-IGSTAMT = LT_KONV_T-KWERT * LS_KKURS.
*                lv_roundoff_amt     = ( ls_itemlist-assamt * ls_itemlist-gstrt ) / 100 .
*                lv_roundoff         = ls_itemlist-igstamt - lv_roundoff_amt.
              ENDIF.
            ENDIF.

          ELSEIF LT_KONV_T-KSCHL = 'JOCG'.
            IF LT_KONV_T-KBETR NE 0.
              LS_ITEMLIST-GSTRT    =  LS_ITEMLIST-GSTRT + LT_KONV_T-KBETR." / 10.
              LS_ITEMLIST-CGSTAMT  =  LT_KONV_T-KWERT.
            ENDIF.
          ELSEIF LT_KONV_T-KSCHL = 'JOSG'.
            IF LT_KONV_T-KBETR NE 0.
              LS_ITEMLIST-GSTRT    =  LS_ITEMLIST-GSTRT + LT_KONV_T-KBETR." / 10.
              LS_ITEMLIST-SGSTAMT  = LT_KONV_T-KWERT.
            ENDIF.
          ENDIF.


        ENDLOOP.


        REFRESH LT_KONV_T.

        "------------CES Condition------------

        SELECT  KBETR KWERT KSCHL FROM PRCD_ELEMENTS
*        SELECT  kbetr kwert kschl FROM konv   "COMMENTED BY AMIT
                            INTO CORRESPONDING FIELDS OF TABLE LT_KONV_T
                            FOR ALL ENTRIES IN LT_ZEINV_LINK
                            WHERE KNUMV = LS_VBRK-KNUMV AND
                                  KPOSN = LS_VBRP-POSNR AND

                                  ( KSCHL = LT_ZEINV_LINK-OTHER_KSCHL ).
        LOOP AT LT_KONV_T.
          IF LT_KONV_T-KSCHL        = 'CES'.
            LS_ITEMLIST-ZCESRT      = LT_KONV_T-KBETR / 10.
            LS_ITEMLIST-ZCESAMT     = LT_KONV_T-KWERT.
          ELSEIF LT_KONV_T-KSCHL = 'statece'.
            LS_ITEMLIST-STATECESRT  = LT_KONV_T-KBETR / 10.
            LS_ITEMLIST-STATECESAMT = LT_KONV_T-KWERT.
          ENDIF.
        ENDLOOP.

        CLEAR : LS_ITEMLIST-OTHCHRG.
        "-------------------------JTC1 condition-------------------------
        SELECT  KBETR KWERT KSCHL FROM PRCD_ELEMENTS
*        SELECT  kbetr kwert kschl FROM konv  "COMMENETED BY AMIT
                    INTO CORRESPONDING FIELDS OF TABLE LT_KONV_T
*                    FOR ALL ENTRIES IN lt_zeinv_link
                    WHERE KNUMV = LS_VBRK-KNUMV AND
                          KPOSN = LS_VBRP-POSNR AND
                          ( KSCHL = 'JTC1' OR KSCHL = 'ZTCS' ).
        LOOP AT LT_KONV_T.
          LS_ITEMLIST-OTHCHRG  =  LT_KONV_T-KWERT.
        ENDLOOP.



*
*          CLEAR lt_konv_t.
        LS_ITEMLIST-ZCESRT               = '0.00'.
        LS_ITEMLIST-ZCESAMT              = '0.00'.
        LS_ITEMLIST-ZCESNONADVLAMT       = '0.00'.
        LS_ITEMLIST-STATECESRT           = '0.00'.
        LS_ITEMLIST-STATECESAMT          = '0.00'.
        LS_ITEMLIST-STATECESNONADVLAMT   = '0.00'.

        IF LS_ITEMLIST-GSTRT IS INITIAL.
          LS_ITEMLIST-GSTRT = '0.00'.
        ENDIF.

        LS_ITEMLIST-TOTITEMVAL    =  LS_ITEMLIST-ASSAMT + LS_ITEMLIST-IGSTAMT + LS_ITEMLIST-SGSTAMT + LS_ITEMLIST-CGSTAMT +
                                     LS_ITEMLIST-ZCESAMT + LS_ITEMLIST-ZCESNONADVLAMT + LS_ITEMLIST-STATECESAMT + LS_ITEMLIST-STATECESNONADVLAMT +
                                     LS_ITEMLIST-OTHCHRG .
        LS_ITEMLIST-ORDLINEREF    =  '0.00'.
        LS_ITEMLIST-ORGCNTRY      =  'IN'.
        LS_ITEMLIST-PRDSLNO       =  LC_NULL.
************************************************************
        "--bchdtl (Batch Details)------------------
***********************************************************
        LS_ITEMLIST-BCHDTLS-ZNM          = ''.
        LS_ITEMLIST-BCHDTLS-ZEXPDT       = 'null'.
        LS_ITEMLIST-BCHDTLS-WRDT         = 'null'.
        IF  LS_ITEMLIST-BCHDTLS-ZNM   IS NOT INITIAL.
          LS_UPDATE-BCHDTLS = 'X'.
        ENDIF.

        LS_ATTRIBDTLS-ZNM         =  LC_NULL.
        LS_ATTRIBDTLS-VALU        =  LC_NULL.


        APPEND LS_ATTRIBDTLS TO LT_ATTRIBDTLS.
        LS_ITEMLIST-ATTRIBDTLS  = LT_ATTRIBDTLS.

        APPEND LS_ITEMLIST TO LT_ITEMLIST.



        LV_TOTAL_VAL  = LV_TOTAL_VAL  + LS_ITEMLIST-TOTITEMVAL.
        LV_ASSVAL     = LS_ITEMLIST-ASSAMT  + LV_ASSVAL.
        LV_CGSTVAL    = LS_ITEMLIST-CGSTAMT + LV_CGSTVAL.
        LV_SGSTVAL    = LS_ITEMLIST-SGSTAMT + LV_SGSTVAL.
        LV_IGSTVAL    = LS_ITEMLIST-IGSTAMT + LV_IGSTVAL.
        LV_DISCOUNT   = LS_ITEMLIST-DISCOUNT + LV_DISCOUNT.


        CLEAR: LS_ITEMLIST , LS_ATTRIBDTLS ,LS_KKURS.


        REFRESH : LT_ATTRIBDTLS.
      ENDLOOP.

      LS_FINAL-ITEMLIST = LT_ITEMLIST.

      REFRESH: LT_ITEMLIST.

***********************************************************
      "--ValDtls (Values Details)------------------
***********************************************************

      LS_FINAL-VALDTLS-ASSVAL       = LV_ASSVAL.
      LS_FINAL-VALDTLS-CGSTVAL      = LV_CGSTVAL.
      LS_FINAL-VALDTLS-SGSTVAL      = LV_SGSTVAL.
      LS_FINAL-VALDTLS-IGSTVAL      = LV_IGSTVAL.
      LS_FINAL-VALDTLS-ZCESVAL      = ''."lv_cesval.3
      LS_FINAL-VALDTLS-STCESVAL     = ''."lv_stcesval.
      LS_FINAL-VALDTLS-RNDOFFAMT    = LV_ROUNDOFF.
      LS_FINAL-VALDTLS-ZTOTINVVAL   = LV_TOTAL_VAL.
      LS_FINAL-VALDTLS-TOTINVVALFC  = ''.
*      ls_final-valdtls-invforcur     = lc_null.
      LS_UPDATE-VALDTLS = 'X'.

*** Avinash
      IF LS_VBRK-FKART = 'ZEXP'.
        IF LS_FINAL-VALDTLS-IGSTVAL IS NOT INITIAL.
          LS_FINAL-TRANDTLS-SUPTYP = 'EXPWP'.
        ELSEIF LS_FINAL-VALDTLS-IGSTVAL IS INITIAL.
          LS_FINAL-TRANDTLS-SUPTYP = 'EXPWOP'.
        ENDIF.
      ENDIF.



**end avi **
***********************************************************
      "--PayDtls (Pay Details)---------------------
***********************************************************
      LS_FINAL-PAYDTLS-ZNM        = ''.
      LS_FINAL-PAYDTLS-ACCDET     = LC_NULL.
      LS_FINAL-PAYDTLS-MODES      = LC_NULL.
      LS_FINAL-PAYDTLS-FININSBR   = LC_NULL.
      LS_FINAL-PAYDTLS-PAYTERM    = LC_NULL.
      LS_FINAL-PAYDTLS-PAYINSTR   = LC_NULL.
      LS_FINAL-PAYDTLS-CRTRN      = LC_NULL.
      LS_FINAL-PAYDTLS-DIRDR      = LC_NULL.
      LS_FINAL-PAYDTLS-CRDAY      = LC_NULL.
      LS_FINAL-PAYDTLS-PAIDAMT    = '0.00'.
      LS_FINAL-PAYDTLS-PAYMTDUE   = '0.00'.
      IF  LS_FINAL-PAYDTLS-ZNM   IS NOT INITIAL.
        LS_UPDATE-PAYDTLS = 'X'.
      ENDIF.

***********************************************************
      "--RefDtls (Ref Details)----------------------
***********************************************************

      DATA :
        LV_CURRY    TYPE VBRK-GJAHR,
        LV_FY(4)    TYPE C,
        LV_PERIV    TYPE PERIV VALUE 'V3',
        LV_INVSTDT  TYPE SY-DATUM,
        LV_INVENDDT TYPE SY-DATUM.


      CALL FUNCTION 'GM_GET_FISCAL_YEAR'
        EXPORTING
          I_DATE                     = LS_VBRK-FKDAT
          I_FYV                      = LV_PERIV
        IMPORTING
          E_FY                       = LV_FY
        EXCEPTIONS
          FISCAL_YEAR_DOES_NOT_EXIST = 1
          NOT_DEFINED_FOR_DATE       = 2
          OTHERS                     = 3.
      IF SY-SUBRC <> 0.
* Implement suitable error handling here
      ENDIF.

      MOVE LV_FY TO LV_CURRY.

      CALL FUNCTION 'FIRST_AND_LAST_DAY_IN_YEAR_GET'
        EXPORTING
          I_GJAHR        = LV_CURRY
          I_PERIV        = LV_PERIV
        IMPORTING
          E_FIRST_DAY    = LV_INVSTDT
          E_LAST_DAY     = LV_INVENDDT
        EXCEPTIONS
          INPUT_FALSE    = 1
          T009_NOTFOUND  = 2
          T009B_NOTFOUND = 3
          OTHERS         = 4.
      IF SY-SUBRC <> 0.
* Implement suitable error handling here
      ENDIF.

      CONCATENATE LV_INVSTDT+6(02) '/' LV_INVSTDT+4(02) '/' LV_INVSTDT(04)  INTO LS_FINAL-REFDTLS-DOCPERDDTLS-INVSTDT.
      CONCATENATE LV_INVENDDT+6(02) '/' LV_INVENDDT+4(02) '/' LV_INVENDDT(04)  INTO LS_FINAL-REFDTLS-DOCPERDDTLS-INVENDDT.


      LS_FINAL-REFDTLS-INVRM        = LC_NULL.

      LS_PRECDOCDTLS-INVNO          = ''.
      LS_PRECDOCDTLS-INVDT          = LC_NULL.
      LS_PRECDOCDTLS-OTHREFNO       = LC_NULL.
      IF LS_PRECDOCDTLS-INVNO IS NOT INITIAL.
        LS_UPDATE-PRECDOCDTLS = 'X'.
      ENDIF.
      LS_CONTRDTLS-RECADVREFR       = LC_NULL.
      LS_CONTRDTLS-RECADVDT         = LC_NULL.
      LS_CONTRDTLS-TENDREFR         = LC_NULL.
      LS_CONTRDTLS-CONTRREFR        = LC_NULL.
      LS_CONTRDTLS-EXTREFR          = LC_NULL.
      LS_CONTRDTLS-PROJREFR         = LC_NULL.
      LS_CONTRDTLS-POREFR           = LC_NULL.
      LS_CONTRDTLS-POREFDT          = LC_NULL.
      IF LS_CONTRDTLS-RECADVREFR  IS NOT INITIAL.
        LS_UPDATE-CONTRDTLS = 'X'.
      ENDIF.
      APPEND LS_CONTRDTLS TO LT_CONTRDTLS.
      LS_FINAL-REFDTLS-CONTRDTLS  = LT_CONTRDTLS.
*      ls_final-refdtls-contrdtls    = ls_contrdtls.

      APPEND LS_PRECDOCDTLS TO LT_PRECDOCDTLS.
      LS_FINAL-REFDTLS-PRECDOCDTLS  = LT_PRECDOCDTLS.
*      ls_final-refdtls-precdocdtls  = ls_precdocdtls.

      CLEAR: LT_PRECDOCDTLS,LT_CONTRDTLS,LS_CONTRDTLS,LS_PRECDOCDTLS.

      IF LS_FINAL-REFDTLS-DOCPERDDTLS-INVSTDT IS NOT INITIAL.
*        ls_update-refdtls = 'X'.              ???????????????????????????
      ENDIF.

***********************************************************
*      ---ExpDtls------------------------------------ ---
***********************************************************

      READ TABLE LT_LIKP INTO LS_LIKP WITH KEY  VBELN = LS_VBRP-VGBEL.
      IF SY-SUBRC EQ 0.
        READ TABLE LT_VBPA INTO LS_VBPA WITH KEY VBELN  = LS_LIKP-VBELN.
        IF SY-SUBRC EQ 0.
          READ TABLE LT_KNA1_EXP INTO LS_KNA1_EXP WITH KEY KUNNR = LS_VBPA-KUNNR.
          IF SY-SUBRC EQ 0.
            LS_FINAL-EXPDTLS-PORT     = LS_KNA1_EXP-LOCCO.
          ENDIF.
        ENDIF.
      ENDIF.


      LS_FINAL-EXPDTLS-SHIPBNO  =  "ls_vbrk-xblnr.
      LS_FINAL-EXPDTLS-SHIPBDT  = "lv_date.
      LS_FINAL-EXPDTLS-REFCLM   = ''.
      LS_FINAL-EXPDTLS-EXPDUTY  = 0.

      IF LS_FINAL-EXPDTLS-SHIPBNO IS INITIAL.
        LS_FINAL-EXPDTLS-SHIPBNO  = LC_NULL.
      ENDIF.

      IF LS_FINAL-EXPDTLS-SHIPBDT IS INITIAL.
        LS_FINAL-EXPDTLS-SHIPBDT  = LC_NULL.
      ENDIF.

      IF LS_FINAL-EXPDTLS-REFCLM IS INITIAL.
        LS_FINAL-EXPDTLS-REFCLM = LC_NULL.
      ENDIF.

      LS_FINAL-EXPDTLS-FORCUR   = LS_VBRK-WAERK.

      IF LS_VBRK-LAND1 IS INITIAL.
        LS_FINAL-EXPDTLS-CNTCODE  = LC_NULL.
      ELSE.
        LS_FINAL-EXPDTLS-CNTCODE  = LS_VBRK-LAND1.
      ENDIF.

      IF LS_FINAL-EXPDTLS-PORT IS NOT INITIAL.
        LS_UPDATE-EXPDTLS = 'X'.
      ENDIF.

************************************************************************
      "--Addldocdtls--------------------------------------------
************************************************************************
      LS_ADDLDOCDTLS-URL  = LC_NULL.
      LS_ADDLDOCDTLS-DOCS = LC_NULL.
      LS_ADDLDOCDTLS-INFODTLS = LC_NULL.
      APPEND LS_ADDLDOCDTLS TO LT_ADDLDOCDTLS.
      LS_FINAL-ADDLDOCDTLS = LT_ADDLDOCDTLS.
      CLEAR : LS_ADDLDOCDTLS,LT_ADDLDOCDTLS.

************************************************************************
      "----Ewbdtls(E-way Bill)------------------------------------------
************************************************************************

      DATA: LS_EWAY_DATE  TYPE STRING.
      DATA: LV_TRANS_MODE TYPE STRING.

      READ TABLE LT_VBRP INTO LS_VBRP WITH KEY VBELN  = LS_VBRK-VBELN.
      IF SY-SUBRC EQ 0.

        READ TABLE LT_LIKP_EWAY INTO DATA(LS_LIKP_EWAY) WITH KEY  VBELN = LS_VBRP-VGBEL.
        IF SY-SUBRC EQ 0.
          LS_FINAL-EWBDTLS-VEHNO        =  LS_LIKP_EWAY-BOLNR.
        ENDIF.
        READ TABLE LT_VBPA_EWAY INTO LS_VBPA_EWAY WITH KEY VBELN = LS_VBRP-VGBEL.
        IF SY-SUBRC EQ 0.
          READ TABLE LT_LFA1_EWAY INTO LS_LFA1_EWAY WITH KEY LIFNR = LS_VBPA_EWAY-LIFNR.
          IF SY-SUBRC EQ 0.
            LS_FINAL-EWBDTLS-TRANSID      = LS_LFA1_EWAY-STCD3.
            LS_FINAL-EWBDTLS-TRANSNAME    = LS_LFA1_EWAY-NAME1.
          ENDIF.
        ENDIF.
      ENDIF.



      READ TABLE LT_ZEWAY_TAB INTO LS_ZEWAY_TAB WITH KEY VBELN = LS_VBRK-VBELN.
      IF SY-SUBRC EQ 0.

        IF LS_FINAL-EWBDTLS-VEHNO IS INITIAL.
          LS_FINAL-EWBDTLS-VEHNO        = LS_ZEWAY_TAB-VEHICAL_NO.
        ENDIF.

        IF LS_FINAL-EWBDTLS-TRANSID IS INITIAL.
          LS_FINAL-EWBDTLS-TRANSID      = LS_ZEWAY_TAB-TRANS_ID.
        ENDIF.

        LS_FINAL-EWBDTLS-DISTANCE     = LS_ZEWAY_TAB-DISTANCE.

        IF LS_ZEWAY_TAB-TRANS_DOC IS NOT INITIAL.
          LS_FINAL-EWBDTLS-TRANSDOCNO   = LS_ZEWAY_TAB-TRANS_DOC.
        ELSE.
          LS_FINAL-EWBDTLS-TRANSDOCNO   = 'null'.
        ENDIF.

        IF LS_FINAL-EWBDTLS-TRANSNAME IS INITIAL.
          LS_FINAL-EWBDTLS-TRANSNAME   = LS_ZEWAY_TAB-TRANS_NAME.
        ENDIF.

        IF LS_ZEWAY_TAB-DOC_DT IS NOT INITIAL.
          CONCATENATE LS_ZEWAY_TAB-DOC_DT+6(2) LS_ZEWAY_TAB-DOC_DT+4(2) LS_ZEWAY_TAB-DOC_DT+0(4) INTO LS_EWAY_DATE  SEPARATED BY '/'.
        ELSE.
          LS_EWAY_DATE = 'null'.
        ENDIF.

        LS_FINAL-EWBDTLS-TRANSDOCDT   = LS_EWAY_DATE.
        LS_FINAL-EWBDTLS-VEHTYPE      = LS_ZEWAY_TAB-VEHICAL_TYPE+0(1).

        CASE LS_ZEWAY_TAB-TRNS_MD.
          WHEN 'Road'.
            LV_TRANS_MODE = 1.
          WHEN 'Rail'.
            LV_TRANS_MODE = 2.
          WHEN 'Air'.
            LV_TRANS_MODE = 3.
          WHEN 'Ship'.
            LV_TRANS_MODE = 4.
          WHEN OTHERS.
        ENDCASE.
        LS_FINAL-EWBDTLS-TRANSMODE    = LV_TRANS_MODE.

      ENDIF.
      IF LV_UCOMM = '&IRNEW'.
        LS_UPDATE-EWBDTLS = 'X'.
      ENDIF.

      APPEND LS_FINAL TO LT_FINAL.
      CLEAR: LV_ASSVAL, LV_CGSTVAL, LV_SGSTVAL, LV_IGSTVAL,LV_TOTAL_VAL,LV_ROUNDOFF.

    ELSE.
*    MESSAGE 'Posting is not completed' TYPE 'E'.
      LS_RETMSG-ID = 'E'.
      LS_RETMSG-MESSAGE = 'Posting is not completed'.
      APPEND LS_RETMSG TO LT_RETMSG.
      LV_ERROR = 'X'.
      CLEAR LS_RETMSG.
      EXIT.
      LEAVE LIST-PROCESSING.
    ENDIF.
    CLEAR : LV_CURRY, LV_FY.
    CLEAR : LS_SEL_ADDR,LS_DIS_ADDR,LS_BUY_ADDR,LS_SHP_ADDR.
  ENDLOOP.

  CLEAR : LS_SEL_ADDR,LS_DIS_ADDR,LS_BUY_ADDR,LS_SHP_ADDR.

  IT_FINAL = LT_FINAL.



ENDFORM.
FORM PROCESS_DATA
    CHANGING LT_FINAL TYPE ANY TABLE.

  PERFORM REG_EINV CHANGING LT_FINAL.
ENDFORM.
FORM REG_EINV CHANGING LT_FINAL TYPE ANY TABLE.

  LOOP AT LT_VBRK INTO LS_VBRK.

  ENDLOOP.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  JSON_CONVERSION_ALL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_FILE_LOC  text
*      <--P_STATUS  text
*----------------------------------------------------------------------*
FORM JSON_CONVERSION_ALL  TABLES LT_JSONFILE STRUCTURE ZSTR_JSONFILE USING  FILE_LOC TYPE RLGRAP-FILENAME VBELN TYPE VBELN LV_MODE TYPE FLAG CHANGING
                                                                                                                          STATUS TYPE STRING.
  BREAK PRIMUS.

  DATA:  LV_JSON   TYPE STRING.
  DATA : O_WRITER_ITAB TYPE REF TO CL_SXML_STRING_WRITER.
  DATA: LV_RESULT TYPE STRING.
  DATA : O_TREX TYPE REF TO CL_TREX_JSON_SERIALIZER.
* CREATE OBJECT o_trex .

*************************************************************************************************
  TYPES : BEGIN OF TY_JSON,
            LINE(255) TYPE C,
            TABIX(03) TYPE N,
*           lv_text(65535) TYPE c,
          END OF TY_JSON.

  TYPES : BEGIN OF TY_JSON_OUTPUT,
            LINE(255) TYPE C,
          END OF TY_JSON_OUTPUT.


  TYPES : BEGIN OF TY_JSON_CNT,
            LINE(255) TYPE C,
            TABIX     TYPE I,
*           lv_text(65535) TYPE c,
          END OF TY_JSON_CNT.

  DATA :
    IT_JSON        TYPE TABLE OF ZEINV_JSON,
    IT_JSON_IN     TYPE TABLE OF ZEINV_JSON,
    LS_JSON        TYPE ZEINV_JSON,
    LT_JSON_OUTPUT TYPE STANDARD TABLE OF TY_JSON_OUTPUT,
    LS_JSON_OUTPUT TYPE TY_JSON_OUTPUT,
    P_LINES        TYPE I VALUE 0,
    COUNT          TYPE I VALUE 0.

  DATA : LT_JSON_CNT TYPE TABLE OF TY_JSON_CNT,
         LS_JSON_CNT TYPE TY_JSON_CNT.

  DATA : LV_SRNO TYPE STRING VALUE 'zslno'.
  DATA : LV_START TYPE STRING VALUE 'version'.
  DATA : CNT TYPE I VALUE 200.
  DATA : CNT_TAX TYPE I VALUE 0.
  DATA : LV_FLAG(01) TYPE C.
  DATA : LS_STR TYPE STRING.

  IF LV_ERROR = ' '.

    IF LV_MODE EQ 'M'.    "-----Check for multiple docs selected in cockpit if docs are more than 1 create single file for mass upload.

* serialize table lt_fINAL into JSON, skipping initial fields and converting ABAP field names into camelCase
      LV_JSON = /UI2/CL_JSON=>SERIALIZE( DATA = LT_FINAL COMPRESS = ABAP_TRUE PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE ).
*  cl_abap_browser=>show_html( title = 'ABAP (iTab) -> JSON: /ui2/cl_json=>serialize' html_string = cl_abap_codepage=>convert_from( lvc_html ) ).

      CLEAR LT_FINAL.

* deserialize JSON string json into internal table lt_final doing camelCase to ABAP like field name mapping
      /UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = LV_JSON PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE CHANGING DATA = LT_FINAL ).



      O_WRITER_ITAB = CL_SXML_STRING_WRITER=>CREATE( TYPE = IF_SXML=>CO_XT_JSON ).
      CALL TRANSFORMATION ID SOURCE VALUES = LT_FINAL RESULT XML O_WRITER_ITAB.

      CL_ABAP_CONV_IN_CE=>CREATE( )->CONVERT( EXPORTING
                                                INPUT = O_WRITER_ITAB->GET_OUTPUT( )
                                              IMPORTING
                                                DATA = LV_RESULT ).

* JSON -> ABAP (iTab)
      CLEAR LT_FINAL.

      CALL TRANSFORMATION ID SOURCE XML LV_RESULT RESULT VALUES = LT_FINAL.

* ABAP (iTab) -> JSON (trex)
      O_TREX = NEW CL_TREX_JSON_SERIALIZER( LT_FINAL ).
      O_TREX->SERIALIZE( ).


    ELSEIF LV_MODE NE 'M'.  " ------------------------------Single document Single file


* serialize table lt_fINAL into JSON, skipping initial fields and converting ABAP field names into camelCase
      LV_JSON = /UI2/CL_JSON=>SERIALIZE( DATA = LS_FINAL COMPRESS = ABAP_TRUE PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE ).
*  cl_abap_browser=>show_html( title = 'ABAP (iTab) -> JSON: /ui2/cl_json=>serialize' html_string = cl_abap_codepage=>convert_from( lvc_html ) ).

      CLEAR LS_FINAL.

* deserialize JSON string json into internal table lt_final doing camelCase to ABAP like field name mapping
      /UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = LV_JSON PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE CHANGING DATA = LS_FINAL ).



      O_WRITER_ITAB = CL_SXML_STRING_WRITER=>CREATE( TYPE = IF_SXML=>CO_XT_JSON ).
      CALL TRANSFORMATION ID SOURCE VALUES = LS_FINAL RESULT XML O_WRITER_ITAB.

      CL_ABAP_CONV_IN_CE=>CREATE( )->CONVERT( EXPORTING
                                                INPUT = O_WRITER_ITAB->GET_OUTPUT( )
                                              IMPORTING
                                                DATA = LV_RESULT ).

* JSON -> ABAP (iTab)
      CLEAR LS_FINAL.

      CALL TRANSFORMATION ID SOURCE XML LV_RESULT RESULT VALUES = LS_FINAL.

* ABAP (iTab) -> JSON (trex)
      O_TREX = NEW CL_TREX_JSON_SERIALIZER( LS_FINAL ).
      O_TREX->SERIALIZE( ).


    ENDIF.
*----------------------------------------------------------------------------------
    DATA(LV_TREX_JSON) = O_TREX->GET_DATA( ).
*--------------------------------------------------------------------------------------

    IF SY-SUBRC IS INITIAL.
*    SPLIT lv_trex_json AT ':' INTO TABLE lt_json_string .
      REPLACE ALL OCCURRENCES OF ',' IN LV_TREX_JSON WITH ',#'.
      SPLIT LV_TREX_JSON AT '#' INTO TABLE IT_JSON .
    ENDIF.

    LOOP AT IT_JSON INTO LS_JSON.
*      ls_json-tabix = sy-tabix.
      IF LS_JSON-LINE CS LV_START.
        CNT_TAX = 0.
        LS_JSON-TABIX = CNT_TAX.
        LV_FLAG = 'X'.
      ENDIF.
      IF LV_FLAG  = 'X' AND LS_JSON-LINE NS LV_SRNO.
        CNT_TAX = CNT_TAX + 1.
        LS_JSON-TABIX = CNT_TAX.
      ELSE.
        CLEAR LV_FLAG.
      ENDIF.

      MODIFY IT_JSON FROM LS_JSON TRANSPORTING TABIX.
      CLEAR LS_JSON.
*  clear <lfs_assign>.
    ENDLOOP.

    CLEAR :  SY-TABIX , LV_FLAG .

    LOOP AT IT_JSON INTO LS_JSON.
*      ls_json-tabix = sy-tabix.
      IF LS_JSON-LINE CS LV_SRNO.
        CNT = 200.
        LS_JSON-TABIX = CNT.
        LV_FLAG = 'X'.
      ENDIF.
      IF LV_FLAG  = 'X' AND LS_JSON-LINE NS LV_START.
        CNT = CNT + 1.
        LS_JSON-TABIX = CNT.
      ELSE.
        CLEAR LV_FLAG.
      ENDIF.

      MODIFY IT_JSON FROM LS_JSON TRANSPORTING TABIX.
*  clear <lfs_assign>.
    ENDLOOP.
    MOVE IT_JSON TO IT_JSON_IN.
    REFRESH IT_JSON.

    CALL FUNCTION 'ZEINV_SCHEMA_MAP'
      EXPORTING
        I_UPDATE = LS_UPDATE
      TABLES
        JSON_IN  = IT_JSON_IN
        JSON_OUT = IT_JSON.



    LOOP AT IT_JSON INTO LS_JSON.

      LS_JSON_OUTPUT-LINE = LS_JSON-LINE.
      CONCATENATE  LS_STR LS_JSON-LINE  INTO LS_STR.
      APPEND LS_JSON_OUTPUT TO LT_JSON_OUTPUT.

      COUNT = COUNT + 1.
      WRITE / LS_JSON-LINE.
      CLEAR :  LS_JSON , LS_JSON_OUTPUT , LS_UPDATE.
    ENDLOOP.

    IF LT_JSON_OUTPUT IS NOT INITIAL.
      LT_JSONFILE[] = LT_JSON_OUTPUT[].
      STATUS = 'Success!'.
    ELSE.
      STATUS = 'Error!'.
    ENDIF.

  ELSE.
    STATUS = 'Error!'.
  ENDIF.
  CLEAR : LS_FINAL.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  GET_DATA_CANCEL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_LT_RETMSG  text
*      -->P_VBELN  text
*      -->P_GJAHR  text
*----------------------------------------------------------------------*
FORM GET_DATA_CANCEL  TABLES   LT_RETMSG STRUCTURE BAPIRET2
                                 "Insert a correct name for <...>
                      USING    VBELN
                               GJAHR
                               LV_UCOMM TYPE SY-UCOMM.


  DATA LC_VBELN TYPE VBELN.
  LC_VBELN = VBELN.

  DATA : LS_ZEINV_CANCEL    TYPE ZEINV_RES.
  DATA : LS_ZEWAY_BILL      TYPE ZEWAY_BILL.
  DATA : LS_J_1IG_INVREFNUM TYPE J_1IG_INVREFNUM .

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT  = LC_VBELN
    IMPORTING
      OUTPUT = LC_VBELN.





  IF LV_UCOMM = '&CAN'.

    SELECT SINGLE * FROM ZEINV_RES INTO LS_ZEINV_CANCEL
    WHERE VBELN = LC_VBELN.
    IF SY-SUBRC IS INITIAL AND LS_ZEINV_CANCEL-ZZIRN_NO IS NOT INITIAL.
      LS_FINAL_CANCEL-IRN = LS_ZEINV_CANCEL-ZZIRN_NO.
      LS_FINAL_CANCEL-CNLRSN = LS_ZEINV_CANCEL-ZZCAN_RSN.
      LS_FINAL_CANCEL-CNLREM = LS_ZEINV_CANCEL-ZZCAN_REASON.
    ELSE.
      SELECT SINGLE * FROM J_1IG_INVREFNUM INTO LS_J_1IG_INVREFNUM
        WHERE DOCNO = LC_VBELN.
      IF SY-SUBRC IS INITIAL.
        SELECT SINGLE * FROM ZEINV_RES INTO LS_ZEINV_CANCEL
        WHERE VBELN = LC_VBELN.

        LS_FINAL_CANCEL-IRN = LS_J_1IG_INVREFNUM-IRN.
        LS_FINAL_CANCEL-CNLRSN = LS_ZEINV_CANCEL-ZZCAN_RSN.
        LS_FINAL_CANCEL-CNLREM = LS_ZEINV_CANCEL-ZZCAN_REASON.
      ENDIF.
    ENDIF.

  ELSEIF LV_UCOMM = '&CANEWAY'.
    SELECT SINGLE * FROM ZEINV_RES INTO LS_ZEINV_CANCEL
     WHERE VBELN = LC_VBELN.

    IF SY-SUBRC IS INITIAL.

      SELECT SINGLE * FROM ZEWAY_BILL INTO LS_ZEWAY_BILL WHERE
          VBELN = LC_VBELN.
      IF SY-SUBRC IS INITIAL.
        LS_FINAL_CANCEL_EWAY-EWBNO         = LS_ZEINV_CANCEL-ZZEWAYBILL_NO.
        LS_FINAL_CANCEL_EWAY-CANCELRSNCODE = LS_ZEWAY_BILL-REASONCODE.
        LS_FINAL_CANCEL_EWAY-CANCELRMRK    = LS_ZEWAY_BILL-REASON.
      ENDIF.
    ENDIF.
  ENDIF.
  CLEAR : LS_ZEINV_CANCEL,LS_ZEWAY_BILL.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  JSON_CONVERSION_CANCEL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_LT_JSONFILE  text
*      -->P_FILE_LOC  text
*      -->P_VBELN  text
*      <--P_STATUS  text
*----------------------------------------------------------------------*
FORM JSON_CONVERSION_CANCEL  TABLES   LT_JSONFILE STRUCTURE ZSTR_JSONFILE
                                        "Insert a correct name for <...>
                             USING    FILE_LOC
                                      VBELN
                                      LV_UCOMM TYPE SY-UCOMM
                             CHANGING STATUS.





  DATA: LV_JSON   TYPE STRING,
        LV_RESULT TYPE STRING,
        LS_STR    TYPE STRING.

  TYPES : BEGIN OF TY_JSON,
            LINE(255) TYPE C,
            TABIX(03) TYPE N,
*           lv_text(65535) TYPE c,
          END OF TY_JSON.

  TYPES : BEGIN OF TY_JSON_OUTPUT,
            LINE(255) TYPE C,
          END OF TY_JSON_OUTPUT.


  TYPES : BEGIN OF TY_JSON_CNT,
            LINE(255) TYPE C,
            TABIX     TYPE I,
*           lv_text(65535) TYPE c,
          END OF TY_JSON_CNT.

  DATA : IT_JSON        TYPE TABLE OF TY_JSON,
         LS_JSON        TYPE TY_JSON,
         LT_JSON_OUTPUT TYPE STANDARD TABLE OF TY_JSON_OUTPUT,
         LS_JSON_OUTPUT TYPE TY_JSON_OUTPUT,
         P_LINES        TYPE I VALUE 0,
         COUNT          TYPE I VALUE 0.

  DATA : LT_JSON_CNT TYPE TABLE OF TY_JSON_CNT,
         LS_JSON_CNT TYPE TY_JSON_CNT.



  IF LV_UCOMM = '&CAN'.

* serialize table lt_fINAL into JSON, skipping initial fields and converting ABAP field names into camelCase
    LV_JSON = /UI2/CL_JSON=>SERIALIZE( DATA = LS_FINAL_CANCEL COMPRESS = ABAP_TRUE PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE ).

    " Display JSON in ABAP
    CALL TRANSFORMATION SJSON2HTML SOURCE XML LV_JSON
                               RESULT XML DATA(LVC_HTML).
*  cl_abap_browser=>show_html( title = 'ABAP (iTab) -> JSON: /ui2/cl_json=>serialize' html_string = cl_abap_codepage=>convert_from( lvc_html ) ).

    CLEAR LT_FINAL.

* deserialize JSON string json into internal table lt_final doing camelCase to ABAP like field name mapping
    /UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = LV_JSON PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE CHANGING DATA = LS_FINAL_CANCEL ).



    DATA(O_WRITER_ITAB) = CL_SXML_STRING_WRITER=>CREATE( TYPE = IF_SXML=>CO_XT_JSON ).
    CALL TRANSFORMATION ID SOURCE VALUES = LS_FINAL_CANCEL RESULT XML O_WRITER_ITAB.

    CL_ABAP_CONV_IN_CE=>CREATE( )->CONVERT( EXPORTING
                                              INPUT = O_WRITER_ITAB->GET_OUTPUT( )
                                            IMPORTING
                                              DATA = LV_RESULT ).

* JSON -> ABAP (iTab)
    CLEAR LT_FINAL.

    CALL TRANSFORMATION ID SOURCE XML LV_RESULT RESULT VALUES = LS_FINAL_CANCEL.

* ABAP (iTab) -> JSON (trex)
    DATA(O_TREX) = NEW CL_TREX_JSON_SERIALIZER( LS_FINAL_CANCEL ).
    O_TREX->SERIALIZE( ).

    DATA(LV_TREX_JSON) = O_TREX->GET_DATA( ).
*--------------------------------------------------------------------------------------
    IF SY-SUBRC IS INITIAL.
*    SPLIT lv_trex_json AT ':' INTO TABLE lt_json_string .
      REPLACE ALL OCCURRENCES OF ',' IN LV_TREX_JSON WITH ',#'.
      SPLIT LV_TREX_JSON AT '#' INTO TABLE IT_JSON .
    ENDIF.


    LOOP AT IT_JSON ASSIGNING FIELD-SYMBOL(<LFS_JSON_MAIN>).
      CASE SY-TABIX.
        WHEN 1.
          REPLACE 'irn' IN <LFS_JSON_MAIN> WITH '"Irn"'.
        WHEN 2.
          REPLACE 'cnlrsn' IN <LFS_JSON_MAIN> WITH '"CnlRsn"'.
        WHEN 3.
          REPLACE 'cnlrem' IN <LFS_JSON_MAIN> WITH '"CnlRem"'.

        WHEN OTHERS.
      ENDCASE.

    ENDLOOP.


  ELSEIF LV_UCOMM = '&CANEWAY'.


* serialize table lt_fINAL into JSON, skipping initial fields and converting ABAP field names into camelCase
    LV_JSON = /UI2/CL_JSON=>SERIALIZE( DATA = LS_FINAL_CANCEL_EWAY COMPRESS = ABAP_TRUE PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE ).


    CLEAR LT_FINAL.

* deserialize JSON string json into internal table lt_final doing camelCase to ABAP like field name mapping
    /UI2/CL_JSON=>DESERIALIZE( EXPORTING JSON = LV_JSON PRETTY_NAME = /UI2/CL_JSON=>PRETTY_MODE-CAMEL_CASE CHANGING DATA = LS_FINAL_CANCEL_EWAY ).



    DATA(O_WRITER_ITAB_EWAY) = CL_SXML_STRING_WRITER=>CREATE( TYPE = IF_SXML=>CO_XT_JSON ).
    CALL TRANSFORMATION ID SOURCE VALUES = LS_FINAL_CANCEL_EWAY RESULT XML O_WRITER_ITAB_EWAY.

    CL_ABAP_CONV_IN_CE=>CREATE( )->CONVERT( EXPORTING
                                              INPUT = O_WRITER_ITAB_EWAY->GET_OUTPUT( )
                                            IMPORTING
                                              DATA = LV_RESULT ).

* JSON -> ABAP (iTab)
    CLEAR LT_FINAL.

    CALL TRANSFORMATION ID SOURCE XML LV_RESULT RESULT VALUES = LS_FINAL_CANCEL_EWAY.

* ABAP (iTab) -> JSON (trex)
    DATA(O_TREX_EWAY) = NEW CL_TREX_JSON_SERIALIZER( LS_FINAL_CANCEL_EWAY ).
    O_TREX_EWAY->SERIALIZE( ).

    DATA(LV_TREX_JSON_EWAY) = O_TREX_EWAY->GET_DATA( ).
*--------------------------------------------------------------------------------------

    IF SY-SUBRC IS INITIAL.
*    SPLIT lv_trex_json AT ':' INTO TABLE lt_json_string .
      REPLACE ALL OCCURRENCES OF ',' IN LV_TREX_JSON_EWAY WITH ',#'.
      SPLIT LV_TREX_JSON_EWAY AT '#' INTO TABLE IT_JSON .
    ENDIF.



    LOOP AT IT_JSON ASSIGNING FIELD-SYMBOL(<LFS_JSON_EWAY>).
      CASE SY-TABIX.
        WHEN 1.
          REPLACE 'ewbno' IN <LFS_JSON_EWAY> WITH '"ewbNo"'.
        WHEN 2.
          REPLACE 'cancelrsncode' IN <LFS_JSON_EWAY> WITH '"cancelRsnCode"'.
        WHEN 3.
          REPLACE 'cancelrmrk' IN <LFS_JSON_EWAY> WITH '"cancelRmrk"'.

        WHEN OTHERS.
      ENDCASE.

    ENDLOOP.

  ENDIF.




  LOOP AT IT_JSON INTO LS_JSON.

    LS_JSON_OUTPUT-LINE = LS_JSON-LINE.
    CONCATENATE  LS_STR LS_JSON-LINE  INTO LS_STR.
    APPEND LS_JSON_OUTPUT TO LT_JSON_OUTPUT.

    COUNT = COUNT + 1.
    WRITE / LS_JSON-LINE.
    CLEAR :  LS_JSON , LS_JSON_OUTPUT.
  ENDLOOP.

  IF LT_JSON_OUTPUT IS NOT INITIAL.
    LT_JSONFILE[] = LT_JSON_OUTPUT[].
    STATUS = 'Success!'.
  ELSE.
    STATUS = 'Error!'.
  ENDIF.

  CLEAR : LS_FINAL_CANCEL_EWAY, LS_FINAL_CANCEL.



ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  ES_REMOVE_SPECIAL_CHARACTER
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_I_TEXT  text
*      <--P_E_TEXT  text
*----------------------------------------------------------------------*
FORM ES_REMOVE_SPECIAL_CHARACTER  USING    P_I_TEXT
                                  CHANGING P_E_TEXT.
  CALL FUNCTION 'ES_REMOVE_SPECIAL_CHARACTER'
    EXPORTING
      TEXT1       = P_I_TEXT
    IMPORTING
      CORR_STRING = P_E_TEXT.

ENDFORM.
