****** Biren 28-02.2009
DATA I TYPE I.
SELECT SINGLE AWKEY
INTO L_AWKEY
FROM BKPF
WHERE BLART = 'SK'
AND BELNR = BKPFTAB-BELNR.
I = L_AWKEY+(10).
L_AWKEY = I.
CONDENSE L_AWKEY.

****** Biren

IF BKPFTAB-BSTAT = 'V'.
  GV_STATUS = 'Parked'.
ELSEIF BKPFTAB-BSTAT = 'Z'.
  GV_STATUS = 'Parked Document Deleted'.
ELSE.
  GV_STATUS = 'Posted'.
ENDIF.

SELECT SINGLE LTEXT FROM T003T INTO GV_DOC_TYPE_TEXT
WHERE SPRAS = SY-LANGU
AND   BLART = BKPFTAB-BLART.

CLEAR: WA_BSEGTAB,
L_ZTERM.

*Added on 06/08/2010
IF W_DOC_TYPE = 'BANK PAYMENT' OR W_DOC_TYPE = 'BANK RECEIPT'.
  READ TABLE BSEGTAB INTO WA_BSEGTAB WITH KEY BUZEI = '001'.
  IF SY-SUBRC = 0.
    L_ZUONR = WA_BSEGTAB-ZUONR.
  ENDIF.
ELSE.
  READ TABLE BSEGTAB INTO WA_BSEGTAB WITH KEY BUZEI = '002'.
  IF SY-SUBRC = 0.
    L_ZUONR = WA_BSEGTAB-ZUONR.
  ENDIF.
ENDIF.


* IF VENDORS
READ TABLE BSEGTAB INTO WA_BSEGTAB WITH KEY KOART = 'K'.                        .
IF SY-SUBRC = 0.
  L_ZTERM = WA_BSEGTAB-ZTERM.
*  l_zuonr = wa_bsegtab-zuonr.
  L_VEN_CUST = 'K'.
  SELECT SINGLE J_1ICSTNO J_1ILSTNO J_1IPANNO J_1ISERN
  FROM J_1IMOVEND
  INTO (L_CST, L_VAT, L_PAN, L_SRV)
  WHERE LIFNR = WA_BSEGTAB-LIFNR.
ENDIF.
* IF CUSTOMERS
READ TABLE BSEGTAB INTO WA_BSEGTAB WITH KEY KOART = 'D'.                        .
IF SY-SUBRC = 0.
  L_ZTERM = WA_BSEGTAB-ZTERM.
*  l_zuonr = wa_bsegtab-zuonr.
  L_VEN_CUST = 'D'.
  SELECT SINGLE J_1ICSTNO J_1ILSTNO J_1IPANNO J_1ISERN
  FROM J_1IMOCUST
  INTO (L_CST, L_VAT, L_PAN, L_SRV)
  WHERE KUNNR = WA_BSEGTAB-KUNNR.

ENDIF.

IF L_ZTERM IS NOT INITIAL.
  SELECT SINGLE VTEXT
  FROM TVZBT
  INTO L_VTEXT
  WHERE ZTERM = L_ZTERM
  AND SPRAS = 'EN'.
ENDIF.

IF W_DOC_TYPE = 'BANK PAYMENT' OR W_DOC_TYPE = 'BANK RECEIPT'.
  L_ASS = 'A'.
ELSE.
  L_ASS = ''.
ENDIF.
