*&---------------------------------------------------------------------*
*&  Include           ZGATE_OUT_SS
*&---------------------------------------------------------------------*
TABLES : VBRK , ZGATE_OUT.
DATA : ZV_DATE TYPE BUDAT.
*
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-001.
  PARAMETERS : R_CREATE RADIOBUTTON GROUP rb USER-COMMAND rb1 MODIF ID new DEFAULT 'X',
               R_DISPLY RADIOBUTTON GROUP rb MODIF ID dip.
  SELECT-OPTIONS : P_DATE FOR ZV_DATE MODIF ID dis.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK B5 WITH FRAME TITLE ABC .
PARAMETERS P_DOWN AS CHECKBOX.
PARAMETERS : P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/delval/temp'MODIF ID NEE.
            "'E:\delval\temp' MODIF ID NEE.
SELECTION-SCREEN END OF BLOCK B5.

SELECTION-SCREEN :BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-003.
SELECTION-SCREEN  COMMENT /1(60) TEXT-004.
SELECTION-SCREEN  COMMENT /1(70) TEXT-005.
SELECTION-SCREEN :END OF BLOCK b3.

TYPES : BEGIN OF TY_FINAL,
        ZV_DATE         TYPE  ZGATE_OUT-ZV_DATE,
        ZVEH_NUM        TYPE  ZGATE_OUT-ZVEH_NUM ,
        ZV_DRIVER_NAME  TYPE  ZGATE_OUT-ZV_DRIVER_NAME,
        ZTRANS_NAME     TYPE  ZGATE_OUT-ZTRANS_NAME,
        ZINVOICE_NO     TYPE  ZGATE_OUT-ZINVOICE_NO,
        ZCRETED_BY      TYPE  ZGATE_OUT-ZCRETED_BY,
        ZV_REMARK       TYPE  ZGATE_OUT-ZV_REMARK ,
        ZOUT_DATE       TYPE  ZGATE_OUT-ZOUT_DATE ,
        ZOUT_TIME       TYPE  ZGATE_OUT-ZOUT_TIME ,
        ZNUMBER_01      TYPE  ZGATE_OUT-ZNUMBER_01 ,
        zser_no         TYPE  ZGATE_OUT-zser_no ,
        zrefe_no        TYPE  ZGATE_OUT-zrefe_no ,
        ZFSTORAGE_LOC  TYPE  ZGATE_OUT-ZFSTORAGE_LOC,   " add by supriya on 08.07.2024
        ZTSTORAGE_LOC  TYPE  ZGATE_OUT-ZTSTORAGE_LOC,   " add by supriya on 08.07.2024

        END OF TY_FINAL.

  DATA : IT_FINAL TYPE TABLE OF TY_FINAL,
         WA_FINAL TYPE TY_FINAL.
