  PROCESS BEFORE OUTPUT.
    MODULE STATUS_0100.

    LOOP AT IT_DATA INTO WA_DATA WITH CONTROL TAB CURSOR
      TAB-CURRENT_LINE.
    ENDLOOP.

  PROCESS AFTER INPUT.

    CHAIN.
      FIELD ZGATE_OUT-ZTRANS_NAME MODULE ZTRANS_NAME.
    ENDCHAIN.

*    CHAIN.
*      FIELD ZGATE_OUT-ZINVOICE_NO MODULE ZINVOICE_NO.
*    ENDCHAIN.

    CHAIN.
      FIELD ZGATE_OUT-ZVEH_NUM   MODULE ZVEH_NUM.
    ENDCHAIN.

    LOOP AT IT_DATA .

    ENDLOOP.
    MODULE USER_COMMAND_0100.
