
TOTAL_DEBIT = 0.
TOTAL_CREDIT = 0.



IF WA_CUSTBAL-CLBAL LT 0.
  WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL * -1.
LV_DR_CR = 'Cr'.
ELSE.
  LV_DR_CR = 'Dr'.
ENDIF.


CONCATENATE WA_CUSTBAL-NAME1 WA_CUSTBAL-NAME2 INTO LV_ADDR1
SEPARATED BY  SPACE.
CONDENSE LV_ADDR1.

CONCATENATE WA_CUSTBAL-HOUSE_NUM1
 WA_CUSTBAL-STREET WA_CUSTBAL-Str_suppl1 INTO LV_ADDR2
 SEPARATED BY SPACE.
CONDENSE LV_ADDR2.

CONCATENATE WA_CUSTBAL-STR_SUPPL2 WA_CUSTBAL-STR_SUPPL3
INTO LV_ADDR3 SEPARATED BY SPACE.
CONDENSE LV_ADDR3.

CONCATENATE WA_CUSTBAL-LOCATION WA_CUSTBAL-ORT01 '-'
WA_CUSTBAL-PSTLZ INTO LV_ADDR4 SEPARATED BY SPACE.
CONDENSE LV_ADDR4.

CONCATENATE WA_CUSTBAL-BEZEI WA_CUSTBAL-LANDX INTO LV_ADDR5
SEPARATED BY SPACE.
CONDENSE LV_ADDR5.

