*BREAK-POINT.
CLEAR: GV_DEL_DT, GV_OFM_DATE, WA_FINAL-OFM_DATE.

SELECT SINGLE * FROM vbap INTO wa_vbap
  WHERE vbeln = wa_final-vbeln AND posnr = wa_final-posnr.

  WA_FINAL-OFM_DATE = WA_VBAP-OFM_DATE.

*CONCATENATE  WA_FINAL-DELDATE+6(2) WA_FINAL-DELDATE+4(2) WA_FINAL-DELDATE+0(4)
*                INTO GV_DEL_DT SEPARATED BY '-'.

*SELECT SINGLE OFM_DATE FROM VBAP INTO GV_OFM_DATE WHERE VBELN = WA_FINAL-VBELN.
*
*WA_FINAL-OFM_DATE = GV_OFM_DATE.

CONCATENATE  WA_FINAL-OFM_DATE+6(2) WA_FINAL-OFM_DATE+4(2) WA_FINAL-OFM_DATE+0(4)
                INTO WA_FINAL-OFM_DATE SEPARATED BY '-'.

CONCATENATE  GV_OFM_DATE+6(2) GV_OFM_DATE+4(2) GV_OFM_DATE+0(4)
                INTO GV_OFM_DATE SEPARATED BY '-'.











