
DATA AMNT TYPE MAXBT.

AMNT = CENVAT_DUTY.

CALL FUNCTION 'HR_IN_CHG_INR_WRDS'
EXPORTING
aMT_IN_NUM               = AMNT
IMPORTING
AMT_IN_WORDS             = TOTAL_AMOUNT_TEXT
EXCEPTIONS
DATA_TYPE_MISMATCH       = 1
OTHERS                   = 2
.
IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ELSE.
  CONDENSE TOTAL_AMOUNT_TEXT.
ENDIF.


" For Total Invoice-amount :
AMNT = TOTAL_INVOICE_AMOUNT.

CALL FUNCTION 'HR_IN_CHG_INR_WRDS'
EXPORTING
aMT_IN_NUM               = AMNT
IMPORTING
AMT_IN_WORDS             = TOTAL_INVOICE_AMOUNT_TEXT
EXCEPTIONS
DATA_TYPE_MISMATCH       = 1
OTHERS                   = 2
.
IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ELSE.
  CONDENSE TOTAL_INVOICE_AMOUNT_TEXT.
ENDIF.












