READ TABLE lt_afpo INTO wa_afpo INDEX 1.
READ TABLE IT_KONV INTO WA_KONV WITH KEY KSCHL = 'JOCM'.
IF SY-SUBRC = 0.
V_OCTROI1 = WA_KONV-KWERT.
ENDIF.

READ TABLE IT_KONV INTO WA_KONV WITH KEY KSCHL = 'FRA1'.
IF SY-SUBRC = 0.
V_KWERT = WA_KONV-KWERT.
ENDIF.
SELECT KNUMV FROM EKKO INTO TABLE IT_EKKO
  WHERE EBELN = gv_MSEG-EBELN.

OCT_AMT = V_OCTROI1.
TRNSPRT_AMT = V_KWERT.

CONDENSE : OCT_AMT , TRNSPRT_AMT.
