
*BREAK PRIMUS.
DATA : LV_UDATE  TYPE CDHDR-UDATE,
       LV_ZEIVR  TYPE CDPOS-VALUE_OLD,
       LV_ZEIVR1 TYPE CDPOS-VALUE_OLD,
       LV_CHANG  TYPE CDHDR-CHANGENR.
DATA : IT_CDPOS TYPE STANDARD TABLE OF TY_CDPOS,
       WA_CDPOS TYPE TY_CDPOS.
DATA : IT_CDPOS1 TYPE STANDARD TABLE OF TY_CDPOS,
       WA_CDPOS1 TYPE TY_CDPOS.
DATA : IT_CDHDR TYPE STANDARD TABLE OF TY_CDHDR,
       WA_CDHDR TYPE TY_CDHDR.
DATA : WA_MSEG TYPE T_MSEG,
       "LT_MSEG    TYPE STANDARD TABLE OF T_MSEG,
       LT_MAKT TYPE STANDARD TABLE OF T_MAKT.

DATA : LWA_MSEG    TYPE T_MSEG,
       LWA_MAKT    TYPE T_MAKT,
       LWA_GR_ITEM TYPE T_GR.

READ TABLE IT_DOCS INTO YPM_GR_STR INDEX 1.

SELECT ZEILE
       EBELN
       EBELP
       MATNR
       LSMNG
       LSMEH
       ERFMG
       ERFME
       BPMNG
       BPRME
       LIFNR
       BWART
       LGORT
       SHKZG
       INSMK
       AUFNR
       MAT_KDAUF
       INTO TABLE LT_MSEG FROM MSEG
       WHERE MBLNR = YPM_GR_STR-MBLNR
       AND   MJAHR = YPM_GR_STR-MJAHR
       AND BWART = '101'.

SELECT AUFNR
       KDAUF
       KDPOS
       FROM AFPO
       INTO TABLE LT_AFPO
       FOR ALL ENTRIES IN LT_MSEG
       WHERE AUFNR = LT_MSEG-AUFNR.

SORT LT_MSEG BY MATNR.
SELECT MATNR MAKTX FROM MAKT
INTO TABLE LT_MAKT
FOR ALL ENTRIES IN LT_MSEG
WHERE
MATNR  =  LT_MSEG-MATNR AND
SPRAS  =  SY-LANGU.

LOOP AT LT_MSEG INTO LWA_MSEG.
  IF SY-TABIX = 1.
    SELECT SINGLE * FROM LFA1 INTO GV_LFA1 WHERE
    LIFNR = LWA_MSEG-LIFNR.
    GV_MSEG-MBLNR = YPM_GR_STR-MBLNR.
    GV_MSEG-MJAHR = YPM_GR_STR-MJAHR.
* break primus.
    SELECT SINGLE * FROM VBAK INTO GV_VBAK WHERE
      VBELN = LWA_MSEG-MAT_KDAUF.

* BREAK PRIMUS.
    SELECT SINGLE * FROM MKPF INTO GV_MKPF WHERE
    MBLNR = YPM_GR_STR-MBLNR AND
    MJAHR = YPM_GR_STR-MJAHR.

    SELECT  SINGLE *  FROM MSEG INTO GV_MSEG
      WHERE  MBLNR = YPM_GR_STR-MBLNR AND
              MJAHR = YPM_GR_STR-MJAHR
              and ZEILE = '0001'.


      SELECT SINGLE * FROM J_1IGRXREF INTO GV_1IGRXREF WHERE
      MBLNR = YPM_GR_STR-MBLNR AND
      MJAHR = YPM_GR_STR-MJAHR.
        SELECT SINGLE BEDAT WAERS  FROM EKKO INTO (GV_PODATE,GV_WAERS ) WHERE
        EBELN = GV_MSEG-EBELN.
        ENDIF.

        LWA_GR_ITEM-ZEILE  = LWA_MSEG-ZEILE.
        LWA_GR_ITEM-MATNR  = LWA_MSEG-MATNR.
        READ TABLE LT_MAKT INTO LWA_MAKT
        WITH KEY
        MATNR  =   LWA_MSEG-MATNR.
        IF SY-SUBRC = 0.
          LWA_GR_ITEM-MAKTX  = LWA_MAKT-MAKTX.
        ENDIF.
***<<<<PO QUANTITY
        SELECT SINGLE * FROM EKPO INTO WA_EKPO
        WHERE EBELN = LWA_MSEG-EBELN AND
        EBELP = LWA_MSEG-EBELP.

          CLEAR  LV_TXT1.

          IF WA_EKPO-NETPR <> 0.
            LV_TXT1 = 'BILLABLE'.
          ELSE.
            LV_TXT1 = 'NON BILLABLE'  .
          ENDIF.

          SELECT SINGLE * FROM EKKO INTO WA_EKKO
            WHERE EBELN = LWA_MSEG-EBELN.

            SELECT KSCHL KAWRT KWERT FROM KONV INTO CORRESPONDING FIELDS OF TABLE IT_KONV
              WHERE KNUMV = WA_EKKO-KNUMV
              AND   ( KSCHL = 'FRA1' OR
                      KSCHL = 'FRB1' OR
                      KSCHL = 'FRC1' OR
                      KSCHL = 'FRA2' OR
                      KSCHL = 'FRB2' OR
                      KSCHL = 'FRC2'  OR
                      KSCHL = 'JOCM' ).

******************************************************
              SELECT MBLNR LMENGE04 FROM QALS
                INTO CORRESPONDING FIELDS OF TABLE IT_QALS
                WHERE MBLNR = YPM_GR_STR-MBLNR.

                LWA_GR_ITEM-MENGE_PO   = WA_EKPO-MENGE.
                LWA_GR_ITEM-MEINS_PO   = LWA_MSEG-BPRME.

                LWA_GR_ITEM-MENGE_CH   = LWA_MSEG-LSMNG.
                LWA_GR_ITEM-MEINS_CH   = LWA_MSEG-LSMEH.

                LWA_GR_ITEM-MENGE_GR   = LWA_MSEG-ERFMG.
                LWA_GR_ITEM-MEINS_GR   = LWA_MSEG-ERFME.

                LWA_GR_ITEM-MENGE_DF   = LWA_GR_ITEM-MENGE_CH - LWA_GR_ITEM-MENGE_GR.

                CLEAR  LV_TXT.
                CASE GV_MSEG-INSMK.
                  WHEN 'X'.
                    LV_TXT = 'YES'.
                  WHEN OTHERS.
                    LV_TXT = 'NO'.
                ENDCASE.
**************AVINASH BHAGAT
*  select SINGLE UDATE from cdhdr INTO LV_UDATE WHERE OBJECTID = lwa_mseg-EBELN.
*  SELECT OBJECTID CHANGENR FROM CDPOS INTO TABLE IT_CDPOS WHERE OBJECTID = lwa_mseg-MATNR
*AND TABNAME = 'MARA' AND FNAME = 'ZEIVR'.
*    IF IT_CDPOS IS NOT INITIAL.
*    SELECT OBJECTID CHANGENR FROM cdhdr INTO TABLE IT_CDHDR FOR ALL ENTRIES IN IT_CDPOS  WHERE OBJECTID = lwa_mseg-MATNR
*      AND UDATE GE LV_UDATE AND CHANGENR = IT_CDPOS-CHANGENR .
*      SORT IT_CDHDR  ASCENDING BY CHANGENR.
*      READ TABLE IT_CDHDR INTO WA_CDHDR INDEX 1.
*      LV_CHANG = WA_CDHDR-CHANGENR.
*      ENDIF.
*      SELECT SINGLE VALUE_OLD FROM CDPOS INTO LV_zeivr WHERE OBJECTID = lwa_mseg-MATNR
*        AND TABNAME = 'MARA' AND FNAME = 'ZEIVR' AND CHANGENR = LV_CHANG.
*        IF LV_zeivr IS NOT INITIAL.
*          lv_zeivr1 =  LV_zeivr.
*          ELSE.
*            SELECT SINGLE zeivr FROM MARA INTO lv_zeivr1 WHERE MATNR = lwa_mseg-MATNR.
*            ENDIF.
*
*************  END AVINASH BHAGAT
                APPEND LWA_GR_ITEM TO GT_GR_ITEM.
                CLEAR : LWA_GR_ITEM.

              ENDLOOP.
              SELECT MATNR
                     WERKS
                     LGORT
                     LGPBE
                FROM MARD
                INTO TABLE GT_MARD
                FOR ALL ENTRIES IN LT_MSEG
                WHERE MATNR = LT_MSEG-MATNR
*  AND   werks = lt_mseg-werks
                AND   LGORT = LT_MSEG-LGORT.


                DATA : ADDRNUMBER TYPE ADRC-ADDRNUMBER.
*>>> COMPANY CODE ADDRESS
                SELECT SINGLE ADRNR FROM T001
                INTO ADDRNUMBER
                WHERE BUKRS = GV_MSEG-BUKRS.

                  SELECT SINGLE NAME1 NAME2 CITY1 NAME_CO STR_SUPPL1
                  STR_SUPPL2 STR_SUPPL3 STREET BEZEI LANDX POST_CODE1
                  TEL_NUMBER TEL_EXTENS FAX_NUMBER FAX_EXTENS
                  FROM ADRC AS A INNER JOIN T005T AS B
                  ON A~COUNTRY = B~LAND1 INNER JOIN T005U AS C
                  ON A~COUNTRY = C~LAND1 AND A~REGION = C~BLAND
                  INTO CORRESPONDING FIELDS OF WA_COMPADRC
                  WHERE ADDRNUMBER = ADDRNUMBER AND B~SPRAS = 'E'
                  AND C~SPRAS = 'E'.


                    SELECT MBLNR MJAHR VGART FROM MKPF
                      INTO TABLE GT_MKPF
                      FOR ALL ENTRIES IN IT_DOCS
                      WHERE MBLNR = IT_DOCS-MBLNR
                      AND   MJAHR = IT_DOCS-MJAHR.


                      LOOP AT LT_MSEG INTO WA_MSEG1.

                        SELECT EBELN PSTYP FROM EKPO
                          INTO TABLE GT_EKPO
                          WHERE EBELN = WA_MSEG1-EBELN.

                        ENDLOOP.



**SELECT SINGLE *  FROM MARA INTO WA_MARA
**       WHERE MATNR = WA_GR_ITEM-MATNR."LWA_MSEG-MATNR.
