
DATA : T_LIFNR TYPE LIFNR.

SELECT SINGLE KNUMV FROM EKKO INTO WA_EKKO
  WHERE EBELN = GV_MSEG-EBELN.

SELECT SINGLE LIFNR FROM prcd_elements INTO T_LIFNR
  WHERE KNUMV = WA_EKKO-KNUMV.

SELECT SINGLE NAME1 INTO GV_LFA1-NAME1
  FROM LFA1 WHERE LIFNR = T_LIFNR.
