*&---------------------------------------------------------------------*
*&  Include           ZMM_REQUSITION_DELETE_TOP
*&---------------------------------------------------------------------*

 " TYPE-POOLS DELCARATION
 TYPE-POOLS: SLIS.

 " TYPE DECLARATION
 TYPES:
 " FOR T_EBAN "
 BEGIN OF T_EBAN,
   BANFN TYPE BANFN, " Purchase Req. No
   BNFPO TYPE BNFPO, " Item No of Purchase Req.
   BSMNG TYPE BSMNG, " Qnty Ordered Against PR
   PSTYP TYPE PSTYP, " Item Category in Purchasing Doc
   END OF T_EBAN,

 " FOR T_EBAN1 "
 BEGIN OF T_EBAN1,
   WERKS TYPE EWERK, " Plant
   MATNR TYPE MATNR, " Material No
 END OF T_EBAN1,


 " FOR TABLE OUTPUT "
BEGIN OF T_OUTPUT,
  BANFN TYPE BANFN, " Purchase Req. No
  BNFPO TYPE BNFPO, " Item No of Purchase Req
  NOTE  TYPE C LENGTH 15, " Success or Failure Note
  MESSAGE TYPE STRING, " Message Passed in Return
  END OF T_OUTPUT.



 " INTERNAL TABLE AND WORK AREA DECLARATION "
 DATA:
    " FOR T_EBAN "
    I_EBAN TYPE STANDARD TABLE OF T_EBAN,
    W_EBAN TYPE T_EBAN,

    " FOR EBAN "
    I_EBAN1 TYPE STANDARD TABLE OF T_EBAN1,
    W_EBAN1 TYPE T_EBAN1,

    " FOR MDPS "
    I_MDPS TYPE TABLE OF MDPS,
    W_MDPS TYPE MDPS,

    " FOR T_OUTPUT "
    I_OUTPUT TYPE STANDARD TABLE OF T_OUTPUT,
    W_OUTPUT TYPE T_OUTPUT,

    " FOR BAPIEBAND "
    I_BAPIEBAND TYPE STANDARD TABLE OF BAPIEBAND,
    W_BAPIEBAND TYPE BAPIEBAND,

    " FOR BAPIRET2
    I_RETURN TYPE TABLE OF  BAPIRET2,
    W_RETURN TYPE BAPIRET2,

    " RETURN1
    RETURN1 TYPE BAPIRET2,

    " FOR PRITEM AND PRITEMX
    I_PRITEM TYPE TABLE OF BAPIMEREQITEMIMP,
    W_PRITEM TYPE BAPIMEREQITEMIMP,

    I_PRITEMX TYPE TABLE OF BAPIMEREQITEMX,
    W_PRITEMX TYPE BAPIMEREQITEMX.


 " DATA DECALRATION FOR ALV SCREEN "
 DATA:
       " FOR FIELDCAT "
       I_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
       W_FIELDCAT TYPE SLIS_FIELDCAT_ALV,

       " FOR LAYOUT "
       LAYOUT TYPE SLIS_LAYOUT_ALV.
