CLEAR : V_TEXT, WA_CONDITION.
READ TABLE IT_CONDITIONS INTO WA_CONDITION WITH KEY SQNO = counter.
IF SY-SUBRC <> 0.
  V_TEXT = '0.00'.
else.
  TOTAL_AMOUNT = TOTAL_AMOUNT + WA_CONDITION-KWERT.
  V_TEXT = WA_CONDITION-KWERT.
ENDIF.

"CONCATENATE v_text '-' WA_CONDITION-descr INTO v_text.
"CONCATENATE v_text '-' counter INTO v_text.
CONDENSE V_TEXT.

counter = counter + 1.




