DATA lv_date TYPE mjahr.
data: v_docno type J_1IDOCNO.

data : LIPS_VBELN TYPE VBELN_VL,
       OBJNAME    TYPE TDOBNAME,
       IT_KONV TYPE TY_TAB_ITEM_KONV,
       WA_KONV TYPE KOMV
*       TMP_TAB TYPE TABLE OF CHAR4,
*       STR TYPE STRING VALUE '_TOT ZPFL _XBD _ECS _HCS _SBT JVRD JVCS _TCS ZINR FRA1 _GRT'.
.
*SELECT SINGLE VBELN
*  FROM VBRP
*  INTO VBRP_VBELN
*  WHERE VGBEL = LIPS_VBELN.

"VBRP_VBELN = I_VBELN.

*SELECT SINGLE KNUMV
*              INCO2 AS TRNSPRTR
*              FKART
*  FROM VBRK
*  INTO CORRESPONDING FIELDS OF WA_HDR
*  WHERE VBELN = I_VBELN.

SELECT SINGLE
  TRNTYP
  DOCYR
  DOCNO
  BUKRS
  WERKS
  EXNUM
  EXDAT
*  "EXYEAR
  LIFNR
  REMTIME
  CPUTM
  EXCUR
*  KUNAG
*  KUNWE
  EXBED
  ECS
  EXADDTAX1
  RDOC AS VBELN
  FROM J_1IEXCHDR
  INTO CORRESPONDING FIELDS OF WA_HDR
  WHERE RDOC = I_VBELN
  "  AND status EQ 'C'
.
** Fetch Transporter info
*SELECT SINGLE VGBEL
*  FROM VBRP
*  INTO WA_HDR-VBELN
*  WHERE VBELN = I_VBELN.

*SELECT SINGLE
*  INCO2
*  INTO WA_HDR-TRNSPRTR
*  FROM VBKD
*  WHERE VBELN = WA_HDR-VBELN.

CLEAR OBJNAME.

OBJNAME = WA_HDR-VBELN.

** Fetch Supplier details
*PERFORM GET_TEXT USING OBJNAME 'VBBK' 'Z001' 'E' CHANGING WA_HDR-SUPPLIER.
*CONDENSE WA_HDR-SUPPLIER.
*
** Ftech info for Mode Of Transport
*PERFORM GET_TEXT USING OBJNAME 'VBBK' 'Z013' 'E' CHANGING WA_HDR-TRNSPRT_MODE.
*CONDENSE WA_HDR-TRNSPRT_MODE.
*
** Get name of Transporter
*PERFORM GET_TEXT USING OBJNAME 'VBBK' 'Z002' 'E' CHANGING WA_HDR-TRNSPRTR.
*CONDENSE WA_HDR-TRNSPRTR.
*
** Get name of L.R.No.
*PERFORM GET_TEXT USING OBJNAME 'VBBK' 'Z003' 'E' CHANGING WA_HDR-L_R_NO.
*CONDENSE WA_HDR-L_R_NO.
*
** Get Vehicle No.
*PERFORM GET_TEXT USING OBJNAME 'VBBK' 'Z004' 'E' CHANGING WA_HDR-VHICL.
*CONDENSE WA_HDR-VHICL.
*
** Get Freight.
*PERFORM GET_TEXT USING OBJNAME 'VBBK' 'Z004' 'E' CHANGING WA_HDR-FREIGHT.
*CONDENSE WA_HDR-FREIGHT.
*
** Get Transpor Date
*PERFORM GET_TEXT USING OBJNAME 'VBBK' 'Z012' 'E' CHANGING WA_HDR-TRNSPRT_DT.
*CONDENSE WA_HDR-TRNSPRT_DT.


*IF sy-datum+4(2) BETWEEN  '04' AND '12' .  "??????????????????
*  lv_date = sy-datum(4).
*ELSE.
*  lv_date = sy-datum(4) - 1.
*ENDIF.
*
*select single docno
*  into v_docno
*  from J_1IEXCHDR
*  where docyr = lv_date AND
*  trntyp = 'DLFC' AND
*  WERKS  = wa_hdr-werks and
*  RDOC = I_VBELN AND
*  status EQ 'C'.
*
*SELECT DOCNO
*  exbas INTO
*  table t_j_1iexcdtl
*  FROM j_1iexcdtl
**      for all entries in t_J_1IEXCHDR
*  WHERE TRNTYP  = 'DLFC' AND
*  docyr = lv_date AND
*  DOCNO <= v_docno.
*
*LOOP AT t_j_1iexcdtl into wa_j_1iexcdtl.
*  EXBAS_TOTAL = EXBAS_TOTAL + wa_j_1iexcdtl-exbas.
*ENDLOOP.

SELECT SINGLE BUTXT
  FROM T001
  INTO CORRESPONDING FIELDS OF WA_HDR
  WHERE BUKRS = WA_HDR-BUKRS.

SELECT SINGLE NAME1
    ORT01
    ADRNR
  FROM T001W
  INTO CORRESPONDING FIELDS OF WA_HDR
  WHERE WERKS = WA_HDR-WERKS.

SELECT SINGLE *
  FROM adrc
  INTO wa_adrc
  WHERE addrnumber = WA_HDR-ADRNR.

SELECT SINGLE SMTP_ADDR
  INTO WA_HDR-EMAIL
  FROM ADR6
  WHERE ADDRNUMBER = WA_HDR-ADRNR.

SELECT SINGLE URI_ADDR
  INTO WA_HDR-URL
  FROM ADR12
  WHERE ADDRNUMBER = WA_HDR-ADRNR.

SELECT SINGLE J_1IEXRN
    J_1IEXRG
    J_1IEXDI
    J_1IEXCO
    J_1ISERN
    J_1ICSTNO
    J_1ILSTNO
  FROM J_1IMOCOMP
  INTO CORRESPONDING FIELDS OF WA_HDR
  WHERE WERKS = WA_HDR-WERKS.

*********************************************************************
*SELECT SINGLE ADRNR
*FROM KNA1
*INTO WA_HDR-KUNAG_ADRNR
*WHERE KUNNR = WA_HDR-KUNAG.

** Fetch Buyer(Sold-To-Party)-Details
*SELECT SINGLE
*  J_1IEXCD
*  J_1ICSTNO
*  J_1ILSTNO
*FROM J_1IMOCUST
*INTO (wa_hdr-KUNAG_J_1IEXCD, wa_hdr-KUNAG_J_1ICSTNO, wa_hdr-KUNAG_J_1ILSTNO)
*WHERE KUNNR = WA_HDR-KUNAG.
*
*SELECT SINGLE ORT01 ADRNR
*FROM KNA1
*INTO (WA_HDR-KUNWE_ORT01, WA_HDR-KUNWE_ADRNR)
*WHERE KUNNR = WA_HDR-KUNWE.
*********************************************************************

SELECT SINGLE ADRNR
FROM LFA1
INTO WA_HDR-LIFNR_ADRNR
WHERE LIFNR = WA_HDR-LIFNR.

SELECT SINGLE J_1IEXCD
              J_1ICSTNO
              J_1ILSTNO
  FROM J_1IMOVEND
  INTO (wa_hdr-LIFNR_J_1IEXCD, wa_hdr-LIFNR_J_1ICSTNO, wa_hdr-LIFNR_J_1ILSTNO).

* Fetch list intems' details
*SELECT
*  ZEILE
*  SHIPFROM
*  RCWRK
*  MATNR
*  MENGE
*  MEINS
*  RGPLASER
*" MRK_PKG
*" NOS_ON_PKG
*" BEDRATE
*" EXBED
*" ECS
*" ECSRATE
*" EXADDRATE1
*" EXADDTAX1
**  added by marmik shah - 04.02.2011
*  ritem2
**  done
*FROM J_1IEXCDTL
*INTO CORRESPONDING FIELDS OF TABLE IT_ITEMS
*WHERE TRNTYP  = wa_hdr-TRNTYP
*AND DOCYR   = wa_hdr-DOCYR
*AND DOCNO   = wa_hdr-DOCNO.


" Set purchase order parameters
SELECT SINGLE EBELN
  FROM MSEG
  INTO WA_HDR-EBELN         " Purchasing Document Number
  WHERE MBLNR = I_VBELN.

SELECT SINGLE BEDAT KNUMV
  FROM EKKO
  INTO (WA_HDR-BEDAT, WA_HDR-KNUMV)        " Purchasing Document Date
  WHERE EBELN = WA_HDR-EBELN.

SELECT SINGLE XBLNR
  FROM MKPF
  INTO WA_HDR-CHALLAN                     " Challan Number
  WHERE MBLNR EQ I_VBELN.

*SELECT SINGLE KNUMV
*  FROM EKPO
*  INTO WA_HDR-KNUMV         " KNUMV
*  WHERE EBELN = WA_HDR-EBELN.

SELECT ZEILE
       MATNR
       MENGE
       MEINS
       "EBELN
       EBELP
  FROM MSEG
  INTO CORRESPONDING FIELDS OF TABLE IT_ITEMS
  WHERE MBLNR = I_VBELN.

SORT : IT_ITEMS BY ZEILE.
REFRESH : IT_KONV.
CLEAR TOTAL_AMOUNT.
*sort it_items by MATKL.
LOOP AT IT_ITEMS INTO WA_ITEM.

 SELECT SINGLE MAKTX
   FROM MAKT
   INTO WA_ITEM-MAKTX
   WHERE MATNR = WA_ITEM-MATNR AND SPRAS = 'E'.

 SELECT SINGLE NETPR
   FROM EKPO
   INTO WA_ITEM-NETPR
   WHERE EBELN = WA_HDR-EBELN AND EBELP = WA_ITEM-EBELP.

 WA_ITEM-NETWR = WA_ITEM-NETPR * WA_ITEM-MENGE.
 TOTAL_AMOUNT = TOTAL_AMOUNT + WA_ITEM-NETWR.

 PERFORM CALCULATE_ITEM_TAX TABLES IT_KONV USING WA_HDR-EBELN WA_ITEM-EBELP
                                                 I_VBELN .

**...ZPRO
*CLEAR WA_ITEM_KONV.
*READ TABLE IT_ITEMS_KONV INTO WA_ITEM_KONV WITH KEY KPOSN = WA_ITEM-RITEM2 " WA_ITEM-ZEILE
*KSCHL = 'ZPR0'.
*IF SY-SUBRC = 0.
*WA_ITEM-KBETR = WA_ITEM_KONV-KBETR.
*WA_ITEM-KWERT = WA_ITEM_KONV-KWERT.
*ENDIF.
*
*DELETE TABLE IT_ITEMS_KONV FROM WA_ITEM_KONV.
*
*READ TABLE IT_VBRP  INTO WA_VBRP WITH KEY MATNR = WA_ITEM-MATNR.
*
*WA_ITEM-MATKL       = WA_VBRP-MATKL.
**  WA_ITEM-NTGEW       = WA_VBRP-NTGEW.
*WA_ITEM-BRGEW       = WA_VBRP-BRGEW.
*WA_ITEM-GEWEI       = WA_VBRP-GEWEI.
*
*WA_ITEM-MAKTX       = WA_VBRP-ARKTX.
MODIFY IT_ITEMS FROM WA_ITEM.

ENDLOOP.

* Calculations related with taxes and discounts applicable.
REFRESH IT_CONDITIONS.
CLEAR : TOTAL_INVOICE_AMOUNT.

CLEAR WA_CONDITION.
WA_CONDITION-KSCHL = '_TOT'.
WA_CONDITION-KWERT = TOTAL_AMOUNT.
PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.

SORT IT_KONV BY KSCHL.
CLEAR : WA_CONDITION, WA_KONV.
LOOP AT IT_KONV INTO WA_KONV WHERE KSCHL = 'JVCS' OR KSCHL = 'JVRD'.
  IF WA_CONDITION-KSCHL <> WA_KONV-KSCHL.
    IF NOT WA_CONDITION-KSCHL IS INITIAL.
      PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.
      CLEAR WA_CONDITION.
    ENDIF.
    WA_CONDITION-KSCHL = WA_KONV-KSCHL.
    WA_CONDITION-Kbetr = WA_KONV-Kbetr.
  ENDIF.
  WA_CONDITION-KWERT = WA_CONDITION-KWERT + WA_KONV-KWERT.
  CLEAR WA_KONV.
ENDLOOP.
IF NOT WA_CONDITION-KSCHL IS INITIAL.
  PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.
  CLEAR WA_CONDITION.
ENDIF.

CLEAR WA_CONDITION.
WA_CONDITION-KSCHL = '_ECS'.
WA_CONDITION-KWERT = WA_HDR-ECS.
PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.

CLEAR WA_CONDITION.
WA_CONDITION-KSCHL = '_HCS'.
WA_CONDITION-KWERT = WA_HDR-EXADDTAX1.
PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.

CLEAR WA_CONDITION.
WA_CONDITION-KSCHL = '_XBD'.
WA_CONDITION-KWERT = WA_HDR-EXBED.
PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.

CENVAT_DUTY = WA_HDR-EXBED + WA_HDR-ECS + WA_HDR-EXADDTAX1.

SELECT KPOSN
      KSCHL
      KBETR
      WAERS
      KWERT
  FROM KONV "J_1IKONV
  INTO CORRESPONDING FIELDS OF TABLE IT_ITEMS_KONV
  WHERE KNUMV = WA_HDR-KNUMV
        AND KSCHL IN ('ZPFL', 'ZPC1', 'ZINR', 'FRA1', 'FRB1', 'FRC1').

  "..............................................................
  CLEAR WA_ITEM_KONV.
  WA_ITEM_KONV-KSCHL ='ZPFL'.
  MODIFY IT_ITEMS_KONV FROM WA_ITEM_KONV TRANSPORTING KSCHL WHERE KSCHL = 'ZPCI'.

  CLEAR WA_ITEM_KONV.
  WA_ITEM_KONV-KSCHL ='FRA1'.
  MODIFY IT_ITEMS_KONV FROM WA_ITEM_KONV TRANSPORTING KSCHL WHERE KSCHL = 'FRB1'
                                                                OR KSCHL = 'FRC1'.

  "..............................................................

*IF WA_HDR-FKART = 'ZFF2'.
  CLEAR : WA_CONDITION,
          WA_ITEM_KONV.
  SORT IT_ITEMS_KONV BY KSCHL.

  LOOP AT IT_ITEMS_KONV INTO WA_ITEM_KONV WHERE KPOSN IS NOT INITIAL.
    IF WA_CONDITION-KSCHL <> WA_ITEM_KONV-KSCHL.
      IF NOT WA_CONDITION-KSCHL IS INITIAL.
        PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.
        CLEAR WA_CONDITION.
      ENDIF.
      WA_CONDITION-KSCHL = WA_ITEM_KONV-KSCHL.
    ENDIF.

*    IF WA_CONDITION IS INITIAL.
*      WA_CONDITION-KSCHL = WA_ITEM_KONV-KSCHL.
*      WA_CONDITION-KBETR = WA_ITEM_KONV-KBETR.
*
*      IF WA_ITEM_KONV-WAERS IS INITIAL.
*        WA_CONDITION-WAERS = '%'.
*        WA_CONDITION-KBETR = WA_CONDITION-KBETR / 10.
*      ELSE.
*        WA_CONDITION-WAERS = WA_ITEM_KONV-WAERS.
*      ENDIF.
*    ENDIF.
    WA_CONDITION-KWERT = WA_CONDITION-KWERT + WA_ITEM_KONV-KWERT.
  ENDLOOP.
  IF NOT WA_CONDITION IS INITIAL.
    PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.
 "   TOTAL_INVOICE_AMOUNT = TOTAL_INVOICE_AMOUNT + WA_CONDITION-KWERT.
    CLEAR WA_CONDITION.
  ENDIF.

  CLEAR WA_CONDITION.
  WA_CONDITION-KSCHL = '_GRT'.
  WA_CONDITION-KWERT = TOTAL_INVOICE_AMOUNT.
  "CLEAR TOTAL_INVOICE_AMOUNT.
  PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.

* for Sub-Total
  CLEAR TOTAL_AMOUNT.
*******  SORT IT_CONDITIONS BY SQNO.
*******  LOOP AT IT_CONDITIONS INTO WA_CONDITION.
*******    TOTAL_AMOUNT = TOTAL_AMOUNT + WA_CONDITION-KWERT.
*******    IF WA_CONDITION-SQNO = 5.
*******      CLEAR WA_CONDITION.
*******      WA_CONDITION-KSCHL = '_SBT'.
*******      WA_CONDITION-KWERT = TOTAL_AMOUNT.
*******      "CLEAR TOTAL_INVOICE_AMOUNT.
*******      PERFORM APPEND_PRICING TABLES IT_CONDITIONS USING WA_CONDITION CHANGING TOTAL_INVOICE_AMOUNT.
*******      EXIT.
*******    ENDIF.
*******  ENDLOOP.
*******  SORT IT_CONDITIONS BY SQNO.
*******  CLEAR TOTAL_AMOUNT.
  " To fill in 0-values for the rest other conditions
*  DO 12 TIMES.
*    READ TABLE IT_CONDITIONS INTO WA_CONDITION WITH KEY SQNO = SY-INDEX.
*    IF SY-SUBRC <> 0.
*      CLEAR WA_CONDITION.
*      WA_CONDITION-SQNO = SY-INDEX.
*      WA_CONDITION-KSCHL = '-'.
*      WA_CONDITION-KWERT = '0.00'.
*      APPEND WA_CONDITION TO IT_CONDITIONS.
*    ENDIF.
*  ENDDO.
  SORT IT_CONDITIONS BY SQNO.
