*&---------------------------------------------------------------------*
*&  Include           ZPAYMENT_VOUCHER_SS
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

PARAMETERS : P_BUKRS TYPE BSAK-BUKRS DEFAULT '1000' MODIF ID BU,
*              P_GJAHR TYPE BSAK-GJAHR,
             P_LIFNR TYPE BSAK-LIFNR OBLIGATORY .
SELECT-OPTIONS : ""S_LIFNR FOR V_LIFNR OBLIGATORY ,
                S_AUGBL FOR V_AUGBL OBLIGATORY.
*SELECT-OPTIONS : S_GJAHR FOR  V_GJAHR."TYPE BSAK-GJAHR OBLIGATORY.
PARAMETERS: P_GJAHR TYPE BSAK-GJAHR OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
*PARAMETERS: PDF AS CHECKBOX .
*SELECTION-SCREEN END OF BLOCK B2.
