*&---------------------------------------------------------------------*
*&  Include           ZPAYMENT_VOUCHER_SS
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

PARAMETERS : P_BUKRS TYPE BSAK-BUKRS DEFAULT '1000' MODIF ID BU,
             P_LIFNR TYPE BSAK-LIFNR OBLIGATORY.
*             P_AUGBL TYPE BSAK-AUGBL OBLIGATORY.
*SELECT-OPTIONS : S_GJAHR FOR  V_GJAHR."TYPE BSAK-GJAHR OBLIGATORY.
SELECT-OPTIONS : S_BELNR FOR  V_BELNR OBLIGATORY."TYPE BSAK-GJAHR OBLIGATORY.
PARAMETERS:   S_GJAHR TYPE BSAK-GJAHR OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

*SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
*PARAMETERS: PDF AS CHECKBOX .
*SELECTION-SCREEN END OF BLOCK B2.
