*&---------------------------------------------------------------------*
*& Report ZPO_KONV_UPDATETABLE
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZPO_KONV_UPDATETABLE.

TABLES :PRCD_ELEMENTS.

*DATA: IT_KONV TYPE STANDARD TABLE OF PRCD_ELEMENTS,
*      WA_KONV LIKE LINE OF IT_KONV .

DATA: BEGIN OF ITAB OCCURS 1.

    INCLUDE STRUCTURE prcd_elements.

DATA: END OF ITAB.

DATA: WTAB LIKE ITAB.

DATA : IT_KONV TYPE TABLE OF PRCD_ELEMENTS,
       WA_KONV TYPE PRCD_ELEMENTS.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS : S_KNUMV FOR PRCD_ELEMENTS-KNUMV.
SELECTION-SCREEN END OF BLOCK B1.

SELECT * FROM PRCD_ELEMENTS
*SELECT * FROM KONV
  INTO TABLE IT_KONV
  WHERE KNUMV IN S_KNUMV
  AND   KSCHL in ( 'ZPFL', 'ZSCV' ).


LOOP AT IT_KONV INTO WA_KONV.
  IF WA_KONV-KNTYP = 'D' or WA_KONV-KNTYP = 'A'.
    WA_KONV-KNTYP = 'B'.
*    MODIFY KONV  FROM WA_KONV .
    MODIFY PRCD_ELEMENTS  FROM WA_KONV .


    WRITE : WA_KONV-KNUMV , WA_KONV-KPOSN.

    CLEAR: WA_KONV.
  ENDIF.
ENDLOOP.
