"""added by Pranit 30.08.2024
"""added by Pranit 05.09.2024
IF HEADER-AUART EQ 'AUT1' OR HEADER-AUART EQ 'KAUT'.
  CLEAR HEADER-MATNR.
  HEADER-MATNR = HEADER-PLNBEZ.
ENDIF.


IF HEADER-AUART EQ 'AUT1' OR HEADER-AUART EQ 'KAUT'.
SELECT SINGLE STLNR FROM MAST INTO @DATA(WA_MAST) WHERE matnr = @HEADER-PLNBEZ.
SELECT SINGLE IDNRK FROM STPO INTO @DATA(WA_STPO) WHERE STLNR = @WA_MAST
                                           AND   POSNR = '0010'.
  CLEAR HEADER-MATNR.
  HEADER-MATNR = WA_STPO.
ENDIF.
















