"Name: \PR:SAPLCOBC\FO:READ_RESB_IND_CONV\SE:BEGIN\EI
ENHANCEMENT 0 ZPROD_ORD_SLOC_DEFAULT.
*
*   BREAK PRIMUSABAP.

  LOOP AT resb_bt.
     IF CAUFVD-WERKS = 'PL01' AND ( SY-TCODE = 'CO01' OR SY-TCODE = 'CO40'  ).
    IF CAUFVD-AUART+0(1) = 'K'.
*    IF resb_bt-LGORT+0(1) = 'K'.
    resb_bt-LGORT = 'KRM0'.
    MODIFY resb_bt.
     ENDIF.
     ENDIF.
  ENDLOOP.

ENDENHANCEMENT.
