"Name: \PR:SAPMQBAA\IC:MQBAAO10\SE:END\EI
ENHANCEMENT 0 ZQM_QI01_INDC.
*
**MODULE screen_control  OUTPUT .
*  BREAK-POINT.
**ENDMODULE.

 MODULE ZGREEN_CHAN OUTPUT.
   BREAK PRIMUSABAP.
     IF QINF-WERK NE 'PL01'.
    LOOP AT SCREEN.
      IF SCREEN-name = 'QINF-ZGREEN_CHAN'..
        SCREEN-ACTIVE  = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
  ENDIF.

  IF SY-tcode = 'QI03'.
    LOOP AT SCREEN.
      IF SCREEN-name = 'QINF-ZGREEN_CHAN'..
        SCREEN-INPUT  = 0.
      ENDIF.
        MODIFY SCREEN.
    ENDLOOP.
  ENDIF.

 ENDMODULE.

ENDENHANCEMENT.
