PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSALE_ORD_VAL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSALE_ORD_VAL-PRODUCT .
    FIELD ZSALE_ORD_VAL-SUB_CAT .
    FIELD ZSALE_ORD_VAL-COM_CODE_DESC .
    FIELD ZSALE_ORD_VAL-COMPONENT_QTY .
    FIELD ZSALE_ORD_VAL-COMPONENT_UNIT .
    FIELD ZSALE_ORD_VAL-COMPONENT_TYPE .
    FIELD ZSALE_ORD_VAL-PATTERN .
    FIELD ZSALE_ORD_VAL-TOOL .
    FIELD ZSALE_ORD_VAL-DIES .
    FIELD ZSALE_ORD_VAL-MC_FIXTURES .
    FIELD ZSALE_ORD_VAL-INFRA_LEAD_TIME .
    FIELD ZSALE_ORD_VAL-COMP_LEAD_TIME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSALE_ORD_VAL-PRODUCT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
