DATA: L_WERKS   TYPE WERKS_D,
      L_ADRNR   TYPE ADRNR,
      L_COUNTRY TYPE LAND1.
TYPES : BEGIN OF T_VBELV,
          VBELV TYPE VBELN_VON,
        END OF T_VBELV.
DATA : IT_SO TYPE TABLE OF T_VBELV.

SELECT SINGLE WERKS
INTO L_WERKS
FROM LIPS
WHERE VBELN = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB.

************************************************
SELECT SINGLE VBELV
FROM VBFA
INTO V_SO
WHERE VBELN = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB.

IF SY-SUBRC = 0.
  SELECT SINGLE AUDAT
  FROM VBAK
  INTO V_DATE
  WHERE VBELN = V_SO.

  SELECT SINGLE VSART ZTERM INCO1 INCO2
  FROM VBKD
  INTO (V_VSART,V_ZTERM,V_INCO1,V_INCO2)
  WHERE VBELN = V_SO.

  IF SY-SUBRC = 0.
    IF V_VSART IS INITIAL.
      SELECT SINGLE VSART
        INTO V_VSART
        FROM VBKD
        JOIN VBFA ON VBFA~VBELV = VBKD~VBELN
        WHERE VBFA~VBELN = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB
          AND VSART NE SPACE.
    ENDIF.
    IF NOT V_VSART IS INITIAL.
      SELECT SINGLE BEZEI
      FROM T173T
      INTO V_BEZEI
      WHERE VSART = V_VSART
      AND SPRAS = SY-LANGU.
    ENDIF.

    SELECT SINGLE VTEXT
    FROM TVZBT
    INTO V_VTEXT
    WHERE SPRAS = 'EN'
    AND ZTERM = V_ZTERM.
  ENDIF.
ENDIF.

SELECT SINGLE VBELN ERDAT
FROM VBFA
INTO (V_INVOICE ,V_ERDAT)
WHERE VBELV = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB
AND ( VBTYP_N = 'M'
OR VBTYP_N = 'U').

CONCATENATE V_ERDAT+0(4) V_ERDAT+4(2) V_ERDAT+6(2) INTO
LV_INVOICE_DATE SEPARATED BY '.'.
