*BREAK-POINT.
SELECT SINGLE FKDAT
  INTO V_PCK_LST_DT
  FROM LIKP
  WHERE VBELN = IS_NAST-OBJKY.

CONCATENATE V_PCK_LST_DT+0(4) V_PCK_LST_DT+4(2) V_PCK_LST_DT+6(2)
INTO LV_PCK_LST_DATE SEPARATED BY '.'. "Added by Awais on 03.11.2023
"20231025
*SELECT SINGLE VBELN
*   INTO INBOUND
*   FROM LIKP
*   WHERE VERUR = is_nast-objky.

SELECT VBELN
       VERUR FROM LIKP INTO TABLE IT_LIKP
       WHERE VERUR = IS_NAST-OBJKY.


SORT IT_LIKP DESCENDING BY VBELN.

READ TABLE IT_LIKP INTO WA_LIKP INDEX 1.
IF SY-SUBRC = 0.
  INBOUND = WA_LIKP-VBELN.
ENDIF.

CONCATENATE gs_vbrk-fkdat+0(4) gs_vbrk-fkdat+4(2) gs_vbrk-fkdat+6(2)
INTO LV_INV_LST_DATE SEPARATED BY '.'.








