"Name: \PR:SAPLV60A\FO:T180_LESEN\SE:END\EI
ENHANCEMENT 0 ZSAVEVF02.
*
DATA: I_VEHICAL TYPE TABLE OF ZVEHICALNO_TABLE,
      S_VEHICAL TYPE ZVEHICALNO_TABLE.

IF SY-TCODE = 'VF02'.
SELECT * FROM ZVEHICALNO_TABLE
              INTO TABLE I_VEHICAL
              WHERE BILLING_NO = VBRK-VBELN.
  LOOP AT I_VEHICAL INTO S_VEHICAL.
    S_VEHICAL-SR_NO           = S_VEHICAL-SR_NO.
    S_VEHICAL-VEHICAL_NO      = S_VEHICAL-VEHICAL_NO.
    S_VEHICAL-QUANTITY        = S_VEHICAL-QUANTITY.
    S_VEHICAL-UNIT_OF_MEASURE = S_VEHICAL-UNIT_OF_MEASURE.

    EXPORT S_VEHICAL TO MEMORY ID 'WXYZ'.
    CLEAR: S_VEHICAL.
  ENDLOOP.

ENDIF.

ENDENHANCEMENT.
