"Name: \FU:RV_INVOICE_DOCUMENT_ADD\SE:END\EI
ENHANCEMENT 0 ZSAVE_VEHICALDATA1.

" BADI_SD_SEPA_FAKTURA
*  INSERT ZVEHICALNO_TABLE FROM ZVEHICAL.


  DATA: ZVEHICAL TYPE ZVEHICLE_TB,
        LT_FINAL TYPE TABLE OF ZVEHICLE_TB.

        TYPES: BEGIN OF TS_ZVEHICLE_TB,
        sel             TYPE char1,
        SR_NO           TYPE ZVEHICLE_TB-SR_NO,
        VEHICAL_NO      TYPE ZVEHICLE_TB-VEHICAL_NO,
        QUANTITY        TYPE ZVEHICLE_TB-QUANTITY,
        UNIT_OF_MEASURE TYPE ZVEHICLE_TB-UNIT_OF_MEASURE,
      END OF TS_ZVEHICLE_TB.
DATA:I_VEHICAL TYPE TABLE OF  ts_ZVEHICLE_TB,
     S_VEHICAL TYPE ts_ZVEHICLE_TB.

IF SY-TCODE = 'VF01' ."OR SY-TCODE = 'VF02'.
IMPORT I_VEHICAL FROM MEMORY ID 'ABCD'.

    LOOP AT I_VEHICAL ASSIGNING FIELD-SYMBOL(<FS>).
      zvehical-BILLING_NO = XVBUK-vbeln.
      zvehical-VEHICAL_NO = <FS>-VEHICAL_NO.
zvehical-QUANTITY = <FS>-QUANTITY.
zvehical-UNIT_OF_MEASURE = <FS>-UNIT_OF_MEASURE.
zvehical-SR_NO = <FS>-SR_NO.

  modify ZVEHICLE_TB FROM ZVEHICAL ."TRANSPORTING BILLING_NO.
  CLEAR:ZVEHICAL.
    ENDLOOP.


ENDIF.


ENDENHANCEMENT.
