CLEAR : V_TEXT.
" CHANGE TO INSER FIELD EXADDTAX1 FROM J_1IEXCHDR "
IF WA_CONDITION-SQNO = 5.
  WA_CONDITION-KWERT =  WA_HDR-EXADDTAX1.
ENDIF.


V_TEXT = WA_CONDITION-KWERT.
CONDENSE V_TEXT.

counter = counter + 1.
