TYPES: GT_TYPESERNR_PRT LIKE KOMSER OCCURS 0.

TYPES:BEGIN OF T_LIPS,
      MATNR TYPE LIPS-MATNR,
      LFIMG TYPE LIPS-LFIMG,
      END OF T_LIPS.

TYPES:BEGIN OF T_MAKT,
      MATNR TYPE MAKT-MATNR,
      MAKTX TYPE MAKT-MAKTX,
      END OF T_MAKT.

TYPES:BEGIN OF T_MARA,
      MATNR TYPE MARA-MATNR,
      GROES TYPE MARA-GROES,
      END OF T_MARA.

TYPES:BEGIN OF T_VEPO,
     VBELN TYPE VEPO-VBELN,
     POSNR TYPE VEPO-POSNR,
     VENUM TYPE VEPO-VENUM,
     VEMNG TYPE VEPO-VEMNG,
END OF T_VEPO.

TYPES:BEGIN OF T_VEKP,
      EXIDV TYPE VEKP-EXIDV,
      VHILM TYPE VEKP-VHILM,
      VHILM_KU TYPE VEKP-VHILM_KU,
      BRGEW TYPE VEKP-BRGEW,
      NTGEW TYPE VEKP-NTGEW,
END OF T_VEKP.

