DATA: L_KNUMV, GV_ANZPK,
      V_POSNR TYPE POSNR,
      TOT_BOX TYPE LFIMG.

V_IND = V_IND + 1.
DATA: LV_ANZPK TYPE ANZPK,
      C TYPE C.

CLEAR : GV_ANZPK, LV_ANZPK, WA_MARA, GV_TXT, "GV_AMT,
        GV_KBETR, WA_BX, WA_SZ, GV_LFIMG, G_TERM, G_BSTKD.
C = C + 1.

clear wa_REFPURORD.
read table IS_BIL_INVOICE-IT_REFPURORD into wa_refpurord WITH key ITM_NUMBER = GS_IT_GEN-ITM_NUMBER.


*SELECT single vBELN
*        POSNR
*        MATNR
*        MATKL
*        ARKTX
*        LFIMG
*        VGBEL
*        VGPOS
*  FROM LIPS INTO CORRESPONDING FIELDS OF wa_LIPS
*  WHERE VBELN = IS_BIL_INVOICE-HD_REF-DELIV_NUMB
*  AND   POSNR = V_POSNR
*  AND   PSTYV = 'ZTAN'.

*IF IT_LIPS IS NOT INITIAL.
**if sy-subrc = 0.
**SELECT single  vbeln
**         posnr
**          ZTERM
**          BSTKD
**     FROM VBKD
**     INTO CORRESPONDING FIELDS OF wa_vbkd
**     WHERE VBELN = wa_LIPS-VGBEL.
***     and posnr = wa_lips-vgpos. "IS_BIL_INVOICE-HD_REF-ORDER_NUMB.
**
**  SELECT SINGLE VTEXT FROM TVZBT INTO
**   G_TEXT1 WHERE ZTERM = G_TERM
**           AND   SPRAS = 'EN'.
**
***    V_POSNR = V_POSNR + 1.
**ENDIF.

SELECT SINGLE
        VBELN
        POSNR
        MATNR
        MATKL
        ARKTX
        LFIMG
  FROM LIPS INTO WA_BX
  WHERE VBELN = IS_BIL_INVOICE-HD_REF-DELIV_NUMB
  AND   POSNR = V_POSNR
  AND   PSTYV = 'HUPM'.

SELECT SINGLE MATNR GROES
  FROM MARA
  INTO WA_SZ
  WHERE MATNR = WA_BX-MATNR.

V_POSNR = V_POSNR + 1.

  SELECT SINGLE
          MATNR
*          GROES
          ZSIZE
    FROM MARA INTO CORRESPONDING FIELDS OF WA_MARA
    WHERE MATNR = GS_IT_GEN-MATERIAL.

GV_LFIMG = WA_BX-LFIMG.

TOT_BOX = TOT_BOX + GV_LFIMG.

IF NOT GV_LFIMG IS INITIAL.

CALL FUNCTION 'SPELL_AMOUNT'
 EXPORTING
   AMOUNT          = GV_LFIMG
*   CURRENCY        = ' '
*   FILLER          = ' '
   LANGUAGE        = SY-LANGU
 IMPORTING
   IN_WORDS        = GV_TXT
 EXCEPTIONS
   NOT_FOUND       = 1
   TOO_LARGE       = 2
   OTHERS          = 3
          .
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
ENDIF.
