V_IND = V_IND + 1.
DATA: LV_ANZPK TYPE ANZPK.

CLEAR : GV_ANZPK, LV_ANZPK, WA_LIPS, WA_MARA, GV_TXT, GV_AMT,
        GV_KBETR, WA_BX, WA_SZ, GV_LFIMG.
C = C + 1.

SELECT SINGLE
        VBELN
        POSNR
        MATNR
        MATKL
        ARKTX
        LFIMG
  FROM LIPS INTO WA_BX
  WHERE VBELN = IS_BIL_INVOICE-HD_REF-DELIV_NUMB
  AND   POSNR = V_POSNR
  AND   PSTYV = 'HUPM'.

SELECT SINGLE MATNR GROES
  FROM MARA
  INTO WA_SZ
  WHERE MATNR = WA_BX-MATNR.

V_POSNR = V_POSNR + 1.

  SELECT SINGLE
          MATNR
*          GROES
          ZSIZE
    FROM MARA INTO CORRESPONDING FIELDS OF WA_MARA
    WHERE MATNR = GS_IT_GEN-MATERIAL.

GV_LFIMG = WA_BX-LFIMG.

TOT_BOX = TOT_BOX + GV_LFIMG.

IF NOT GV_LFIMG IS INITIAL.

CALL FUNCTION 'SPELL_AMOUNT'
 EXPORTING
   AMOUNT          = GV_LFIMG
*   CURRENCY        = ' '
*   FILLER          = ' '
   LANGUAGE        = SY-LANGU
 IMPORTING
   IN_WORDS        = GV_TXT
 EXCEPTIONS
   NOT_FOUND       = 1
   TOO_LARGE       = 2
   OTHERS          = 3
          .
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
ENDIF.

DATA : WA_PRICE TYPE LBBIL_IT_PRICE.
CLEAR WA_PRICE.
READ TABLE IS_BIL_INVOICE-IT_PRICE INTO WA_PRICE WITH KEY ITM_NUMBER = GS_IT_GEN-ITM_NUMBER.
IF SY-SUBRC = 0.
  GV_AMT = GV_AMT + WA_PRICE-NETWR.
*  TG_AMT = TG_AMT + GV_AMT ."WA_PRICE-NETWR.
  GV_KBETR = WA_PRICE-NETWR / GS_IT_GEN-FKIMG.
endif.
