V_IND = V_IND + 1.

CLEAR : WA_LIPS1 , WA_MARA , GV_ZSIZE, GV_TXT. " WA_VBFA1, WA_VBKD.

SELECT SINGLE ZSIZE FROM MARA INTO GV_ZSIZE
    WHERE MATNR = WA_LIPS-MATNR.

  SELECT SINGLE
        VBELN
        POSNR
        PSTYV
        MATNR
        MATKL
        ARKTX
        KDMAT
        LFIMG
FROM LIPS INTO CORRESPONDING FIELDS OF WA_LIPS1
WHERE VBELN = WA_LIPS-VBELN
AND   PSTYV = 'HUPM'
  AND POSNR = V_POSNR.


IF WA_LIPS1-PSTYV IS  INITIAL.
  CLEAR WA_VBRL-VBELN_VF.
ENDIF.


GV_LFIMG = WA_LIPS1-LFIMG.

TOT_BOX = TOT_BOX + GV_LFIMG.

IF SY-SUBRC = 0.
  SELECT SINGLE
          MATNR
          GROES
    FROM MARA INTO CORRESPONDING FIELDS OF WA_MARA
    WHERE MATNR = WA_LIPS1-MATNR.

ENDIF.
V_POSNR = V_POSNR + 1.

**************************************************

SELECT SINGLE J_1ICHID FROM J_1IMTCHID INTO GV_J_1ICHID
    WHERE MATNR = WA_VBRP-MATNR
    AND   WERKS = L_WERKS.

SELECT SINGLE J_1IEXCD FROM J_1IMOCUST INTO GV_J_1IEXCD
    WHERE KUNNR = LV_KUNAG.
***********************************************

IF NOT GV_LFIMG IS INITIAL.

CALL FUNCTION 'SPELL_AMOUNT'
 EXPORTING
   AMOUNT          = GV_LFIMG
*   CURRENCY        = ' '
*   FILLER          = ' '
   LANGUAGE        = SY-LANGU
 IMPORTING
   IN_WORDS        = GV_TXT
 EXCEPTIONS
   NOT_FOUND       = 1
   TOO_LARGE       = 2
   OTHERS          = 3
          .
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
ENDIF.

GV_LFIMG1 = WA_LIPS-LFIMG.

CLEAR: WA_VBKD, WA_VBFA1.

SELECT SINGLE VBELV
              POSNV
              VBELN
              POSNN
              VBTYP_N
              VBTYP_V
         FROM VBFA INTO CORRESPONDING FIELDS OF WA_VBFA1
         WHERE VBELN   = LV_VBELN1      "WA_VBRL-VBELN_VF "LV_VBELN_VF
         AND   VBTYP_V = 'C'.

  SELECT SINGLE
                VBELN
                POSNR
                VSART
                INCO1
                BSTKD
*                KURRF
                ZTERM
                FROM VBKD
    INTO CORRESPONDING FIELDS OF WA_VBKD
    WHERE VBELN = WA_VBFA1-VBELV.
