DATA: L_LAND1 TYPE LAND1,
L_KUNNR TYPE KUNNR.
IF IS_DLV_DELNOTE-HD_GEN-SHIP_TO_PARTY NE IS_DLV_DELNOTE-HD_GEN-SOLD_TO_PARTY.
  G_COUNT1 = '2'.
ENDIF.

L_KUNNR = IS_DLV_DELNOTE-HD_GEN-SOLD_TO_PARTY.
CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
  EXPORTING
    INPUT  = L_KUNNR
  IMPORTING
    OUTPUT = L_KUNNR.

SELECT SINGLE LAND1 NAME1
FROM KNA1
INTO (L_LAND1, V_NAME1)
WHERE KUNNR = IS_DLV_DELNOTE-HD_GEN-SOLD_TO_PARTY
AND   SPRAS = SY-LANGU.

IF SY-SUBRC IS INITIAL.
  SELECT SINGLE LANDX FROM T005T
  INTO G_LANDX3
  WHERE LAND1 = L_LAND1
  AND   SPRAS = SY-LANGU.
ENDIF.
*************************************************
SELECT SINGLE VBELV
FROM VBFA
INTO V_SO
WHERE VBELN = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB.

IF SY-SUBRC = 0.
  SELECT SINGLE AUDAT
  FROM VBAK
  INTO V_DATE
  WHERE VBELN = V_SO.
ENDIF.

SELECT SINGLE VBELN
FROM VBFA
INTO V_INVOICE
WHERE VBELV = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB
AND ( VBTYP_N = 'M'
OR VBTYP_N = 'U').

SELECT SINGLE VSART
FROM VBKD
INTO V_VSART
WHERE VBELN = V_SO.

SELECT SINGLE BEZEI
FROM T173T
INTO V_BEZEI
WHERE VSART = V_VSART
AND SPRAS = 'EN'.
**********************************************
SELECT
MATNR
LFIMG
FROM LIPS
INTO TABLE IT_LIPS
WHERE VBELN = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB
AND   PSTYV = 'HUPM'.

LOOP AT IT_LIPS INTO WA_LIPS.
  V_LFIMG1 = V_LFIMG1 + WA_LIPS-LFIMG.
  CONDENSE V_LFIMG1.
ENDLOOP.
