CLEAR : V_TEXT, WA_CONDITION.
V_TEXT = TOTAL_AMOUNT.
"CONCATENATE v_text '- TOTAL' INTO v_text.
CONDENSE V_TEXT.

" For Total Invoice-amount :
CLEAR : AMNT, TOTAL_INVOICE_AMOUNT_TEXT.
AMNT = TOTAL_AMOUNT.

CALL FUNCTION 'HR_IN_CHG_INR_WRDS'
EXPORTING
aMT_IN_NUM               = AMNT
IMPORTING
AMT_IN_WORDS             = TOTAL_INVOICE_AMOUNT_TEXT
EXCEPTIONS
DATA_TYPE_MISMATCH       = 1
OTHERS                   = 2
.
IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ELSE.
  CONDENSE TOTAL_INVOICE_AMOUNT_TEXT.
ENDIF.


*CLEAR : V_TEXT, WA_CONDITION.
*READ TABLE IT_CONDITIONS INTO WA_CONDITION WITH KEY SQNO = counter.
*IF SY-SUBRC <> 0.
*  V_TEXT = '0.00'.
*else.
*  TOTAL_AMOUNT = TOTAL_AMOUNT + WA_CONDITION-KWERT.
*  V_TEXT = WA_CONDITION-KWERT.
*ENDIF.
*
*"CONCATENATE v_text '-' WA_CONDITION-descr INTO v_text.
*"CONCATENATE v_text '-' counter INTO v_text.
*CONDENSE V_TEXT.
*
*counter = counter + 1.
