
TYPES: BEGIN OF TY_VBRP,
        VBELN TYPE VBELN,
        WERKS TYPE WERKS,
       END OF TY_VBRP.
*
*TYPES: BEGIN OF TY_J_1IMOCOMP,
*        BUKRS     TYPE BUKRS,
*        WERKS     TYPE WERKS_D,
*        J_1IPANNO TYPE J_1IPANNO,
*        J_1ISERN  TYPE J_1ISERN,
*        J_1IEXCD  TYPE J_1IEXCD,
*        J_1ICSTNO TYPE J_1ICSTNO,
*        J_1ILSTNO TYPE J_1ILSTNO,
*       END OF TY_J_1IMOCOMP.

  TYPES: BEGIN OF TY_J_1IEXCHDR,
        BUKRS     TYPE BUKRS,
        WERKS     TYPE WERKS_D,
        J_1IPANNO TYPE J_1IPANNO,
        J_1ISERN  TYPE J_1ISERN,
        J_1IEXCD  TYPE J_1IEXCD,
        J_1ICSTNO TYPE J_1ICSTNO,
        J_1ILSTNO TYPE J_1ILSTNO,
       END OF TY_J_1IEXCHDR.















