
DATA:  L_COUNTRY TYPE LAND1.

SELECT SINGLE KUNNR FROM LIKP
INTO G_KUNNR
WHERE VBELN = IS_BIL_INVOICE-HD_REF-DELIV_NUMB.


IF SY-SUBRC = 0.
  SELECT SINGLE ADRNR FROM KNA1
  INTO G_ADRNR
  WHERE KUNNR = G_KUNNR.
ENDIF.

IF SY-SUBRC = 0.
  SELECT SINGLE
          NAME1
          STREET
          SORT1
          CITY1
          POST_CODE1
          TEL_NUMBER
          FAX_NUMBER
          COUNTRY
     FROM ADRC
     INTO  (G_NAME,
            G_STREET,
            G_SORT1,
            G_CITY,
            G_POST_CODE,
            G_TEL_NUMBER,
            G_FAX_NUMBER,
            L_COUNTRY)
  WHERE ADDRNUMBER = G_ADRNR.
ENDIF.
IF SY-SUBRC = 0.
  SELECT SINGLE LANDX FROM T005T INTO G_LANDX
  WHERE LAND1 = L_COUNTRY AND
  SPRAS = 'EN'.
ENDIF.
