* read order data
CLEAR GS_IT_REFORD.
READ TABLE IS_BIL_INVOICE-IT_REFORD INTO GS_IT_REFORD
           WITH KEY BIL_NUMBER = GS_IT_GEN-BIL_NUMBER
                    ITM_NUMBER = GS_IT_GEN-ITM_NUMBER BINARY SEARCH.

* read purchase order data
CLEAR GS_IT_REFPURORD.
READ TABLE IS_BIL_INVOICE-IT_REFPURORD INTO GS_IT_REFPURORD
           WITH KEY BIL_NUMBER = GS_IT_GEN-BIL_NUMBER
                    ITM_NUMBER = GS_IT_GEN-ITM_NUMBER BINARY SEARCH.

* read delivery data
CLEAR GS_IT_REFDLV.
READ TABLE IS_BIL_INVOICE-IT_REFDLV INTO GS_IT_REFDLV
           WITH KEY BIL_NUMBER = GS_IT_GEN-BIL_NUMBER
                    ITM_NUMBER = GS_IT_GEN-ITM_NUMBER BINARY SEARCH.

* read G2 reference
CLEAR GS_IT_REFVG2.
READ TABLE IS_BIL_INVOICE-IT_REFVG2 INTO GS_IT_REFVG2
           WITH KEY BIL_NUMBER = GS_IT_GEN-BIL_NUMBER
                    ITM_NUMBER = GS_IT_GEN-ITM_NUMBER BINARY SEARCH.

















