*BREAK PRIMUS.
CLEAR : WA_MARA, TG_AMT, GV_AMT, V_REC_COUNT." WA_MARA, GV_TXT, GV_AMT, GV_KBETR.

DESCRIBE TABLE IS_BIL_INVOICE-IT_GEN LINES V_REC_COUNT.

SELECT SINGLE KNUMV
         FROM VBRK
         INTO L_KNUMV
        WHERE VBELN = IS_BIL_INVOICE-HD_GEN-BIL_NUMBER.

IF IS_BIL_INVOICE-HD_GEN-BIL_WAERK = 'USD'.
  CURR = 'USD'.
ELSEIF IS_BIL_INVOICE-HD_GEN-BIL_WAERK = 'EUR'.
  CURR = 'EURO'.
ELSEIF IS_BIL_INVOICE-HD_GEN-BIL_WAERK = 'GBP'.   "Added By Nilay on 04.12.2023
  CURR = 'GBP'.
ELSEIF IS_BIL_INVOICE-HD_GEN-BIL_WAERK = 'SAR'.   "Added By Nilay on 28.12.2023
  CURR = 'SAR'.

ENDIF.

*break primus.
*if sfsy-page = sfsy-formpages.
*  gk = 'P'.
*  endif.
