

* read condition data
CLEAR GS_IT_KOND.
CLEAR GS_IT_PRICE.

DATA: GS_IT_KOND_WA TYPE LBBIL_IT_KOND.
LOOP AT IS_BIL_INVOICE-IT_KOND INTO GS_IT_KOND_WA
WHERE BIL_NUMBER = GS_IT_GEN-BIL_NUMBER
AND ITM_NUMBER = GS_IT_GEN-ITM_NUMBER.
IF GS_IT_KOND_WA-KOEIN ='%'.
DIVIDE GS_IT_KOND_WA-KBETR BY 10.
ENDIF.
WRITE GS_IT_KOND_WA-KBETR TO GS_IT_KOND_WA-BTRMW CURRENCY '2'.
APPEND GS_IT_KOND_WA TO GS_IT_KOND.
*   ENDIF.
ENDLOOP.








