SELECT SINGLE
          ZTERM
          BSTKD
     FROM VBKD
     INTO (G_TERM, G_BSTKD)
     WHERE VBELN = IS_BIL_INVOICE-HD_REF-ORDER_NUMB.

IF SY-SUBRC = 0.
  SELECT SINGLE VTEXT FROM TVZBT INTO
   G_TEXT1 WHERE ZTERM = G_TERM
           AND   SPRAS = 'EN'.
ENDIF.

SELECT SINGLE WAERK INCO1 INCO2 KURRF FROM VBRK INTO
(G_WAERK, G_INCO1, G_INCO2, G_KURRF) WHERE VBELN = IS_BIL_INVOICE-HD_GEN-BIL_NUMBER.
