CLEAR : V_TEXT, WA_CONDITION, COUNTER.
*READ TABLE IT_CONDITIONS INTO WA_CONDITION WITH KEY SQNO = counter.
*IF SY-SUBRC <> 0.
*  V_TEXT = '0.00'.
*else.
*  TOTAL_AMOUNT = TOTAL_AMOUNT + WA_CONDITION-KWERT.
*  V_TEXT = WA_CONDITION-KWERT.
*ENDIF.
V_TEXT = TOTAL_AMOUNT.
*CONCATENATE v_text '-' WA_CONDITION-kschl INTO v_text.
"CONCATENATE v_text '-' counter INTO v_text.
CONDENSE V_TEXT.

IF COUNTER <> 1.
  COUNTER = 1.
ENDIF.
COUNTER = COUNTER + 1.
