
BREAK primus.
V_IND = V_IND + 1.
CLEAR GS_IT_QM.
READ TABLE
IS_DLV_DELNOTE-IT_QM INTO GS_IT_QM
WITH KEY DELIV_NUMB = GS_IT_GEN-DELIV_NUMB
ITM_NUMBER = GS_IT_GEN-ITM_NUMBER BINARY SEARCH.
**********************************************************
**************************************************
*CLEAR WA_VEPO.
*SELECT SINGLE VBELN  POSNR VENUM
*  INTO WA_VEPO
*  FROM VEPO
*  WHERE VBELN = GS_IT_GEN-DELIV_NUMB
*  AND POSNR = GS_IT_GEN-ITM_NUMBER.

*IF SY-SUBRC = 0.

SELECT SINGLE MATNR
  FROM LIPS
  INTO V_MATNR1
   WHERE VBELN = WA_VEPO-VBELN
  AND POSNR = WA_VEPO-POSNR.
IF SY-SUBRC = 0.
  SELECT SINGLE MATNR MAKTX
  FROM MAKT
  INTO WA_MAKT1
    WHERE MATNR = V_MATNR1.
ENDIF.


CLEAR W_VEKP.
SELECT SINGLE EXIDV VHILM VHILM_KU BRGEW NTGEW
  FROM VEKP
  INTO W_VEKP
  WHERE VENUM = WA_VEPO-VENUM.

IF SY-SUBRC = 0.
  CLEAR WA_MAKT.
  SELECT SINGLE MATNR MAKTX
    FROM MAKT
    INTO WA_MAKT
      WHERE MATNR = W_VEKP-VHILM.

  IF SY-SUBRC = 0.
    CLEAR WA_MARA.
    SELECT SINGLE MATNR GROES
    FROM MARA
    INTO WA_MARA
      WHERE MATNR = W_VEKP-VHILM.
  ENDIF.
ENDIF.

SELECT SINGLE ANZPK
FROM LIKP
INTO LV_ANZPK
WHERE VBELN = WA_vepo-VBELN.
