*break-point.
CLEAR : V_TEXT, WA_CONDITION.
READ TABLE IT_CONDITIONS INTO WA_CONDITION WITH KEY SQNO = counter.
IF SY-SUBRC <> 0.
  V_TEXT = '0.00'.
else.
  TOTAL_AMOUNT = TOTAL_AMOUNT + WA_CONDITION-KWERT.
  IF NOT WA_CONDITION-KBETR IS INITIAL.
    PERFORM FORMAT_NUM USING WA_CONDITION-KBETR CHANGING V_TEXT.
    CONCATENATE v_text WA_CONDITION-WAERS INTO V_TEXT.  "WA_CONDITION-KWERT.
  ENDIF.
ENDIF.

*CONCATENATE v_text '-' WA_CONDITION-kschl INTO v_text.
"CONCATENATE v_text '-' WA_CONDITION-descr INTO v_text.
*CONCATENATE v_text '-' counter INTO v_text.
CONDENSE V_TEXT.

*counter = counter + 1.

*select single * from J_1IEXCHDR into wa_J_1IEXCHDR
*  where RDOC =
