
DATA: L_ADRNR TYPE AD_ADDRNUM.

SELECT SINGLE ADRNR
FROM KNA1
INTO L_ADRNR
WHERE KUNNR = IS_DLV_DELNOTE-HD_GEN-SHIP_TO_PARTY.

IF SY-SUBRC IS INITIAL.
  SELECT SINGLE *
  FROM ADRC
  INTO WA_ADRC
  WHERE ADDRNUMBER = L_ADRNR.
ENDIF.

SELECT SINGLE LANDX
FROM T005T
INTO G_LANDX1
WHERE LAND1 = WA_ADRC-COUNTRY
AND   SPRAS = SY-LANGU.
***********************************************
DATA: L_ADRNR1 TYPE AD_ADDRNUM.

SELECT SINGLE ADRNR
FROM KNA1
INTO L_ADRNR1
WHERE KUNNR = IS_DLV_DELNOTE-HD_GEN-SOLD_TO_PARTY.

IF SY-SUBRC IS INITIAL.
  SELECT SINGLE *
  FROM ADRC INTO WA_ADRC1
  WHERE ADDRNUMBER = L_ADRNR1.
ENDIF.

SELECT SINGLE LANDX
FROM T005T
INTO G_LANDX1_1
WHERE LAND1 = WA_ADRC1-COUNTRY
AND SPRAS = SY-LANGU.












