CLEAR GS_HD_REF.

SELECT  VBELN
        POSNR
        PARVW
        ADRNR
        FROM VBPA INTO CORRESPONDING FIELDS OF TABLE IT_VBPA
        WHERE VBELN = LV_VBELN
        AND   PARVW = 'RE'.

READ TABLE IT_VBPA INTO WA_VBPA INDEX 1.

IF NOT IT_VBPA IS INITIAL.
  SELECT SINGLE
       NAME1
       STREET
       SORT1
       CITY1
       POST_CODE1
       TEL_NUMBER
       FAX_NUMBER
       COUNTRY
  FROM ADRC
  INTO CORRESPONDING FIELDS OF WA_ADRC
  WHERE ADDRNUMBER = WA_VBPA-ADRNR.
ENDIF.
