*BREAK-POINT.
*IT_FINAL = IT_FINAL1.
LOOP AT IT_FINAL INTO WA_FINAL.

WA_FINAL1-TAX_AMT = WA_FINAL1-TAX_AMT + WA_FINAL-kwert.
IF WA_FINAL-kwert IS INITIAL.
WA_FINAL1-TAX_AMT = WA_FINAL1-TAX_AMT + wa_final-VALUE.
ENDIF.


*CLEAR:wa_final,wa_final1.
ENDLOOP.
APPEND WA_FINAL1 TO IT_FINAL1.


gross = WA_FINAL1-TAX_AMT.






