DATA: L_KNUMV TYPE KNUMV.
DATA: W_VBRK TYPE VBRK.
DATA: L_KNUMV1 TYPE KNUMV,
*       WA_PRICE TYPE LBBIL_IT_PRICE,
       W_KONV TYPE KONV.








SELECT SINGLE
              KNUMV
         FROM VBRK
         INTO L_KNUMV1
        WHERE VBELN = IS_BIL_INVOICE-HD_GEN-BIL_NUMBER.



*READ TABLE IS_BIL_INVOICE-IT_PRICE INTO WA_PRICE WITH KEY ITM_NUMBER = GS_IT_GEN-ITM_NUMBER.
IF SY-SUBRC = 0.

SELECT SINGLE * INTO W_KONV
  FROM KONV WHERE KNUMV = L_KNUMV1
  AND KPOSN = GS_IT_GEN-ITM_NUMBER AND KSCHL = 'ZPR0'.
  .

*  SELECT SINGLE
*                KBETR
*                KWERT
*           FROM KONV
*           INTO (GV_KBETR,
*                 GV_KWERT)
*          WHERE KNUMV = L_KNUMV
*          AND   KSCHL = 'ZPR0'.

IF SY-SUBRC = 0.
*  CLEAR: TG_AMT.
*  GV_AMT = WA_PRICE-NETWR.
   V_KWERT = W_KONV-KWERT.
*  V_KWERT = GV_KWERT.
  TG_AMT = TG_AMT + V_KWERT .
  GV_KBETR = W_KONV-KBETR.
*  GV_KBETR = WA_PRICE-NETWR / GS_IT_GEN-FKIMG.
endif.


*  WRITE  GV_KWERT TO V_KWERT.

* GV_AMT = GV_FKIMG * V_KWERT.
* GV_AMT = GS_IT_GEN-FKIMG * V_KWERT.

*  REPLACE ALL  OCCURRENCES OF ',' IN V_KWERT
*  WITH '/'.
*  REPLACE ALL  OCCURRENCES OF '.' IN V_KWERT
*  WITH ','.
*  REPLACE ALL  OCCURRENCES OF '/' IN V_KWERT
*WITH '.'.

ENDIF.


DATA : WA_PRICE TYPE LBBIL_IT_PRICE,
      LV_KBETR TYPE KBETR.
.
LV_KBETR = GV_KBETR.
CLEAR : WA_PRICE." gv_amt, gv_kbetr.



*
*SELECT SINGLE
*              KNUMV
*         FROM VBRK
*         INTO L_KNUMV1
*        WHERE VBELN = GS_IT_GEN-BIL_NUMBER.
*
