CLEAR AMNT.
AMNT = TOTAL_CENVAT.

CALL FUNCTION 'HR_IN_CHG_INR_WRDS'
EXPORTING
aMT_IN_NUM               = AMNT
IMPORTING
AMT_IN_WORDS             = TOTAL_AMOUNT_TEXT
EXCEPTIONS
DATA_TYPE_MISMATCH       = 1
OTHERS                   = 2
.
IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ELSE.
*  "TOTAL_AMOUNT_TEXT = 'TWO LAKH EIGHTY THOUSAND Rupees'. "... tEMP CODE ... TO BE REMOVED.
*  CONCATENATE 'TWO LAKH EIGHTY THOUSAND Rupees'
*              '-' 'TWO LAKH EIGHTY THOUSAND Rupees'
*              INTO TOTAL_AMOUNT_TEXT SEPARATED BY ' ' respecting blanks.
  CONDENSE TOTAL_AMOUNT_TEXT.
ENDIF.
