
CLEAR : WA_VBRP, GV_KBETR.

READ TABLE IT_VBRP INTO WA_VBRP WITH KEY VGBEL = WA_LIPS-VBELN
                                         VGPOS = WA_LIPS-POSNR.

IF NOT WA_VBRP IS INITIAL." AND NOT GV_LFIMG IS INITIAL.
  GV_KBETR = WA_VBRP-NETWR / GV_LFIMG1.
ENDIF.
