

* read komk data
CLEAR GS_HD_KOND.
CLEAR GS_HD_KOMK.


GS_HD_KOMK-SUPOS   = IS_BIL_INVOICE-HD_KOMK-SUPOS.
GS_HD_KOMK-FKWRT   = IS_BIL_INVOICE-HD_KOMK-FKWRT.
* read condition data
CLEAR GS_HD_KOND.
DATA: GS_HD_KOND_WA TYPE LBBIL_HD_KOND.
LOOP AT IS_BIL_INVOICE-HD_KOND INTO GS_HD_KOND_WA
WHERE BIL_NUMBER = IS_BIL_INVOICE-HD_GEN-BIL_NUMBER.
IF GS_HD_KOND_WA-KOEIN ='%'.
DIVIDE GS_HD_KOND_WA-KBETR BY 10.
ENDIF.
WRITE GS_HD_KOND_WA-KBETR TO GS_HD_KOND_WA-BTRMW CURRENCY '2'.
APPEND GS_HD_KOND_WA TO GS_HD_KOND.
ENDLOOP.




