CLEAR GS_HD_REF.
MOVE-CORRESPONDING IS_BIL_INVOICE-HD_REF TO GS_HD_REF.

CLEAR GS_HD_GEN.
MOVE-CORRESPONDING IS_BIL_INVOICE-HD_GEN TO GS_HD_GEN.

SELECT  VBELN
        POSNR
        PARVW
        ADRNR
        FROM VBPA INTO CORRESPONDING FIELDS OF TABLE IT_VBPA
        WHERE VBELN = GS_HD_REF-ORDER_NUMB
        AND   PARVW = 'AG'.

READ TABLE IT_VBPA INTO WA_VBPA INDEX 1.

IF NOT IT_VBPA IS INITIAL.
  SELECT SINGLE
       NAME1
       STREET
       SORT1
       CITY1
       POST_CODE1
       TEL_NUMBER
       FAX_NUMBER
       COUNTRY
  FROM ADRC
  INTO CORRESPONDING FIELDS OF WA_ADRC
*  FOR ALL ENTRIES IN IT_VBPA
  WHERE ADDRNUMBER = WA_VBPA-ADRNR.
ENDIF.
