CLEAR GS_HD_GEN.

GS_HD_GEN = IS_BIL_INVOICE-HD_GEN.

DATA: L_ALAND TYPE ALAND.
SELECT SINGLE ALAND FROM TVST INTO L_ALAND
WHERE VSTEL = G_VSTEL.

SELECT SINGLE LANDX FROM T005T INTO G_LANDX1
WHERE LAND1 = L_ALAND AND
SPRAS = 'EN'.
