BREAK  primusabap.
* Condition 1
clear GV_COND.
DATA:LV_FROM_LGORT type MSEG-LGORT,
      LV_TO_LGORT type MSEG-LGORT.

LV_FROM_LGORT = GV_FROM_LGORT.

DATA: SL_FROM TYPE c LENGTH 4.
SL_FROM = GV_FROM_LGORT+0(1).
CONDENSE SL_FROM.
IF SL_FROM <> 'K'.
  CLEAR SL_FROM.
  SL_FROM = LV_FROM_LGORT.
ENDIF.

LV_TO_LGORT = GV_TO_LGORT.
DATA: SL_TO TYPE c LENGTH 4.
SL_TO = GV_TO_LGORT+0(1).
CONDENSE SL_TO.
IF SL_TO <> 'K'.
  CLEAR SL_TO.
  SL_TO = LV_TO_LGORT.
ENDIF.

* cONIDITON 1
IF  SL_FROM NE 'K' AND GV_FROM_LGORT NE 'SAN1'  AND  SL_TO EQ 'K'.


*  ship-to & consignee logic
  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'KPR1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

*from logiv
    SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'RM01' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

    GV_COND = '1'.

ELSEIF SL_FROM eq 'K' AND  SL_TO NE 'K' AND GV_TO_LGORT NE 'SAN1' .

*  ship-to & consignee logic
  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'RM01' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

*from logiv
    SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'KPR1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

    IF GV_COND IS INITIAL.
      GV_COND = '2'.
    ENDIF.

ELSEIF SL_FROM eq 'K' AND GV_TO_LGORT EQ 'SAN1'.

*  ship-to & consignee logic
  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'SAN1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

*from logiv
    SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'KPR1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

    IF GV_COND IS INITIAL.
      GV_COND = '3'.
    ENDIF.

ELSEIF GV_FROM_LGORT eq 'SAN1' AND  SL_TO EQ 'K' .

*  ship-to & consignee logic
  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'KPR1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

*from logiv
    SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'SAN1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.

    IF GV_COND IS INITIAL.
      GV_COND = '4'.
    ENDIF.

ENDIF.
