
CLEAR GV_TXT.
CLEAR GV_TXT1.

DATA : IT_HD_FIN TYPE LINE OF  LB_T_BIL_HD_FIN .

*&----------------------------------------------------------*&
*          CONVERTING TOTAL AMOUNT IN WORDS USD
*&----------------------------------------------------------*&

READ TABLE IS_BIL_INVOICE-HD_FIN  INTO IT_HD_FIN INDEX 1.

V_AMTWORDS = IT_HD_FIN-GAWRD.

REPLACE ALL OCCURRENCES OF 'USD' IN V_AMTWORDS WITH ' and CENTS '.
CONCATENATE V_AMTWORDS ' ONLY' INTO V_AMTWORDS.

*&----------------------------------------------------------*&
*          CONVERTING USD INTO INDIAN RUPEES IN WORDS
*&----------------------------------------------------------*&
DATA: V_KWERT1 TYPE PC207-BETRG.
REPLACE ALL OCCURRENCES OF ',' IN V_KWERT WITH ''.
V_KWERT = IS_BIL_INVOICE-HD_GEN-BIL_NETWR * G_KURRF.
V_KWERT1 = V_KWERT.

CALL FUNCTION 'HR_IN_CHG_INR_WRDS'
  EXPORTING
    AMT_IN_NUM         = V_KWERT1
  IMPORTING
    AMT_IN_WORDS       = GV_TXT1
  EXCEPTIONS
    DATA_TYPE_MISMATCH = 1
    OTHERS             = 2.
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.

REPLACE ALL OCCURRENCES OF 'Paise' IN GV_TXT1 WITH ' '.
REPLACE ALL OCCURRENCES OF 'Rupees' IN GV_TXT1 WITH ' and Paise '.
CONCATENATE GV_TXT1 ' ONLY' INTO GV_TXT1.
