*BREAK  primusabap.
* Condition 1
clear GV_COND.
DATA:LV_FROM_LGORT type MSEG-LGORT,
      LV_TO_LGORT type MSEG-LGORT.

LV_FROM_LGORT = GV_FROM_LGORT.

DATA: SL_FROM TYPE c LENGTH 4.
SL_FROM = GV_FROM_LGORT+0(1).
CONDENSE SL_FROM.
IF SL_FROM <> 'K'.
  CLEAR SL_FROM.
  SL_FROM = LV_FROM_LGORT.
ENDIF.

LV_TO_LGORT = GV_TO_LGORT.
DATA: SL_TO TYPE c LENGTH 4.
SL_TO = GV_TO_LGORT+0(1).
CONDENSE SL_TO.
*IF SL_TO <> 'K'.
IF SL_TO = 'K'.
  CLEAR SL_TO.
  SL_TO = LV_TO_LGORT.
ENDIF.

DATA: LV_1 TYPE CHAR4 VALUE 'FG01',
      LV_2 TYPE CHAR4 VALUE 'MCN1',
      LV_3 TYPE CHAR4 VALUE 'NDT1',
      LV_4 TYPE CHAR4 VALUE 'PLG1',
      LV_5 TYPE CHAR4 VALUE 'SC01',
      LV_6 TYPE CHAR4 VALUE 'SCR1',
      LV_7 TYPE CHAR4 VALUE 'SFG1',
      LV_8 TYPE CHAR4 VALUE 'SLR1',
      LV_9 TYPE CHAR4 VALUE 'SPC1',
      LV_10 TYPE CHAR4 VALUE 'SRN1',
      LV_11 TYPE CHAR4 VALUE 'TPI1',
      LV_12 TYPE CHAR4 VALUE 'VLD1',
      LV_13 TYPE CHAR4 VALUE 'PRD1',
      LV_14 TYPE CHAR4 VALUE 'RM01'.
*    break primusabap.

*IF  SL_FROM eq 'PN01' AND  GV_TO_LGORT EQ 'FG01' .""ADDED BY PRANIT
  IF  GV_TO_LGORT eq LV_1  OR GV_TO_LGORT eq LV_2  OR
  GV_TO_LGORT eq LV_3  OR GV_TO_LGORT eq LV_4  OR
  GV_TO_LGORT eq LV_5  OR GV_TO_LGORT eq LV_6  OR
  GV_TO_LGORT eq LV_7  OR GV_TO_LGORT eq LV_8  OR
  GV_TO_LGORT eq LV_9  OR GV_TO_LGORT eq LV_10 OR
  GV_TO_LGORT eq LV_11 OR GV_TO_LGORT eq LV_12 OR
  GV_TO_LGORT eq LV_13 OR GV_TO_LGORT eq LV_14
  AND  SL_FROM EQ 'PN01'.
*      *  ship-to & consignee logic
  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'PN01' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
     SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE  WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
    IF GV_COND IS INITIAL.
      GV_COND = '5'.
    ENDIF.

     ELSEIF  SL_FROM eq LV_1  OR SL_FROM eq LV_2  OR
             SL_FROM eq LV_3  OR SL_FROM eq LV_4  OR
             SL_FROM eq LV_5  OR SL_FROM eq LV_6  OR
             SL_FROM eq LV_7  OR SL_FROM eq LV_8  OR
             SL_FROM eq LV_9  OR SL_FROM eq LV_10 OR
             SL_FROM eq LV_11 OR SL_FROM eq LV_12 OR
             SL_FROM eq LV_13 OR SL_FROM eq LV_14
             AND  SL_TO EQ 'P' .""ADDED BY PRANIT
*
  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE  LGORT = 'PN01' AND WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
     SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE  WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
    IF GV_COND IS INITIAL.
      GV_COND = '6'.
    ENDIF.

  ELSEIF  SL_FROM eq 'PN01' AND  SL_TO+0(1) EQ 'K' .""ADDED BY PRANIT

  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'PN01' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
     SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'KFG0' AND  WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
    IF GV_COND IS INITIAL.
      GV_COND = '7'.
    ENDIF.

  ELSEIF  SL_FROM eq 'PN01' AND  LV_TO_LGORT EQ 'SAN1' .""ADDED BY PRANIT

  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'PN01' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
     SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'SAN1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
    IF GV_COND IS INITIAL.
      GV_COND = '8'.
    ENDIF.

    ELSEIF  SL_FROM eq 'K' AND  LV_TO_LGORT EQ 'PN01' .

  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'KFG0' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
     SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'PN01' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
    IF GV_COND IS INITIAL.
      GV_COND = '1'.
    ENDIF.

        ELSEIF  SL_FROM eq 'SAN1' AND  LV_TO_LGORT EQ 'PN01' .

  SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'PN01' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_SHIP_TO
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
     SELECT SINGLE ADRNR FROM TWLAD
    INTO WA_ADRNR
    WHERE LGORT = 'SAN1' and WERKS = 'PL01'.

    IF SY-SUBRC EQ 0.
      SELECT single STREET CITY1 POST_CODE1 STR_SUPPL3 LOCATION
        FROM ADRC
        INTO WA_ADDRESS_CON_FROM
        WHERE ADDRNUMBER = WA_ADRNR-adrnr.
    ENDIF.
    IF GV_COND IS INITIAL.
      GV_COND = '9'.
    ENDIF.

ENDIF.
