*BREAK-POINT.

*DATA: LV_STWAE TYPE VBRK-WAERK.

IF WA_FINAL-VBELN2 IS NOT INITIAL.
 SELECT SINGLE AUBEL  FROM VBRP
        INTO LV_AUBEL
        WHERE VBELN = WA_FINAL-VBELN2 .

 SELECT SINGLE FKDAT WAERK FROM VBRK INTO ( LV_DATE02, LV_STWAE )
                    WHERE VBELN = WA_FINAL-VBELN2 .

ENDIF.
*BREAK-POINT.
IF LV_AUBEL IS NOT INITIAL.
SELECT SINGLE AUDAT  FROM VBAK INTO LV_AUDAT
                    WHERE VBELN = LV_AUBEL .
ENDIF.


  CONCATENATE LV_DATE02+0(4)'-' LV_DATE02+4(2)'-'LV_DATE02+6(2) INTO LV_DATE03.


TYPES:BEGIN OF TY_KONV,
      KNUMV  TYPE KONV-KNUMV,
      KPOSN  TYPE KONV-KPOSN,
      KSCHL  TYPE KONV-KSCHL,
      KWERT  TYPE KONV-KWERT,
      WAERS  TYPE KONV-WAERS,
      END OF TY_KONV.

 DATA: IT_KONV TYPE TABLE OF TY_KONV,
       WA_KONV TYPE  TY_KONV.

*BREAK PRIMUSABAP.

DATA : LV_VBRK  TYPE VBRK-KNUMV,
       LV_KNUMV TYPE VBRK-KNUMV.

IF  WA_FINAL-VBELN2 IS NOT INITIAL.
  SELECT SINGLE KNUMV KUNAG FROM VBRK INTO ( LV_VBRK , LV_KNUMV )
                       WHERE VBELN = WA_FINAL-VBELN2.

  SELECT KNUMV KPOSN KSCHL KWERT WAERS  FROM KONV  INTO CORRESPONDING FIELDS OF TABLE IT_KONV
                      WHERE KNUMV = LV_VBRK.
*                      AND   KSCHL = 'ZPFO' AND  KSCHL = 'MWAS'
*                      AND   KSCHL = 'ZADV' AND  KSCHL ='ZADP' .

  SELECT SINGLE STCD3 FROM KNA1 INTO LV_STCD3 WHERE KUNNR = LV_KNUMV.


 LOOP AT IT_KONV INTO WA_KONV .
 IF ( WA_KONV-KSCHL = 'ZADV' OR WA_KONV-KSCHL = 'ZADP' ) AND WA_KONV-KPOSN = '0'  .
      LV_KWERT  = LV_KWERT  + WA_KONV-KWERT.
 ENDIF.
IF WA_KONV-KSCHL = 'ZPFO'.
    LV_KWERT  = LV_KWERT  + WA_KONV-KWERT.
ELSEIF WA_KONV-KSCHL = 'MWAS'.
    LV_KWERT  = LV_KWERT  + WA_KONV-KWERT.
ELSEIF  WA_KONV-KSCHL = 'ZFR1'.
     LV_KWERT  = LV_KWERT  + WA_KONV-KWERT.
ELSEIF  WA_KONV-KSCHL = 'ZDC1'.
     LV_KWERT  = LV_KWERT  + WA_KONV-KWERT.
ELSEIF  WA_KONV-KSCHL = 'ZIN1'.
     LV_KWERT  = LV_KWERT  + WA_KONV-KWERT.
ELSEIF  WA_KONV-KSCHL = 'ZTE1'.
     LV_KWERT  = LV_KWERT  + WA_KONV-KWERT.
ENDIF.

 ENDLOOP.

DATA IN_WORDS TYPE SPELL.

     CALL FUNCTION 'SPELL_AMOUNT'
      EXPORTING
        AMOUNT          = LV_KWERT
        CURRENCY        = LV_STWAE             "'INR'  CHANGES BY MA(06.02.2024)
*        FILLER          = ' '
        LANGUAGE        = 'E'
      IMPORTING
        IN_WORDS        = IN_WORDS
      EXCEPTIONS
        NOT_FOUND       = 1
        TOO_LARGE       = 2
*        OTHERS          = 3
               .
     IF SY-SUBRC <> 0.
* Implement suitable error handling here
     ENDIF.

  IF LV_STWAE = 'SAR'.
   IF IN_WORDS-DECWORD = 'ZERO'.
     CONCATENATE 'SAUDI RIYAL' IN_WORDS-WORD 'ONLY' INTO LV_AMT_WORD SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE 'SAUDI RIYAL' IN_WORDS-WORD 'AND' IN_WORDS-DECWORD 'HALLALS ONLY' INTO LV_AMT_WORD SEPARATED BY SPACE.
     ENDIF.

   ELSEIF LV_STWAE = 'USD'.
     IF IN_WORDS-DECWORD = 'ZERO'.
     CONCATENATE IN_WORDS-WORD 'DOLLARS' INTO LV_AMT_WORD SEPARATED BY SPACE.
     ELSE.
     CONCATENATE IN_WORDS-WORD 'DOLLARS' 'AND' IN_WORDS-DECWORD 'CENTS 'INTO LV_AMT_WORD SEPARATED BY SPACE.
     ENDIF.

   ELSEIF LV_STWAE = 'INR'.
    IF IN_WORDS-DECWORD = 'ZERO'.
     CONCATENATE IN_WORDS-WORD 'RUPEES ONLY' INTO LV_AMT_WORD SEPARATED BY SPACE.
    ELSE.
     CONCATENATE IN_WORDS-WORD 'RUPEES AND'  IN_WORDS-DECWORD 'PAISE' INTO LV_AMT_WORD SEPARATED BY SPACE.
    ENDIF.

   ELSEIF LV_STWAE = 'EUR'.
    IF IN_WORDS-DECWORD = 'ZERO'.
     CONCATENATE IN_WORDS-WORD 'EURO'INTO LV_AMT_WORD SEPARATED BY SPACE.
    ELSE.
     CONCATENATE IN_WORDS-WORD 'EURO AND'  IN_WORDS-DECWORD 'CENTS'  INTO LV_AMT_WORD SEPARATED BY SPACE.
    ENDIF.
   ELSEIF LV_STWAE = 'CNY'.
    IF IN_WORDS-DECWORD = 'ZERO'.
     CONCATENATE IN_WORDS-WORD 'YUANS' INTO LV_AMT_WORD SEPARATED BY SPACE.
    ELSE.
     CONCATENATE IN_WORDS-WORD 'YUANS AND' IN_WORDS-DECWORD 'JIAOS'  INTO LV_AMT_WORD SEPARATED BY SPACE.
    ENDIF.
   ELSEIF LV_STWAE = 'GBP'.
    IF IN_WORDS-DECWORD = 'ZERO'.
     CONCATENATE IN_WORDS-WORD 'POUNDS'  INTO LV_AMT_WORD SEPARATED BY SPACE.
    ELSE.
     CONCATENATE IN_WORDS-WORD 'POUNDS AND'IN_WORDS-DECWORD 'PENNYS'  INTO LV_AMT_WORD SEPARATED BY SPACE.
    ENDIF.
   ENDIF.

ENDIF.
*BREAK-POINT.

IF LV_AUDAT IS NOT INITIAL.

CONCATENATE LV_AUDAT+0(4)'-' LV_AUDAT+4(2)'-'LV_AUDAT+6(2) INTO LV_DATE01.

ENDIF.

IF  LV_KWERT IS NOT INITIAL.

ENDIF.
