DATA: L_WERKS TYPE WERKS_D,
L_ADRNR TYPE ADRNR,
L_COUNTRY TYPE LAND1.


SELECT SINGLE WERKS
INTO L_WERKS
FROM LIPS
WHERE VBELN = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB.

SELECT SINGLE ADRNR
INTO L_ADRNR
FROM T001W
WHERE WERKS = L_WERKS.

SELECT SINGLE *"NAME1 STREET CITY1 POST_CODE1 COUNTRY
FROM ADRC
INTO PLANT_ADD"(G_NAME, G_STREET, G_CITY, G_POST_CODE, L_COUNTRY)
WHERE ADDRNUMBER = L_ADRNR.

SELECT SINGLE LANDX
FROM T005T
INTO G_LANDX
WHERE LAND1 = L_COUNTRY
AND   SPRAS = 'EN'.
*************************************************
SELECT SINGLE J_1IEXCD
FROM J_1IMOCOMP
INTO L_ECC
WHERE WERKS = L_WERKS.

SELECT SINGLE VBELN ERDAT
FROM VBFA
INTO (V_INVOICE ,V_ERDAT)
WHERE VBELV = IS_DLV_DELNOTE-HD_GEN-DELIV_NUMB
AND ( VBTYP_N = 'M'
OR VBTYP_N = 'U').


