DATA: L_KNUMV TYPE KNUMV,
      INDEX TYPE SY-INDEX.

SELECT SINGLE KNUMV
         FROM VBRK
         INTO L_KNUMV
        WHERE VBELN = IS_BIL_INVOICE-HD_GEN-BIL_NUMBER.

*SELECT * FROM KONV
*  INTO TABLE I_KONV
*  WHERE KNUMV =  VBRK-VBELN
*  AND KSCHL =  'ZPRO'.
INDEX = INDEX + 1.

IF SY-SUBRC = 0.
 READ TABLE I_KONV INTO W_KONV INDEX SY-INDEX.
ENDIF.

*IF SY-SUBRC = 0.
*
*  SELECT
*                KBETR
*                KWERT
*           FROM KONV
*           INTO (GV_KBETR,
*                 GV_KWERT)
*          WHERE KNUMV = L_KNUMV
*          AND   KSCHL = 'ZPR0'.
*
*  WRITE  GV_KWERT TO V_KWERT.

* GV_AMT = GV_FKIMG * V_KWERT.
* GV_AMT = GS_IT_GEN-FKIMG * V_KWERT.

*  REPLACE ALL  OCCURRENCES OF ',' IN V_KWERT
*  WITH '/'.
*  REPLACE ALL  OCCURRENCES OF '.' IN V_KWERT
*  WITH ','.
*  REPLACE ALL  OCCURRENCES OF '/' IN V_KWERT
*WITH '.'.

*ENDIF.
