
SELECT SINGLE VBELV
              POSNV
              VBELN
              POSNN
              VBTYP_N
              VBTYP_V
         FROM VBFA INTO CORRESPONDING FIELDS OF WA_VBFA1
         WHERE VBELN   = LV_VBELN_VF
         AND   VBTYP_V = 'C'.

  SELECT SINGLE
                VBELN
                POSNR
                VSART
                INCO1
                INCO2
                BSTKD
*                KURRF
                ZTERM
                FROM VBKD
    INTO CORRESPONDING FIELDS OF WA_VBKD
    WHERE VBELN = WA_VBFA1-VBELV.

IF SY-SUBRC = 0.
  SELECT SINGLE VTEXT FROM TVZBT INTO
   G_TEXT1 WHERE ZTERM = WA_VBKD-ZTERM
           AND   SPRAS = 'EN'.
ENDIF.

IF SY-SUBRC = 0.
  SELECT SINGLE BEZEI FROM T173T INTO GV_BEZEI
    WHERE VSART = WA_VBKD-VSART
    AND   SPRAS = 'EN'.
ENDIF.

SELECT SINGLE VSTEL FROM VBAP INTO
G_VSTEL WHERE VBELN = WA_VBFA1-VBELV.


SELECT SINGLE KZABE FROM EIKP
INTO G_KZABE
WHERE REFNR = LV_VBELN_VF.

SELECT SINGLE WAERK INCO1 INCO2 KURRF
  FROM VBRK
  INTO CORRESPONDING FIELDS OF WA_VBRK
  WHERE VBELN = LV_VBELN_VF.
