V_POSNR = '900001'.

REFRESH IT_VBRP.

SELECT VBELN POSNR MATNR ARKTX FKIMG NTGEW BRGEW NETWR VGBEL VGPOS
      FROM VBRP
      INTO CORRESPONDING FIELDS OF TABLE IT_VBRP
      WHERE VBELN = WA_VBRL-VBELN_VF.

SELECT SINGLE VBELV
              POSNV
              VBELN
              POSNN
              VBTYP_N
              VBTYP_V
         FROM VBFA INTO CORRESPONDING FIELDS OF  WA_VBFA
         WHERE VBELN   = WA_VBRL-VBELN_VF
         AND   VBTYP_V = 'J'.

SELECT
        VBELN
        POSNR
        PSTYV
        MATNR
        MATKL
        ARKTX
        KDMAT
        LFIMG
  FROM LIPS INTO CORRESPONDING FIELDS OF TABLE IT_LIPS
  WHERE VBELN = WA_VBFA-VBELV
  AND   PSTYV = 'ZTAN'.

LV_VBELN1  = WA_VBRL-VBELN_VF.
