CLEAR GS_HD_GEN.
CLEAR GS_HD_GEN_DESCRIPT.

GS_HD_GEN_DESCRIPT = IS_BIL_INVOICE-HD_GEN_DESCRIPT.
GS_HD_GEN = IS_BIL_INVOICE-HD_GEN.

DATA: L_VBELN TYPE VBELN.

SELECT SINGLE VSART FROM VBKD INTO
L_VSART WHERE VBELN = IS_BIL_INVOICE-HD_REF-ORDER_NUMB.

IF SY-SUBRC = 0.
  SELECT SINGLE BEZEI FROM T173T INTO GV_BEZEI
    WHERE VSART = L_VSART
    AND   SPRAS = 'EN'.
ENDIF.

SELECT SINGLE VSTEL FROM VBAP INTO
G_VSTEL WHERE VBELN = IS_BIL_INVOICE-HD_REF-ORDER_NUMB.


SELECT SINGLE KZABE FROM EIKP
INTO G_KZABE
WHERE REFNR = IS_BIL_INVOICE-HD_GEN-BIL_NUMBER.
