*&---------------------------------------------------------------------*
*&  Include           ZSO_STORAGE_LOCATION_SCREEN
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
SELECT-OPTIONS S_VBELN FOR VBAP-VBELN.     " Sales Doc No
PARAMETERS P_LGORT TYPE VBAP-LGORT.         " Storage Location
*PARAMETERS P_WERKS TYPE VBAP-WERKS DEFAULT 'PL01'.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
PARAMETERS P_DOWN AS CHECKBOX.
PARAMETERS P_FILE LIKE RLGRAP-FILENAME DEFAULT TEXT-015.
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN :BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-003.
SELECTION-SCREEN  COMMENT /1(60) TEXT-004.
SELECTION-SCREEN :END OF BLOCK B3.
