PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSOURCE_RESTC1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSOURCE_RESTC1-VBELN .
    FIELD ZSOURCE_RESTC1-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC1-POSNR .
    FIELD ZSOURCE_RESTC1-COM_CODE_DESC .
    FIELD ZSOURCE_RESTC1-PRODUCT .
    FIELD ZSOURCE_RESTC1-SUB_CAT .
    FIELD ZSOURCE_RESTC1-COUNTRY_RESTRICTION .
    FIELD ZSOURCE_RESTC1-SUPPLY_RESTRICTION .
    FIELD ZSOURCE_RESTC1-CHECK_BOX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSOURCE_RESTC1-VBELN .
    FIELD ZSOURCE_RESTC1-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC1-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
