PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSOURCE_RESTC2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSOURCE_RESTC2-VBELN .
    FIELD ZSOURCE_RESTC2-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC2-POSNR .
    FIELD ZSOURCE_RESTC2-COM_CODE_DESC .
    FIELD ZSOURCE_RESTC2-PRODUCT .
    FIELD ZSOURCE_RESTC2-SUB_CAT .
    FIELD ZSOURCE_RESTC2-COUNTRY_RESTRICTION .
    FIELD ZSOURCE_RESTC2-SUPPLY_RESTRICTION .
    FIELD ZSOURCE_RESTC2-CHECK_BOX .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSOURCE_RESTC2-VBELN .
    FIELD ZSOURCE_RESTC2-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC2-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
