PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZSOURCE_RESTC1-VBELN .
    FIELD ZSOURCE_RESTC1-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC1-POSNR .
    FIELD ZSOURCE_RESTC1-COM_CODE_DESC .
    FIELD ZSOURCE_RESTC1-PRODUCT .
    FIELD ZSOURCE_RESTC1-SUB_CAT .
    FIELD ZSOURCE_RESTC1-COUNTRY_RESTRICTION .
    FIELD ZSOURCE_RESTC1-SUPPLY_RESTRICTION .
    FIELD ZSOURCE_RESTC1-CHECK_BOX .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZSOURCE_RESTC1-VBELN .
    FIELD ZSOURCE_RESTC1-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC1-POSNR .
  module detail_pai.
 endchain.
