PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZSOURCE_RESTC2-VBELN .
    FIELD ZSOURCE_RESTC2-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC2-POSNR .
    FIELD ZSOURCE_RESTC2-COM_CODE_DESC .
    FIELD ZSOURCE_RESTC2-PRODUCT .
    FIELD ZSOURCE_RESTC2-SUB_CAT .
    FIELD ZSOURCE_RESTC2-COUNTRY_RESTRICTION .
    FIELD ZSOURCE_RESTC2-SUPPLY_RESTRICTION .
    FIELD ZSOURCE_RESTC2-CHECK_BOX .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZSOURCE_RESTC2-VBELN .
    FIELD ZSOURCE_RESTC2-COMPONENT_TYPE .
    FIELD ZSOURCE_RESTC2-POSNR .
  module detail_pai.
 endchain.
