

TYPES : BEGIN OF TY_BSAK,
          BUKRS TYPE BSAK-BUKRS,
          LIFNR TYPE BSAK-LIFNR,
          AUGBL TYPE BSAK-AUGBL,
          GJAHR TYPE BSAK-GJAHR,
          BELNR TYPE BSAK-BELNR,
          BLART TYPE BSAK-BLART,
          DMBTR TYPE BSAK-DMBTR,
          BUDAT TYPE BSAK-BUDAT,
          WRBTR TYPE BSAK-WRBTR,
  augdt TYPE bsak-augdt,
        END OF TY_BSAK.

        TYPES : BEGIN OF TY_BSAK1,
          BUKRS TYPE BSAK-BUKRS,
          LIFNR TYPE BSAK-LIFNR,
          AUGBL TYPE BSAK-AUGBL,
          GJAHR TYPE BSAK-GJAHR,
          BELNR TYPE BSAK-BELNR,
          BLART TYPE BSAK-BLART,
          DMBTR TYPE BSAK-DMBTR,
          BUDAT TYPE BSAK-BUDAT,
          WRBTR TYPE BSAK-WRBTR,
        END OF TY_BSAK1.

        TYPES : BEGIN OF TY_FINAL1,
            BELNR TYPE BSAK-BELNR,
            BLDAT TYPE BSAK-BLDAT,
            DMBTR TYPE BSAK-DMBTR,
            DMBTR1 TYPE BSAK-DMBTR,
            XBLNR TYPE BKPF-XBLNR,
            END OF TY_FINAL1.

