
REPORT ZSU_FM_CS01_TRANSFER.

TABLES: SSCRFIELDS.

TABLES : MARC.
TYPE-POOLS : SLIS.

DATA: FIELDCATALOG TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
      GD_LAYOUT    TYPE SLIS_LAYOUT_ALV.



DATA: IT_TAB   TYPE FILETABLE,
      GD_SUBRC TYPE I,
      L_FILE   TYPE RLGRAP-FILENAME.

DATA MATERIAL           TYPE CSAP_MBOM-MATNR.
DATA PLANT              TYPE CSAP_MBOM-WERKS.
DATA BOM_USAGE          TYPE CSAP_MBOM-STLAN.
DATA VALID_FROM         TYPE CSAP_MBOM-DATUV.
DATA CHANGE_NO          TYPE CSAP_MBOM-AENNR.
DATA REVISION_LEVEL     TYPE CSAP_MBOM-REVLV.
DATA I_STKO             TYPE STKO_API01.
DATA IT_STKO             TYPE  TABLE OF STKO_API01.

DATA FL_NO_CHANGE_DOC   TYPE CAPIFLAG-NO_CHG_DOC.
DATA FL_COMMIT_AND_WAIT TYPE CAPIFLAG-COMM_WAIT.
DATA FL_CAD             TYPE CSDATA-CHAR1.
DATA FL_DEFAULT_VALUES  TYPE CSDATA-XFELD.
DATA FL_RECURSIVE       TYPE CSDATA-XFELD.
DATA FL_WARNING         TYPE CAPIFLAG-FLWARNING.
DATA BOM_NO             TYPE STKO_API02-BOM_NO.
*DATA T_STPO             TYPE TABLE OF STPO_API01.
DATA T_DEP_DATA         TYPE STANDARD TABLE OF CSDEP_DAT.
DATA T_DEP_DESCR        TYPE STANDARD TABLE OF CSDEP_DESC.
DATA T_DEP_ORDER        TYPE STANDARD TABLE OF CSDEP_ORD.
DATA T_DEP_SOURCE       TYPE STANDARD TABLE OF CSDEP_SORC.
DATA T_DEP_DOC          TYPE STANDARD TABLE OF CSDEP_DOC.
DATA T_LTX_LINE         TYPE STANDARD TABLE OF CSLTX_LINE.
DATA T_STPU             TYPE STANDARD TABLE OF STPU_API01.
DATA T_FSH_BOMD         TYPE FSH_TT_BOMVD_API.
DATA T_SGT_BOMC         TYPE SGT_COMP_SEGMENT_T.
*DATA LS_STPO             TYPE  STPO_API01.


DATA: IT_RAW TYPE TRUXS_T_TEXT_DATA.

TYPES : BEGIN OF GT_FINAL,
          COMPONENT TYPE STPO-IDNRK,
          ITEM_CAT  TYPE STPO-POSTP,
          ITEM_LINE TYPE STPO-POSNR,
          COMP_QTY  TYPE STPO-MENGE,
          COMP_UNIT TYPE STPO-MEINS,
          REL_COST  TYPE SANKA,
          ISSUE_LOC TYPE CSLGO,
        END OF GT_FINAL.

TYPES : BEGIN OF GT_BOMAV,
          COMPONENT TYPE STPO-IDNRK,
          ITEM_CAT  TYPE STPO-POSTP,
          ITEM_LINE TYPE STPO-POSNR,
          COMP_QTY  TYPE STPO-MENGE,
          COMP_UNIT TYPE STPO-MEINS,
          REL_COST  TYPE SANKA,
          ISSUE_LOC TYPE CSLGO,
          REMARKS   TYPE STRING,
        END OF GT_BOMAV.

DATA : I_FILE   TYPE  TABLE  OF GT_FINAL,
       WA_FILE  TYPE GT_FINAL,
       LT_DATA  TYPE  TABLE  OF GT_FINAL,
       LS_DATA  TYPE GT_FINAL,
       LT_DATA1 TYPE  TABLE  OF GT_FINAL,
       IT_FINAL TYPE TABLE OF GT_FINAL,
       WA_FINAL TYPE GT_FINAL.

DATA : IT_BOMAV TYPE TABLE OF GT_BOMAV,
       WA_BOMAV TYPE GT_BOMAV.

DATA : G_TOT_REC_CNT TYPE P,
       G_SUC_REC_CNT TYPE P,
       G_ERR_REC_CNT TYPE P.


TYPES: BEGIN OF T_DATA,

         FIELD1 TYPE STRING,
         FIELD2 TYPE STRING,
         FIELD3 TYPE STRING,
         FIELD4 TYPE STRING,
*         FIELD5 TYPE STRING,
         FIELD6 TYPE STRING,
         FIELD7 TYPE STRING,
         FIELD8 TYPE STRING,
         FIELD9 TYPE STRING,
       END OF T_DATA.

DATA: IT_COL_NO     TYPE STANDARD TABLE OF T_DATA,
      WA_COL_NO     LIKE LINE OF IT_COL_NO,
      IT_HEADER     TYPE STANDARD TABLE OF T_DATA,
      WA_HEADER     LIKE LINE OF IT_HEADER,
      IT_SUB_HEADER TYPE STANDARD TABLE OF T_DATA,
      WA_SUB_HEADER LIKE LINE OF IT_SUB_HEADER,
      IT_DATA       TYPE STANDARD TABLE OF T_DATA,
      WA_DATA       LIKE LINE OF IT_DATA.

FIELD-SYMBOLS: <FS>.

DATA: BEGIN OF ITAB1 OCCURS 0, FIRST_NAME(10), END OF ITAB1.
DATA: BEGIN OF ITAB2 OCCURS 0, LAST_NAME(10), END OF ITAB2.
DATA: BEGIN OF ITAB3 OCCURS 0, FORMULA(50), END OF ITAB3.

DATA INDEX TYPE I.
DATA: LD_COLINDX TYPE I,
      LD_ROWINDX TYPE I.

DATA: APPLICATION TYPE OLE2_OBJECT,
      WORKBOOK    TYPE OLE2_OBJECT,
      SHEET       TYPE OLE2_OBJECT,
      CELLS       TYPE OLE2_OBJECT,
      CELL1       TYPE OLE2_OBJECT,
      CELL2       TYPE OLE2_OBJECT,
      RANGE       TYPE OLE2_OBJECT,
      FONT        TYPE OLE2_OBJECT,
      COLUMN      TYPE OLE2_OBJECT,
      SHADING     TYPE OLE2_OBJECT,
      BORDER      TYPE OLE2_OBJECT.

CONSTANTS: ROW_MAX TYPE I VALUE 256.

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
*PARAMETERS: P_UNAME LIKE RLGRAP-FILENAME,
*            P_TEST  AS CHECKBOX.
*SELECTION-SCREEN END OF BLOCK B1.
*
*SELECTION-SCREEN BEGIN OF LINE.
*SELECTION-SCREEN PUSHBUTTON (25) W_BUTTON USER-COMMAND BUT1.
*SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS: P_MATNR TYPE MAST-MATNR,
            P_WERKS TYPE MAST-WERKS DEFAULT 'PL01',
            P_STLAN TYPE MAST-STLAN DEFAULT '1' .
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
PARAMETERS: P_TWERKS TYPE MAST-WERKS.
SELECTION-SCREEN END OF BLOCK B2.

**************************ADDED BY PRIMUS JYOTI ON 25.01.2024******************
SELECTION-SCREEN : BEGIN OF BLOCK B3 WITH FRAME TITLE XYZ.
PARAMETERS: R1 RADIOBUTTON GROUP ABC DEFAULT 'X',
            R2 RADIOBUTTON GROUP ABC.
SELECTION-SCREEN: END OF BLOCK B3.
**********************************************************************************

AT SELECTION-SCREEN .

  IF P_MATNR IS INITIAL.
    MESSAGE 'Material Must be Required' TYPE 'E' DISPLAY LIKE 'E'.
  ELSEIF P_WERKS <> 'PL01'.
    MESSAGE 'BOM Material from PL01 Plant Only' TYPE 'E' DISPLAY LIKE 'E'.
  ELSEIF P_STLAN <> '1' .
    MESSAGE 'BOM Usage Production BOM Only(1)' TYPE 'E' DISPLAY LIKE 'E'.
  ENDIF.

  DATA : VBOMCNT TYPE N.
  SELECT COUNT(*) INTO VBOMCNT FROM MAST WHERE MATNR = P_MATNR AND WERKS = P_TWERKS AND STLAN = '1'.
  IF VBOMCNT > 0.
    MESSAGE 'BOM OF this Material aleady available in Requied Plant' TYPE 'E' DISPLAY LIKE 'E'.
  ENDIF.

INITIALIZATION.

  XYZ = 'BOM Extend'(tt1).


START-OF-SELECTION.


*
  DATA T_STPO         TYPE STANDARD TABLE OF STPO_API02.
  DATA W_STPO         TYPE  STPO_API02.
  DATA T_STPO1         TYPE STANDARD TABLE OF STPO_API01.
  DATA W_STPO1         TYPE STPO_API01.
  DATA T_STKO         TYPE STANDARD TABLE OF STKO_API02.
  DATA W_STKO         TYPE  STKO_API02.



  CALL FUNCTION 'CSAP_MAT_BOM_READ'
    EXPORTING
      MATERIAL  = P_MATNR
      PLANT     = P_WERKS
      BOM_USAGE = '1'
*     ALTERNATIVE          = ALTERNATIVE
*     VALID_FROM           = VALID_FROM
*     VALID_TO  = VALID_TO
*     CHANGE_NO = CHANGE_NO
*     REVISION_LEVEL       = REVISION_LEVEL
*     FL_DOC_LINKS         = FL_DOC_LINKS
*     FL_DMU_TMX           = FL_DMU_TMX
* IMPORTING
*     FL_WARNING           = FL_WARNING
    TABLES
      T_STPO    = T_STPO
      T_STKO    = T_STKO
    EXCEPTIONS
      ERROR     = 1
      OTHERS    = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  MOVE-CORRESPONDING T_STPO TO I_FILE.
*  move-CORRESPONDING p_matnr to I_FILE.
*  MOVE-CORRESPONDING T_STKO TO I_FILE.

*  loop at t_stko INTO
   WA_FILE-COMPONENT = P_matnr.
   APPEND WA_FILE to I_FILE.


  IF R1 = 'X'."added by primus jyoti on 25.01.2024

    IF I_FILE IS NOT INITIAL.

      DATA : V_BOMAV TYPE N.
      LOOP AT I_FILE INTO WA_FILE.
        SELECT COUNT(*) INTO V_BOMAV FROM MARC WHERE MATNR = WA_FILE-COMPONENT AND WERKS = P_TWERKS.

        IF V_BOMAV = 0."added by primus jyoti on 25.01.2024
          WA_BOMAV-COMPONENT = WA_FILE-COMPONENT.
          WA_BOMAV-REMARKS  = ' Components Not Created or Exended for required Plant'.
          APPEND WA_BOMAV TO IT_BOMAV.
          CLEAR WA_BOMAV.
          CLEAR V_BOMAV.
        ELSE.
          WA_BOMAV-COMPONENT = WA_FILE-COMPONENT.
          WA_BOMAV-REMARKS  = ' Components Created or Exended for required Plant'.
          APPEND WA_BOMAV TO IT_BOMAV.
          CLEAR WA_BOMAV.
          CLEAR V_BOMAV.
        ENDIF.
      ENDLOOP.
      IF IT_BOMAV IS NOT INITIAL.
*    ELSEIF SY-SUBRC = 0  AND IT_BOMAV IS NOT INITIAL.

*      FIELDCATALOG-FIELDNAME   = 'MATERIAL'.
*      FIELDCATALOG-SELTEXT_M   = 'Header Material'.
*      FIELDCATALOG-COL_POS     = 1.
*      FIELDCATALOG-OUTPUTLEN   = 20.
*      APPEND FIELDCATALOG TO FIELDCATALOG.
*      CLEAR  FIELDCATALOG.

        FIELDCATALOG-FIELDNAME   = 'COMPONENT'.
        FIELDCATALOG-SELTEXT_M   = 'Components'.
        FIELDCATALOG-COL_POS     = 1.
        FIELDCATALOG-OUTPUTLEN   = 20.
        APPEND FIELDCATALOG TO FIELDCATALOG.
        CLEAR  FIELDCATALOG.
        FIELDCATALOG-FIELDNAME   = 'REMARKS'.
        FIELDCATALOG-SELTEXT_M   = 'Remarks'.
        FIELDCATALOG-COL_POS     = 2.
        FIELDCATALOG-OUTPUTLEN   = 100.
        APPEND FIELDCATALOG TO FIELDCATALOG.
        CLEAR  FIELDCATALOG.

        CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
          EXPORTING
            I_CALLBACK_PROGRAM = SY-REPID
            IS_LAYOUT          = GD_LAYOUT
            IT_FIELDCAT        = FIELDCATALOG[]
            I_SAVE             = ' '
          TABLES
            T_OUTTAB           = IT_BOMAV[]
* EXCEPTIONS
*           PROGRAM_ERROR      = 1
*           OTHERS             = 2
          .
        IF SY-SUBRC <> 0.
* Implement suitable error handling here
        ENDIF.

*        MESSAGE 'Data Upload Failed' TYPE 'E' DISPLAY LIKE 'E'.
      ENDIF.

    ENDIF.

  ELSEIF R2 = 'X'."added by primus jyoti on 25.01.2024
*    IF SY-SUBRC = 0  AND IT_BOMAV IS INITIAL.
*    IF IT_BOMAV IS INITIAL."added by primus jyoti on 25.01.2024
    DATA : GV_DATE LIKE CSAP_MBOM-DATUV.
    GV_DATE  = SY-DATUM .

    CONCATENATE GV_DATE+6(4) GV_DATE+4(2) GV_DATE+0(4) INTO GV_DATE
    SEPARATED BY '.'.
      LOOP AT T_STPO INTO W_STPO.

       W_STPO1-ITEM_CATEG = W_STPO-ITEM_CATEG.
       W_STPO1-ITEM_NO    = W_STPO-ITEM_NO.
       W_STPO1-COMPONENT  = W_STPO-COMPONENT.
       W_STPO1-COMP_QTY   = W_STPO-COMP_QTY.
       W_STPO1-COMP_UNIT  = W_STPO-COMP_UNIT.
       W_STPO1-REL_COST   = W_STPO-REL_COST.
       W_STPO1-REL_PROD   = W_STPO-REL_PROD.
       APPEND W_STPO1 TO T_STPO1.
       CLEAR : W_STPO, W_STPO1.
      ENDLOOP.

      LOOP AT T_STKO INTO W_STKO.
        I_STKO-BASE_QUAN  =  W_STKO-BASE_QUAN .
        I_STKO-BASE_UNIT  =  W_STKO-BASE_UNIT  .
        I_STKO-BOM_STATUS =  W_STKO-BOM_STATUS .
        I_STKO-ALT_TEXT   =  W_STKO-ALT_TEXT   .
        I_STKO-LABORATORY =  W_STKO-LABORATORY .
        I_STKO-DELETE_IND =  W_STKO-DELETE_IND .
        I_STKO-BOM_TEXT   =  W_STKO-BOM_TEXT   .
        I_STKO-BOM_GROUP  =  W_STKO-BOM_GROUP  .
        I_STKO-AUTH_GROUP =  W_STKO-AUTH_GROUP .
        I_STKO-CAD_IND    =  W_STKO-CAD_IND    .
        APPEND I_STKO TO IT_STKO.
        ENDLOOP.

      CALL FUNCTION 'CSAP_MAT_BOM_CREATE'
        EXPORTING
          MATERIAL   = P_MATNR
          PLANT      = P_TWERKS
          BOM_USAGE  = '1'
*         ALTERNATIVE       = '01'
          VALID_FROM = GV_DATE
*         CHANGE_NO  =
*         REVISION_LEVEL    =
*         I_STKO     = LS_STKO
          I_STKO     = I_STKO
        TABLES
*         T_STPO     = LT_STPO
          T_STPO     = T_STPO1
        EXCEPTIONS
          ERROR      = 1
          OTHERS     = 2.

      IF SY-SUBRC <> 0.
* Implement suitable error handling here
      ENDIF.


*DATA T_PLANT            TYPE STANDARD TABLE OF PLANT_API.
*DATA W_PLANT            TYPE  PLANT_API.
*
*   W_PLANT = P_TWERKS.
*APPEND W_PLANT TO T_PLANT.
*
*CALL FUNCTION 'CSAP_MAT_BOM_ALLOC_CREATE'
*  EXPORTING
*    MATERIAL                 = P_MATNR
*   PLANT                    = 'PL01'
*    BOM_USAGE                = '1'
*   ALTERNATIVE              = '01'
**   FL_NO_CHANGE_DOC         = ' '
*   FL_COMMIT_AND_WAIT       = 'X'
* IMPORTING
*   FL_WARNING               = FL_WARNING
*   BOM_NO                   = BOM_NO
*  TABLES
*    T_PLANT                  = T_PLANT
** EXCEPTIONS
**   ERROR                    = 1
**   OTHERS                   = 2
*          .
*IF SY-SUBRC <> 0.
** Implement suitable error handling here
*ENDIF.




      IF SY-SUBRC IS INITIAL.
        MESSAGE 'Data Uploaded Successfully' TYPE 'S' DISPLAY LIKE 'S'.
      ENDIF.
*elseif R1 = 'X'."added by primus jyoti on 25.01.2024

*ENDLOOP.

    ENDIF.
