*&---------------------------------------------------------------------*
*&Report: ZSU_PRODUCTION_VAL_REPORT
*&Transaction: ZSU_PRD
*&Functional Cosultant: Devshree kalamkar
*&Technical Consultant: Shreya Sankpal
*&TR: DEVK912309
*&Date: 04.11.2023
*&Owner: DelVal Flow Controls
*&-------------------------------------
*&---------------------------------------------------------------------*
*& Report ZPRODUCTION_VAL_REPORT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSU_PRODUCTION_VAL_REPORT.

TYPE-POOLS:SLIS,
           OLE2.

*******Temp Variable
DATA:
  TMP_BUDAT TYPE MSEG-BUDAT_MKPF,
  TMP_KDAUF TYPE MSEG-KDAUF,
  TMP_MAT   TYPE MSEG-MATNR,
  TMP_DAUAT TYPE AFPO-DAUAT,
  TMP_LGORT TYPE MSEG-LGORT.


TYPES:
  BEGIN OF T_MAT_DOC,
    MBLNR      TYPE MSEG-MBLNR,
    MJAHR      TYPE MSEG-MJAHR,
    ZEILE      TYPE MSEG-ZEILE,
    BWART      TYPE MSEG-BWART,
    MATNR      TYPE MSEG-MATNR,
    WERKS      TYPE MSEG-WERKS,
    LGORT      TYPE MSEG-LGORT,
    KUNNR      TYPE MSEG-KUNNR,
    KDAUF      TYPE MSEG-KDAUF,
    KDPOS      TYPE MSEG-KDPOS,
    WAERS      TYPE MSEG-WAERS,
    MENGE      TYPE MSEG-MENGE,
    AUFNR      TYPE MSEG-AUFNR,
    BUDAT_MKPF TYPE MSEG-BUDAT_MKPF,
  END OF T_MAT_DOC,
  TT_MAT_DOC TYPE STANDARD TABLE OF T_MAT_DOC.

*TYPES: BEGIN OF TY_MSEG,
*         MBLNR      TYPE MSEG-MBLNR,
*         MJAHR      TYPE MSEG-MJAHR,
*         ZEILE      TYPE MSEG-ZEILE,
*         BWART      TYPE MSEG-BWART,
*         MATNR      TYPE MSEG-MATNR,
*         WERKS      TYPE MSEG-WERKS,
*         AUFNR      TYPE MSEG-AUFNR,
*         BUDAT_MKPF TYPE MSEG-BUDAT_MKPF,
*       END OF TY_MSEG.

DATA: IT_MSEG_261 TYPE TABLE OF T_MAT_DOC,
      WA_MSEG_261 TYPE  T_MAT_DOC.

TYPES: BEGIN OF TY_AUFM,
         MBLNR TYPE AUFM-MBLNR,
         MJAHR TYPE AUFM-MJAHR,
         ZEILE TYPE AUFM-ZEILE,
         BWART TYPE AUFM-BWART,
         MATNR TYPE AUFM-MATNR,
         WERKS TYPE AUFM-WERKS,
         AUFNR TYPE AUFM-AUFNR,
         BUDAT TYPE AUFM-BUDAT,
         DMBTR TYPE AUFM-DMBTR,"MODIFIED BY POONAM J.
       END OF TY_AUFM,
       TT_AUFM TYPE STANDARD TABLE OF TY_AUFM.

TYPES:
  BEGIN OF T_VBKD,
    VBELN TYPE VBKD-VBELN,
    POSNR TYPE VBKD-POSNR,
    KURSK TYPE VBKD-KURSK,
  END OF T_VBKD,
  TT_VBKD TYPE STANDARD TABLE OF T_VBKD.

TYPES:
  BEGIN OF T_COEP,
    KOKRS  TYPE COEP-KOKRS,
    BELNR  TYPE COEP-BELNR,
    BUZEI  TYPE COEP-BUZEI,
    WTGBTR TYPE COEP-WTGBTR,
    OBJNR  TYPE COEP-OBJNR,
  END OF T_COEP,
  TT_COEP TYPE STANDARD TABLE OF T_COEP.


TYPES:
  BEGIN OF T_ORDER_ITEM,
    AUFNR TYPE AFPO-AUFNR,
    POSNR TYPE AFPO-POSNR,
    DAUAT TYPE AFPO-DAUAT,
    PSMNG TYPE AFPO-PSMNG,
    PWERK TYPE AFPO-PWERK,
    OBJNR TYPE COEP-OBJNR,
  END OF T_ORDER_ITEM,
  TT_ORDER_ITEM TYPE STANDARD TABLE OF T_ORDER_ITEM.

TYPES:
  BEGIN OF T_ORDER_HDR,
    AUFNR TYPE AFKO-AUFNR,
    FTRMI TYPE AFKO-FTRMI,
  END OF T_ORDER_HDR,
  TT_ORDER_HDR TYPE STANDARD TABLE OF T_ORDER_HDR.

TYPES:
  BEGIN OF T_SALES_ORD_HDR,
    VBELN TYPE VBAK-VBELN,
    AUDAT TYPE VBAK-AUDAT,
    AUART TYPE VBAK-AUART,
    VKBUR TYPE VBAK-VKBUR,
    KNUMV TYPE VBAK-KNUMV,
    KUNNR TYPE VBAK-KUNNR,
    AEDAT TYPE VBAK-AEDAT,
    WAERK TYPE VBAK-WAERK,
  END OF T_SALES_ORD_HDR,
  TT_SALES_ORD_HDR TYPE STANDARD TABLE OF T_SALES_ORD_HDR.

TYPES:
  BEGIN OF T_SALES_ORD_ITEM,
    VBELN   TYPE VBAP-VBELN,
    POSNR   TYPE VBAP-POSNR,
    MATNR   TYPE VBAP-MATNR,
    KDMAT   TYPE VBAP-KDMAT,
    KWMENG  TYPE VBAP-KWMENG,
    DELDATE TYPE VBAP-DELDATE,
    KZWI1   TYPE VBAP-KZWI1,
  END OF T_SALES_ORD_ITEM,
  TT_SALES_ORD_ITEM TYPE STANDARD TABLE OF T_SALES_ORD_ITEM.

TYPES:
  BEGIN OF T_MAT_MAST,
    MATNR   TYPE MARA-MATNR,
    ZSERIES TYPE MARA-ZSERIES,
    ZSIZE   TYPE MARA-ZSIZE,
    BRAND   TYPE MARA-BRAND,
    MOC     TYPE MARA-MOC,
    TYPE    TYPE MARA-TYPE,
  END OF T_MAT_MAST,
  TT_MAT_MAST TYPE STANDARD TABLE OF T_MAT_MAST.

TYPES:
  BEGIN OF T_MAT_DESC,
    MATNR TYPE MAKT-MATNR,
    MAKTX TYPE MAKT-MAKTX,
  END OF T_MAT_DESC,
  TT_MAT_DESC TYPE STANDARD TABLE OF T_MAT_DESC.

TYPES:
  BEGIN OF T_VBEP,
    VBELN TYPE VBEP-VBELN,
    POSNR TYPE VBEP-POSNR,
    EDATU TYPE VBEP-EDATU,
  END OF T_VBEP,
  TT_VBEP TYPE STANDARD TABLE OF T_VBEP.

TYPES:
  BEGIN OF T_CUST_INFO,
    KUNNR TYPE KNA1-KUNNR,
    NAME1 TYPE KNA1-NAME1,
    STCD3 TYPE KNA1-STCD3,
  END OF T_CUST_INFO,
  TT_CUST_INFO TYPE STANDARD TABLE OF T_CUST_INFO.

TYPES:
  BEGIN OF T_MARC,
    MATNR TYPE MARC-MATNR,
    WERKS TYPE MARC-WERKS,
    DISPO TYPE MARC-DISPO,
  END OF T_MARC,
  TT_MARC TYPE STANDARD TABLE OF T_MARC.

TYPES:
  BEGIN OF T_MBEW,
    MATNR TYPE MBEW-MATNR,
    BWKEY TYPE MBEW-BWKEY,
    STPRS TYPE MBEW-STPRS,
  END OF T_MBEW,
  TT_MBEW TYPE STANDARD TABLE OF T_MBEW.

TYPES:
  BEGIN OF T_QAMB,
    PRUEFLOS TYPE QAMB-PRUEFLOS,
    TYP      TYPE QAMB-TYP,
    MBLNR    TYPE QAMB-MBLNR,
    MJAHR    TYPE QAMB-MJAHR,
    ZEILE    TYPE QAMB-ZEILE,
  END OF T_QAMB,
  TT_QAMB TYPE STANDARD TABLE OF T_QAMB.

TYPES:
  BEGIN OF T_QALS,
    PRUEFLOS TYPE QALS-PRUEFLOS,
    AUFNR    TYPE QALS-AUFNR,
    MJAHR    TYPE QALS-MJAHR,
    MBLNR    TYPE QALS-MBLNR,
  END OF T_QALS,
  TT_QALS TYPE STANDARD TABLE OF T_QALS.

**TYPES:
**  BEGIN OF t_t005u,
**    land1 TYPE t005u-land1,
**    bland TYPE t005u-bland,
**    bezei TYPE t005u-bezei,
**  END OF t_t005u.

TYPES:
  BEGIN OF T_FINAL,
    DISPO     TYPE MARC-DISPO,
    BRAND     TYPE MARA-BRAND,
    KDAUF     TYPE MSEG-KDAUF,
    KDPOS     TYPE MSEG-KDPOS,
    VKBUR     TYPE VBAK-VKBUR,
    MATNR     TYPE MSEG-MATNR,
    MAKTX     TYPE VBRP-ARKTX,
    LONG_TXT  TYPE CHAR100,
    DAUAT     TYPE AFPO-DAUAT,
    NAME1     TYPE KNA1-NAME1,
    EDATU     TYPE CHAR10, "vbep-edatu,
    KWMENG    TYPE VBAP-KWMENG,
    DELDATE   TYPE CHAR10, "vbap-deldate,
    KDMAT     TYPE VBAP-KDMAT,
    AUFNR     TYPE MSEG-AUFNR,
    MENGE     TYPE MSEG-MENGE,
    BUDAT_CON TYPE CHAR10, "mseg-budat_mkpf,
    BUDAT_IN  TYPE CHAR10, "mseg-budat_mkpf,
    PRD_AMT   TYPE VBAP-NETWR,
    NETPR     TYPE VBAP-NETPR,
    STPRS     TYPE MBEW-STPRS,
    ZSERIES   TYPE MARA-ZSERIES,
    ZSIZE     TYPE CHAR3, "mara-zsize,
    MOC       TYPE MARA-MOC,
    TYPE      TYPE MARA-TYPE,
    LGORT     TYPE MSEG-LGORT,
    AEDAT     TYPE CHAR10, "vbak-aedat,
    FTRMI     TYPE CHAR10, "afko-ftrmi,
    WAERK     TYPE VBAK-WAERK,
    KURSK     TYPE VBKD-KURSK,
    S_VAL     TYPE prcd_elements-KWERT,
    S_VAL_LC  TYPE prcd_elements-KWERT,
    AUART     TYPE VBAK-AUART,
    SO_CURR   TYPE VBKD-KURSK,
*    werks     TYPE mseg-werks,
*    kunnr     TYPE mseg-kunnr,
*    stcd3     TYPE kna1-stcd3,
*    kzwi1     TYPE vbap-kzwi1,
    CURR_DATE TYPE SY-DATUM,
    FST_ISH   TYPE CHAR11,
    LST_ISH   TYPE CHAR11,
    DEL_DAT   TYPE CHAR11,
  END OF T_FINAL,
  TT_FINAL TYPE STANDARD TABLE OF T_FINAL.


TYPES:
  BEGIN OF TY_FINAL,
    DISPO     TYPE CHAR100,
    BRAND     TYPE CHAR100,
    KDAUF     TYPE CHAR100,
    KDPOS     TYPE CHAR100,
    VKBUR     TYPE CHAR100,
    MATNR     TYPE CHAR100,
    MAKTX     TYPE VBRP-ARKTX,
    LONG_TXT  TYPE CHAR100,
    DAUAT     TYPE CHAR100,
    NAME1     TYPE CHAR100,
    EDATU     TYPE CHAR11, "vbep-edatu,
    KWMENG    TYPE CHAR100,
    DELDATE   TYPE CHAR11, "vbap-deldate,
    KDMAT     TYPE CHAR100,
    AUFNR     TYPE CHAR100,
    MENGE     TYPE CHAR100,
    BUDAT_CON TYPE CHAR11, "mseg-budat_mkpf,
    BUDAT_IN  TYPE CHAR11, "mseg-budat_mkpf,
    PRD_AMT   TYPE CHAR100,
    NETPR     TYPE CHAR100,
    STPRS     TYPE CHAR100,
    ZSERIES   TYPE CHAR100,
    ZSIZE     TYPE CHAR3, "mara-zsize,
    MOC       TYPE CHAR100,
    TYPE      TYPE CHAR100,
    LGORT     TYPE CHAR100,
    AEDAT     TYPE CHAR11, "vbak-aedat,
    FTRMI     TYPE CHAR11, "afko-ftrmi,
    WAERK     TYPE CHAR100,
    KURSK     TYPE CHAR100,
    S_VAL     TYPE CHAR100,
    S_VAL_LC  TYPE CHAR100,
    AUART     TYPE CHAR100,
    SO_CURR   TYPE CHAR100,
*    werks     TYPE mseg-werks,
*    kunnr     TYPE mseg-kunnr,
*    stcd3     TYPE kna1-stcd3,
*    kzwi1     TYPE vbap-kzwi1,
    CURR_DATE TYPE CHAR11,
    FST_ISH   TYPE CHAR11,
    LST_ISH   TYPE CHAR11,
    DEL_DAT   TYPE CHAR11,
  END OF TY_FINAL.
*  tt_final TYPE STANDARD TABLE OF t_final.

DATA:
  GT_FINAL TYPE TT_FINAL,
  IT_FINAL TYPE TABLE OF TY_FINAL.

SELECTION-SCREEN:BEGIN OF BLOCK B1 WITH FRAME TITLE XYZ.
SELECT-OPTIONS: SO_BUDAT FOR TMP_BUDAT, "OBLIGATORY DEFAULT '20170401' TO SY-DATUM,
                SO_DAUAT FOR TMP_DAUAT NO INTERVALS,
                SO_KDAUF FOR TMP_KDAUF,
                SO_LGORT FOR TMP_LGORT NO INTERVALS,
                SO_MATNR FOR TMP_MAT.
SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE ABC .
PARAMETERS P_DOWN AS CHECKBOX.
PARAMETERS P_FOLDER TYPE RLGRAP-FILENAME DEFAULT '/Delval/Saudi'."Saudi'."Saudi'.  "'E:/delval/Saudi'
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN :BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-003.
  SELECTION-SCREEN  COMMENT /1(60) TEXT-004.
  SELECTION-SCREEN COMMENT /1(70) TEXT-005.
SELECTION-SCREEN: END OF BLOCK B3.

INITIALIZATION.
  XYZ = 'Select Options'(tt1).
  ABC = 'Download File'(tt2).

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FOLDER.

  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      PROGRAM_NAME  = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
*     FIELD_NAME    = ' '
    IMPORTING
      FILE_NAME     = P_FOLDER.

START-OF-SELECTION.
  PERFORM FETCH_DATA CHANGING GT_FINAL.
  PERFORM DISPLAY USING GT_FINAL.
*&---------------------------------------------------------------------*
*&      Form  FETCH_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      <--P_GT_FINAL  text
*----------------------------------------------------------------------*
FORM FETCH_DATA  CHANGING CT_FINAL TYPE TT_FINAL.
  DATA:
    LT_MAT_DOC        TYPE TT_MAT_DOC,
    LS_MAT_DOC        TYPE T_MAT_DOC,
    LT_MAT_DOC_101    TYPE TT_MAT_DOC,
    LS_MAT_DOC_101    TYPE T_MAT_DOC,
    LT_ORDER_ITEM     TYPE TT_ORDER_ITEM,
    LS_ORDER_ITEM     TYPE T_ORDER_ITEM,
    LT_SALES_ORD_HDR  TYPE TT_SALES_ORD_HDR,
    LS_SALES_ORD_HDR  TYPE T_SALES_ORD_HDR,
    LT_SALES_ORD_ITEM TYPE TT_SALES_ORD_ITEM,
    LS_SALES_ORD_ITEM TYPE T_SALES_ORD_ITEM,
    LT_MAT_MAST       TYPE TT_MAT_MAST,
    LS_MAT_MAST       TYPE T_MAT_MAST,
    LT_MAT_DESC       TYPE TT_MAT_DESC,
    LS_MAT_DESC       TYPE T_MAT_DESC,
    LT_VBEP           TYPE TT_VBEP,
    LS_VBEP           TYPE T_VBEP,
    LT_CUST_INFO      TYPE TT_CUST_INFO,
    LS_CUST_INFO      TYPE T_CUST_INFO,
    LT_MARC           TYPE TT_MARC,
    LS_MARC           TYPE T_MARC,
    LT_MBEW           TYPE TT_MBEW,
    LS_MBEW           TYPE T_MBEW,
    LT_QAMB           TYPE TT_QAMB,
    LS_QAMB           TYPE T_QAMB,
    LT_QALS           TYPE TT_QALS,
    LS_QALS           TYPE T_QALS,
    LT_ORDER_HDR      TYPE TT_ORDER_HDR,
    LS_ORDER_HDR      TYPE T_ORDER_HDR,
    LT_COEP           TYPE TT_COEP,
    LS_COEP           TYPE T_COEP,
    LT_VBKD           TYPE TT_VBKD,
    LS_VBKD           TYPE T_VBKD,
    LS_FINAL          TYPE T_FINAL,
    WA_FINAL          TYPE TY_FINAL,
    LT_AUFM           TYPE TT_AUFM,
    LS_AUFM           TYPE TY_AUFM.

  DATA:
    LV_ID        TYPE THEAD-TDNAME,
    LT_LINES     TYPE STANDARD TABLE OF TLINE,
    LS_LINES     TYPE TLINE,
    LV_INDEX     TYPE SY-TABIX,
    LV_COST      TYPE prcd_elements-KWERT,
    LS_EXCH_RATE TYPE BAPI1093_0.

  DATA :
    GV_CON_DAT TYPE MKPF-BUDAT,
    GV_FST_ISH TYPE MKPF-BUDAT,
    GV_LST_ISH TYPE MKPF-BUDAT.

  DATA : V_COST      TYPE prcd_elements-KWERT,
        V_INDEX     TYPE SY-TABIX.

  IF NOT SO_DAUAT IS INITIAL.
    SELECT AUFNR
           POSNR
           DAUAT
           PSMNG
           PWERK
      FROM AFPO
      INTO TABLE LT_ORDER_ITEM
      WHERE DAUAT IN SO_DAUAT
      AND PWERK = 'SU01'." ADDED BY MD

    IF NOT LT_ORDER_ITEM IS INITIAL.
      SELECT MBLNR
             MJAHR
             ZEILE
             BWART
             MATNR
             WERKS
             LGORT
             KUNNR
             KDAUF
             KDPOS
             WAERS
             MENGE
             AUFNR
             BUDAT_MKPF
        FROM MSEG
        INTO TABLE LT_MAT_DOC
        FOR ALL ENTRIES IN LT_ORDER_ITEM
        WHERE AUFNR = LT_ORDER_ITEM-AUFNR
        AND   BUDAT_MKPF IN SO_BUDAT
        AND   BWART = '321'
        AND   XAUTO = 'X'
        AND   MATNR IN SO_MATNR
        AND   LGORT IN SO_LGORT
        AND   KDAUF IN SO_KDAUF
        AND   WERKS = LT_ORDER_ITEM-PWERK." ADDED BY MD
    ENDIF.
  ELSE.
    SELECT MBLNR
           MJAHR
           ZEILE
           BWART
           MATNR
           WERKS
           LGORT
           KUNNR
           KDAUF
           KDPOS
           WAERS
           MENGE
           AUFNR
           BUDAT_MKPF
      FROM MSEG
      INTO TABLE LT_MAT_DOC
      WHERE BUDAT_MKPF IN SO_BUDAT
      AND   BWART = '321'
      AND   XAUTO = 'X'
      AND   MATNR IN SO_MATNR
      AND   LGORT IN SO_LGORT
      AND   KDAUF IN SO_KDAUF
      AND   AUFNR NE SPACE
      AND   WERKS = 'SU01'.  " ADDED BY MD


  ENDIF.
  IF LT_MAT_DOC IS INITIAL.
    MESSAGE 'Data Not Found' TYPE 'E'.
  ELSE.
    SELECT AUFNR
           POSNR
           DAUAT
           PSMNG
      FROM AFPO
      INTO TABLE LT_ORDER_ITEM
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE AUFNR = LT_MAT_DOC-AUFNR.

    IF NOT LT_ORDER_ITEM IS INITIAL.
      LOOP AT LT_ORDER_ITEM INTO LS_ORDER_ITEM.
        CONCATENATE 'OR' LS_ORDER_ITEM-AUFNR INTO LS_ORDER_ITEM-OBJNR.
        MODIFY LT_ORDER_ITEM FROM LS_ORDER_ITEM TRANSPORTING OBJNR.
      ENDLOOP.

      SELECT AUFNR
             FTRMI
        FROM AFKO
        INTO TABLE LT_ORDER_HDR
        FOR ALL ENTRIES IN LT_ORDER_ITEM
        WHERE AUFNR = LT_ORDER_ITEM-AUFNR.

      SELECT KOKRS
             BELNR
             BUZEI
             WTGBTR
             OBJNR
        FROM COEP
        INTO TABLE LT_COEP
        FOR ALL ENTRIES IN LT_ORDER_ITEM
        WHERE OBJNR = LT_ORDER_ITEM-OBJNR
        AND   BEKNZ = 'S'.
    ENDIF.
    SELECT VBELN
           AUDAT
           AUART
           VKBUR
           KNUMV
           KUNNR
           AEDAT
           WAERK
      FROM VBAK
      INTO TABLE LT_SALES_ORD_HDR
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE VBELN = LT_MAT_DOC-KDAUF.

    SELECT VBELN
           POSNR
           MATNR
           KDMAT
           KWMENG
           DELDATE
           KZWI1
      FROM VBAP
      INTO TABLE LT_SALES_ORD_ITEM
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE VBELN = LT_MAT_DOC-KDAUF
      AND   POSNR = LT_MAT_DOC-KDPOS.

    SELECT VBELN
           POSNR
           KURSK
      FROM VBKD
      INTO TABLE LT_VBKD
      FOR ALL ENTRIES IN LT_SALES_ORD_ITEM
      WHERE VBELN = LT_SALES_ORD_ITEM-VBELN.

    SELECT MATNR
           ZSERIES
           ZSIZE
           BRAND
           MOC
           TYPE
      FROM MARA
      INTO TABLE LT_MAT_MAST
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE MATNR = LT_MAT_DOC-MATNR.

    SELECT MATNR
           MAKTX
      FROM MAKT
      INTO TABLE LT_MAT_DESC
      FOR ALL ENTRIES IN LT_MAT_MAST
      WHERE MATNR = LT_MAT_MAST-MATNR
      AND   SPRAS = SY-LANGU.

    SELECT VBELN
           POSNR
           EDATU
      FROM VBEP
      INTO TABLE LT_VBEP
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE VBELN = LT_MAT_DOC-KDAUF
      AND   POSNR = LT_MAT_DOC-KDPOS.

    SELECT KUNNR
           NAME1
           STCD3
      FROM KNA1
      INTO TABLE LT_CUST_INFO
      FOR ALL ENTRIES IN LT_SALES_ORD_HDR
      WHERE KUNNR = LT_SALES_ORD_HDR-KUNNR.

    SELECT MATNR
           WERKS
           DISPO
      FROM MARC
      INTO TABLE LT_MARC
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE MATNR = LT_MAT_DOC-MATNR.

    SELECT MATNR
           BWKEY
           STPRS
      FROM MBEW
      INTO TABLE LT_MBEW
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE MATNR = LT_MAT_DOC-MATNR.

    SELECT PRUEFLOS
           TYP
           MBLNR
           MJAHR
           ZEILE
      FROM QAMB
      INTO TABLE LT_QAMB
      FOR ALL ENTRIES IN LT_MAT_DOC
      WHERE MBLNR = LT_MAT_DOC-MBLNR
      AND   MJAHR = LT_MAT_DOC-MJAHR.
*        AND   zeile = lt_mat_doc-zeile.

    IF NOT LT_QAMB IS INITIAL.

      SELECT PRUEFLOS
             AUFNR
             MJAHR
             MBLNR
        FROM QALS
        INTO TABLE LT_QALS
        FOR ALL ENTRIES IN LT_QAMB
        WHERE PRUEFLOS = LT_QAMB-PRUEFLOS.

      IF NOT LT_QALS IS INITIAL.
        SELECT MBLNR
           MJAHR
           ZEILE
           BWART
           MATNR
           WERKS
           LGORT
           KUNNR
           KDAUF
           KDPOS
           WAERS
           MENGE
           AUFNR
           BUDAT_MKPF
      FROM MSEG
      INTO TABLE LT_MAT_DOC_101
      FOR ALL ENTRIES IN LT_QALS
      WHERE MBLNR = LT_QALS-MBLNR
      AND   MJAHR = LT_QALS-MJAHR
      AND   AUFNR = LT_QALS-AUFNR
      AND   BWART = '101'.
      ENDIF.
    ENDIF.
  ENDIF.
  IF LT_MAT_DOC IS NOT INITIAL.

*    SELECT MBLNR
*           MJAHR
*           ZEILE
*           BWART
*           MATNR
*           WERKS
*           LGORT
*           KUNNR
*           KDAUF
*           KDPOS
*           WAERS
*           MENGE
*           AUFNR
*           BUDAT_MKPF FROM MSEG INTO TABLE IT_MSEG_261
*           FOR ALL ENTRIES IN LT_MAT_DOC
*           WHERE AUFNR = LT_MAT_DOC-AUFNR
*            AND  WERKS = LT_MAT_DOC-WERKS
*            AND  BWART = '261'.
    SELECT MBLNR
           MJAHR
           ZEILE
           BWART
           MATNR
           WERKS
           AUFNR
           BUDAT
           DMBTR " MODIFIED BY PJ
      FROM AUFM INTO TABLE LT_AUFM
    FOR ALL ENTRIES IN LT_MAT_DOC
    WHERE AUFNR = LT_MAT_DOC-AUFNR
    AND  WERKS  = LT_MAT_DOC-WERKS
    AND  BWART  = '261'.

  ENDIF.

  SORT LT_COEP BY OBJNR.
  LOOP AT LT_MAT_DOC INTO LS_MAT_DOC.
    LS_FINAL-KDAUF    = LS_MAT_DOC-KDAUF.
    LS_FINAL-KDPOS    = LS_MAT_DOC-KDPOS.
*    ls_final-waers    = ls_mat_doc-waers.
    LS_FINAL-AUFNR    = LS_MAT_DOC-AUFNR.

    IF NOT LS_MAT_DOC-BUDAT_MKPF IS INITIAL.

      CONCATENATE LS_MAT_DOC-BUDAT_MKPF+6(2) LS_MAT_DOC-BUDAT_MKPF+4(2) LS_MAT_DOC-BUDAT_MKPF+0(4)
              INTO LS_FINAL-BUDAT_IN SEPARATED BY '-'.
    ELSE.
      LS_FINAL-BUDAT_IN = 'NULL'.
    ENDIF.

*    SORT IT_MSEG_261 BY BUDAT_MKPF ASCENDING .
*    READ TABLE IT_MSEG_261 INTO WA_MSEG_261 WITH KEY AUFNR = LS_FINAL-AUFNR.
*    IF NOT WA_MSEG_261-BUDAT_MKPF IS INITIAL.
*      GV_FST_ISH = WA_MSEG_261-BUDAT_MKPF .
*      CONCATENATE WA_MSEG_261-BUDAT_MKPF+6(2) WA_MSEG_261-BUDAT_MKPF+4(2) WA_MSEG_261-BUDAT_MKPF+0(4)
*      INTO LS_FINAL-FST_ISH SEPARATED BY '-'.
*    ELSE.
*      LS_FINAL-FST_ISH = 'NULL'.
*    ENDIF.

    SORT LT_AUFM BY BUDAT ASCENDING .
    READ TABLE LT_AUFM INTO LS_AUFM WITH KEY AUFNR = LS_FINAL-AUFNR.
    IF NOT LS_AUFM-BUDAT IS INITIAL.
      GV_FST_ISH = LS_AUFM-BUDAT.
      CONCATENATE LS_AUFM-BUDAT+6(2) LS_AUFM-BUDAT+4(2) LS_AUFM-BUDAT+0(4)
      INTO LS_FINAL-FST_ISH SEPARATED BY '-'.
    ELSE.
      LS_FINAL-FST_ISH = 'NULL'.
    ENDIF.

*    SORT IT_MSEG_261 BY BUDAT_MKPF DESCENDING .
*    READ TABLE IT_MSEG_261 INTO WA_MSEG_261 WITH KEY AUFNR = LS_FINAL-AUFNR.
*    IF NOT WA_MSEG_261-BUDAT_MKPF IS INITIAL.
*      GV_LST_ISH = WA_MSEG_261-BUDAT_MKPF.
*      CONCATENATE WA_MSEG_261-BUDAT_MKPF+6(2) WA_MSEG_261-BUDAT_MKPF+4(2) WA_MSEG_261-BUDAT_MKPF+0(4)
*      INTO LS_FINAL-LST_ISH SEPARATED BY '-'.
*    ELSE.
*      LS_FINAL-LST_ISH = 'NULL'.
*    ENDIF.
    SORT LT_AUFM BY BUDAT DESCENDING .
    READ TABLE LT_AUFM INTO LS_AUFM WITH KEY AUFNR = LS_FINAL-AUFNR.
    IF NOT LS_AUFM-BUDAT IS INITIAL.
      GV_LST_ISH = LS_AUFM-BUDAT.
      CONCATENATE LS_AUFM-BUDAT+6(2) LS_AUFM-BUDAT+4(2) LS_AUFM-BUDAT+0(4)
      INTO LS_FINAL-LST_ISH SEPARATED BY '-'.
    ELSE.
      LS_FINAL-LST_ISH = 'NULL'.
    ENDIF.



    LS_FINAL-MATNR    = LS_MAT_DOC-MATNR.
*    ls_final-werks    = ls_mat_doc-werks.
    LS_FINAL-LGORT    = LS_MAT_DOC-LGORT.
*    ls_final-kunnr    = ls_mat_doc-kunnr.
    LS_FINAL-MENGE    = LS_MAT_DOC-MENGE.

    READ TABLE LT_MARC INTO LS_MARC WITH KEY MATNR = LS_MAT_DOC-MATNR
                                             WERKS = LS_MAT_DOC-WERKS.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-DISPO  = LS_MARC-DISPO.
    ENDIF.
    READ TABLE LT_ORDER_ITEM INTO LS_ORDER_ITEM WITH KEY AUFNR = LS_MAT_DOC-AUFNR.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-DAUAT  = LS_ORDER_ITEM-DAUAT.
    ENDIF.
    READ TABLE LT_COEP INTO LS_COEP WITH KEY OBJNR = LS_ORDER_ITEM-OBJNR.
    IF SY-SUBRC IS INITIAL.
      LV_INDEX = SY-TABIX.
      LOOP AT LT_COEP INTO LS_COEP FROM LV_INDEX.
        IF LS_COEP-OBJNR = LS_ORDER_ITEM-OBJNR .
          LV_COST = LV_COST + LS_COEP-WTGBTR.
        ELSE.
          EXIT.
        ENDIF.

      ENDLOOP.

    ENDIF.

******************************edited by PJ*******************************************
*       SORT LT_AUFM BY AUFNR ASCENDING .
       SORT LT_AUFM BY AUFNR DESCENDING .
*    READ TABLE LT_AUFM INTO LS_AUFM WITH KEY AUFNR = LS_FINAL-AUFNR.
*    IF SY-SUBRC = 0.
        IF LS_AUFM-AUFNR = LS_MAT_DOC-AUFNR.

      LOOP AT LT_AUFM INTO LS_AUFM WHERE AUFNR = LS_FINAL-AUFNR."FROM V_INDEX.
         V_INDEX = SY-TABIX.
        IF LS_AUFM-AUFNR = LS_MAT_DOC-AUFNR.
            V_COST = V_COST + LS_AUFM-DMBTR.
        ENDIF.

      ENDLOOP.



*            V_COST = V_COST + LS_AUFM-DMBTR.
*        ENDIF.
    ENDIF.





      LS_FINAL-PRD_AMT = V_COST.




*    LS_FINAL-PRD_AMT = ( LV_COST / LS_ORDER_ITEM-PSMNG )  * LS_FINAL-MENGE.


********************************end*******************************************

    READ TABLE LT_ORDER_HDR INTO LS_ORDER_HDR WITH KEY AUFNR = LS_ORDER_ITEM-AUFNR.
    IF SY-SUBRC IS INITIAL.

      IF NOT LS_ORDER_HDR-FTRMI IS INITIAL.

        CONCATENATE LS_ORDER_HDR-FTRMI+6(2) LS_ORDER_HDR-FTRMI+4(2) LS_ORDER_HDR-FTRMI+0(4)
                INTO LS_FINAL-FTRMI SEPARATED BY '-'.
      ELSE.
        LS_FINAL-FTRMI = 'NULL'.
      ENDIF.
    ELSE.
      LS_FINAL-FTRMI = 'NULL'.
    ENDIF.
    READ TABLE LT_SALES_ORD_ITEM INTO LS_SALES_ORD_ITEM WITH KEY VBELN = LS_MAT_DOC-KDAUF
                                                                 POSNR = LS_MAT_DOC-KDPOS.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-KDMAT   = LS_SALES_ORD_ITEM-KDMAT.
      LS_FINAL-KWMENG  = LS_SALES_ORD_ITEM-KWMENG.
      IF NOT LS_SALES_ORD_ITEM-DELDATE IS INITIAL.

        CONCATENATE LS_SALES_ORD_ITEM-DELDATE+6(2) LS_SALES_ORD_ITEM-DELDATE+4(2) LS_SALES_ORD_ITEM-DELDATE+0(4)
                INTO LS_FINAL-DELDATE SEPARATED BY '-'.
      ELSE.
        LS_FINAL-DELDATE = 'NULL'.
      ENDIF.

*      ls_final-kzwi1   = ls_sales_ord_item-kzwi1.
      LS_FINAL-NETPR   = LS_SALES_ORD_ITEM-KZWI1 / LS_SALES_ORD_ITEM-KWMENG.
      LS_FINAL-S_VAL = LS_FINAL-NETPR * LS_FINAL-MENGE.
    ELSE.
      LS_FINAL-DELDATE = 'NULL'.
*    ls_final-so_amt  =
    ENDIF.
    READ TABLE LT_VBKD INTO LS_VBKD WITH KEY VBELN = LS_SALES_ORD_ITEM-VBELN.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-SO_CURR    = LS_VBKD-KURSK.
    ENDIF.
    READ TABLE LT_SALES_ORD_HDR INTO LS_SALES_ORD_HDR WITH KEY VBELN = LS_SALES_ORD_ITEM-VBELN.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-WAERK   = LS_SALES_ORD_HDR-WAERK.
      LS_FINAL-VKBUR   = LS_SALES_ORD_HDR-VKBUR.
      LS_FINAL-AUART = LS_SALES_ORD_HDR-AUART.


      CALL FUNCTION 'BAPI_EXCHANGERATE_GETDETAIL'
        EXPORTING
          RATE_TYPE  = 'M'
          FROM_CURR  = LS_FINAL-WAERK
          TO_CURRNCY = 'SAR'
          DATE       = SY-DATUM
        IMPORTING
          EXCH_RATE  = LS_EXCH_RATE
*         RETURN     =
        .

      LS_FINAL-KURSK    = LS_EXCH_RATE-EXCH_RATE.
      LS_FINAL-S_VAL_LC = LS_FINAL-S_VAL * LS_EXCH_RATE-EXCH_RATE.


      IF NOT LS_SALES_ORD_HDR-AEDAT IS INITIAL.

        CONCATENATE LS_SALES_ORD_HDR-AEDAT+6(2) LS_SALES_ORD_HDR-AEDAT+4(2) LS_SALES_ORD_HDR-AEDAT+0(4)
                INTO LS_FINAL-AEDAT SEPARATED BY '-'.
      ELSE.
        LS_FINAL-AEDAT = 'NULL'.
      ENDIF.

    ELSE.
      LS_FINAL-AEDAT = 'NULL'.
    ENDIF.
    READ TABLE LT_VBEP INTO LS_VBEP WITH KEY VBELN = LS_MAT_DOC-KDAUF
                                             POSNR = LS_MAT_DOC-KDPOS.
    IF SY-SUBRC IS INITIAL.
      IF NOT LS_VBEP-EDATU IS INITIAL.

        CONCATENATE LS_VBEP-EDATU+6(2) LS_VBEP-EDATU+4(2) LS_VBEP-EDATU+0(4)
                INTO LS_FINAL-EDATU SEPARATED BY '-'.
      ELSE.
        LS_FINAL-EDATU = 'NULL'.
      ENDIF.
    ELSE.
      LS_FINAL-EDATU = 'NULL'.
    ENDIF.
    READ TABLE LT_CUST_INFO INTO LS_CUST_INFO WITH KEY KUNNR = LS_SALES_ORD_HDR-KUNNR.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-NAME1 = LS_CUST_INFO-NAME1.
*      ls_final-stcd3 = ls_cust_info-stcd3.
    ENDIF.
    READ TABLE LT_MAT_MAST INTO LS_MAT_MAST WITH KEY MATNR = LS_FINAL-MATNR.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-ZSERIES = LS_MAT_MAST-ZSERIES.
      LS_FINAL-ZSIZE   = LS_MAT_MAST-ZSIZE.
      LS_FINAL-BRAND   = LS_MAT_MAST-BRAND.
      LS_FINAL-MOC     = LS_MAT_MAST-MOC.
      LS_FINAL-TYPE    = LS_MAT_MAST-TYPE.
    ENDIF.
    READ TABLE LT_MAT_DESC INTO LS_MAT_DESC WITH KEY MATNR = LS_FINAL-MATNR.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-MAKTX   = LS_MAT_DESC-MAKTX.

    ENDIF.
    READ TABLE LT_MBEW INTO LS_MBEW WITH KEY MATNR = LS_FINAL-MATNR.
    IF SY-SUBRC IS INITIAL.
      LS_FINAL-STPRS   = LS_MBEW-STPRS.
    ENDIF.
    READ TABLE LT_QAMB INTO LS_QAMB WITH KEY MBLNR = LS_MAT_DOC-MBLNR
                                             MJAHR = LS_MAT_DOC-MJAHR.
    IF SY-SUBRC IS INITIAL.
      READ TABLE LT_QALS INTO LS_QALS WITH KEY PRUEFLOS = LS_QAMB-PRUEFLOS.
      IF SY-SUBRC IS INITIAL.
        READ TABLE LT_MAT_DOC_101 INTO LS_MAT_DOC_101 WITH KEY MBLNR = LS_QALS-MBLNR
                                                               MJAHR = LS_QALS-MJAHR.
        IF SY-SUBRC IS INITIAL.
          IF NOT LS_MAT_DOC_101-BUDAT_MKPF IS INITIAL.
            GV_CON_DAT = LS_MAT_DOC_101-BUDAT_MKPF.
            CONCATENATE LS_MAT_DOC_101-BUDAT_MKPF+6(2) LS_MAT_DOC_101-BUDAT_MKPF+4(2) LS_MAT_DOC_101-BUDAT_MKPF+0(4)
                    INTO LS_FINAL-BUDAT_CON SEPARATED BY '-'.
          ELSE.
            LS_FINAL-BUDAT_CON = 'NULL'.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.

    LS_FINAL-DEL_DAT = GV_CON_DAT - GV_LST_ISH .

    "Material Long Text
    LV_ID = LS_FINAL-MATNR.
    CLEAR: LT_LINES,LS_LINES.
    CALL FUNCTION 'READ_TEXT'
      EXPORTING
        CLIENT                  = SY-MANDT
        ID                      = 'GRUN'
        LANGUAGE                = SY-LANGU
        NAME                    = LV_ID
        OBJECT                  = 'MATERIAL'
      TABLES
        LINES                   = LT_LINES
      EXCEPTIONS
        ID                      = 1
        LANGUAGE                = 2
        NAME                    = 3
        NOT_FOUND               = 4
        OBJECT                  = 5
        REFERENCE_CHECK         = 6
        WRONG_ACCESS_TO_ARCHIVE = 7
        OTHERS                  = 8.
    IF SY-SUBRC <> 0.
* Implement suitable error handling here
    ENDIF.
    IF NOT LT_LINES IS INITIAL.
      LOOP AT LT_LINES INTO LS_LINES.
        IF NOT LS_LINES-TDLINE IS INITIAL.
          CONCATENATE LS_FINAL-LONG_TXT LS_LINES-TDLINE INTO LS_FINAL-LONG_TXT SEPARATED BY SPACE.
        ENDIF.
      ENDLOOP.
      CONDENSE LS_FINAL-LONG_TXT.
    ENDIF.
    LS_FINAL-CURR_DATE = SY-DATUM.
*BREAK PRIMUS.

***************************************************new file download******************************


    IF LS_VBEP-EDATU IS NOT INITIAL.

      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_VBEP-EDATU
        IMPORTING
          OUTPUT = WA_FINAL-EDATU.
      CONCATENATE WA_FINAL-EDATU+0(2) WA_FINAL-EDATU+2(3) WA_FINAL-EDATU+5(4)
                      INTO WA_FINAL-EDATU SEPARATED BY '-'.
*CONCATENATE WA_FINAL-EDATU

    ENDIF.

    IF LS_SALES_ORD_ITEM-DELDATE IS NOT INITIAL.


      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_SALES_ORD_ITEM-DELDATE
        IMPORTING
          OUTPUT = WA_FINAL-DELDATE.
      CONCATENATE WA_FINAL-DELDATE+0(2) WA_FINAL-DELDATE+2(3) WA_FINAL-DELDATE+5(4)
                      INTO WA_FINAL-DELDATE SEPARATED BY '-'.
    ENDIF.

    IF LS_MAT_DOC_101-BUDAT_MKPF IS NOT INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_MAT_DOC_101-BUDAT_MKPF
        IMPORTING
          OUTPUT = WA_FINAL-BUDAT_CON.

      CONCATENATE WA_FINAL-BUDAT_CON+0(2) WA_FINAL-BUDAT_CON+2(3) WA_FINAL-BUDAT_CON+5(4)
                      INTO WA_FINAL-BUDAT_CON SEPARATED BY '-'.
    ENDIF.

    IF LS_MAT_DOC-BUDAT_MKPF IS NOT INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_MAT_DOC-BUDAT_MKPF
        IMPORTING
          OUTPUT = WA_FINAL-BUDAT_IN.

      CONCATENATE WA_FINAL-BUDAT_IN+0(2) WA_FINAL-BUDAT_IN+2(3) WA_FINAL-BUDAT_IN+5(4)
                      INTO WA_FINAL-BUDAT_IN SEPARATED BY '-'.

    ENDIF.
*break primus.
    IF LS_SALES_ORD_HDR-AEDAT IS NOT INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_SALES_ORD_HDR-AEDAT
        IMPORTING
          OUTPUT = WA_FINAL-AEDAT.

      CONCATENATE WA_FINAL-AEDAT+0(2) WA_FINAL-AEDAT+2(3) WA_FINAL-AEDAT+5(4)
                      INTO WA_FINAL-AEDAT SEPARATED BY '-'.
    ENDIF.

    IF LS_ORDER_HDR-FTRMI IS NOT INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_ORDER_HDR-FTRMI
        IMPORTING
          OUTPUT = WA_FINAL-FTRMI.

      CONCATENATE WA_FINAL-FTRMI+0(2) WA_FINAL-FTRMI+2(3) WA_FINAL-FTRMI+5(4)
                      INTO WA_FINAL-FTRMI SEPARATED BY '-'.

    ENDIF.


    IF LS_FINAL-CURR_DATE IS NOT INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_FINAL-CURR_DATE
        IMPORTING
          OUTPUT = WA_FINAL-CURR_DATE.

      CONCATENATE WA_FINAL-CURR_DATE+0(2) WA_FINAL-CURR_DATE+2(3) WA_FINAL-CURR_DATE+5(4)
                      INTO WA_FINAL-CURR_DATE SEPARATED BY '-'.

    ENDIF.

    WA_FINAL-DISPO = LS_FINAL-DISPO.

    WA_FINAL-BRAND = LS_FINAL-BRAND.

    WA_FINAL-KDAUF = LS_FINAL-KDAUF.

    WA_FINAL-KDPOS = LS_FINAL-KDPOS.

    WA_FINAL-AUART = LS_FINAL-AUART.

    WA_FINAL-VKBUR = LS_FINAL-VKBUR.

    WA_FINAL-MATNR = LS_FINAL-MATNR.

    WA_FINAL-PRD_AMT = LS_FINAL-PRD_AMT.

    WA_FINAL-NETPR = LS_FINAL-NETPR.

    WA_FINAL-STPRS = LS_FINAL-STPRS.

    WA_FINAL-S_VAL = LS_FINAL-S_VAL.

    WA_FINAL-S_VAL_LC = LS_FINAL-S_VAL_LC.

    WA_FINAL-MAKTX = LS_FINAL-MAKTX.

    WA_FINAL-LONG_TXT = LS_FINAL-LONG_TXT.

    WA_FINAL-DAUAT = LS_FINAL-DAUAT.

    WA_FINAL-NAME1 = LS_FINAL-NAME1.

    WA_FINAL-KWMENG = LS_FINAL-KWMENG.

    WA_FINAL-KDMAT = LS_FINAL-KDMAT.

    WA_FINAL-AUFNR = LS_FINAL-AUFNR.

    WA_FINAL-MENGE = LS_FINAL-MENGE.

    WA_FINAL-WAERK = LS_FINAL-WAERK.

    WA_FINAL-SO_CURR = LS_FINAL-SO_CURR.

    WA_FINAL-KURSK = LS_FINAL-KURSK.

    WA_FINAL-ZSERIES = LS_FINAL-ZSERIES.

    WA_FINAL-ZSIZE = LS_FINAL-ZSIZE.

    WA_FINAL-TYPE = LS_FINAL-TYPE.

    WA_FINAL-MOC = LS_FINAL-MOC.

    WA_FINAL-LGORT = LS_FINAL-LGORT.
*********ADDED BY SNEHAL*****
*WA_FINAL-FST_ISH = LS_FINAL-FST_ISH.

    IF GV_FST_ISH IS NOT INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = GV_FST_ISH
        IMPORTING
          OUTPUT = WA_FINAL-FST_ISH.

      CONCATENATE WA_FINAL-FST_ISH+0(2) WA_FINAL-FST_ISH+2(3) WA_FINAL-FST_ISH+5(4)
                      INTO WA_FINAL-FST_ISH SEPARATED BY '-'.
    ENDIF.

    IF GV_LST_ISH IS NOT INITIAL.
      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = GV_LST_ISH
        IMPORTING
          OUTPUT = WA_FINAL-LST_ISH.

      CONCATENATE WA_FINAL-LST_ISH+0(2) WA_FINAL-LST_ISH+2(3) WA_FINAL-LST_ISH+5(4)
                      INTO WA_FINAL-LST_ISH SEPARATED BY '-'.
    ENDIF.

*WA_FINAL-LST_ISH = LS_FINAL-LST_ISH.

    WA_FINAL-DEL_DAT = LS_FINAL-DEL_DAT.
  CONDENSE WA_FINAL-DEL_DAT.
*   IF WA_FINAL-DEL_DAT < 0.
*      CONCATENATE '-' WA_FINAL-DEL_DAT INTO WA_FINAL-DEL_DAT.
*    ENDIF.
*break primus.
CALL FUNCTION 'CLOI_PUT_SIGN_IN_FRONT'
  CHANGING
    VALUE         = WA_FINAL-DEL_DAT
          .




********************************
    APPEND WA_FINAL TO IT_FINAL.

    APPEND LS_FINAL TO CT_FINAL.
    CLEAR: LS_FINAL,LS_MAT_DOC,LS_MAT_DOC_101,LS_QALS,LS_QAMB,LS_MBEW,LS_MAT_MAST,LS_CUST_INFO,LS_VBEP,LS_SALES_ORD_HDR,LS_SALES_ORD_ITEM,
           LS_ORDER_ITEM,LS_ORDER_HDR,LS_COEP,LS_VBKD,LV_COST,GV_LST_ISH,GV_CON_DAT,GV_FST_ISH,WA_FINAL.
    CLEAR : V_COST,V_COST. "edited by PJ
  ENDLOOP.

  SORT CT_FINAL BY AUFNR.
*  APPEND LINES OF CT_FINAL TO IT_FINAL.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  DISPLAY
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_GT_FINAL  text
*----------------------------------------------------------------------*
FORM DISPLAY  USING    CT_FINAL TYPE TT_FINAL.
  DATA:
    LT_FIELDCAT     TYPE SLIS_T_FIELDCAT_ALV,
    LS_ALV_LAYOUT   TYPE SLIS_LAYOUT_ALV,
    L_CALLBACK_PROG TYPE SY-REPID.

  L_CALLBACK_PROG = SY-REPID.


  PERFORM PREPARE_DISPLAY CHANGING LT_FIELDCAT.
  CLEAR LS_ALV_LAYOUT.
  LS_ALV_LAYOUT-ZEBRA = 'X'.
  LS_ALV_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM      = L_CALLBACK_PROG
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'UCOMM_ON_ALV'
*     I_CALLBACK_TOP_OF_PAGE  = ' '
      IS_LAYOUT               = LS_ALV_LAYOUT
      IT_FIELDCAT             = LT_FIELDCAT
    TABLES
      T_OUTTAB                = CT_FINAL
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  IF P_DOWN = 'X'.
    PERFORM DOWNLOAD.
  ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  PREPARE_DISPLAY
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      <--P_LT_FIELDCAT  text
*----------------------------------------------------------------------*
FORM PREPARE_DISPLAY  CHANGING CT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
  DATA:
    GV_POS      TYPE I,
    LS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

  REFRESH CT_FIELDCAT.
  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'DISPO'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'MRP Controller'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'BRAND'.
*  ls_fieldcat-outputlen = '8'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Brand'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'KDAUF'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Sales Order No.'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'KDPOS'.
*  ls_fieldcat-outputlen = '10'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Line Item'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'AUART'.
*  ls_fieldcat-outputlen = '10'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Order Type'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.
  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'VKBUR'.
*  ls_fieldcat-outputlen = '12'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Sales Office'."(104).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'MATNR'.
*  ls_fieldcat-outputlen = '18'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Material No.'."(105).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'MAKTX'.
*  ls_fieldcat-outputlen = '40'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Item Description'."(106).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'LONG_TXT'.
*  ls_fieldcat-outputlen = '40'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Long Description'."(127).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.
  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'DAUAT'.
*  ls_fieldcat-outputlen = '21'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Production Order Type'."(107).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.


  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'NAME1'.
*  ls_fieldcat-outputlen = '30'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Customer Name'."(125).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'EDATU'.
*  ls_fieldcat-outputlen = '10'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Production Date'."(126).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'KWMENG'.
*  ls_fieldcat-outputlen = '7'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'SO QTY.'."(108).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'DELDATE'.
*  ls_fieldcat-outputlen = '13'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Delivery Date'."(109).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'KDMAT'.
*  ls_fieldcat-outputlen = '18'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Customer Item Code'."(110).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'AUFNR'.
*  ls_fieldcat-outputlen = '20'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Production Order No.'."(111).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'MENGE'.
*  ls_fieldcat-outputlen = '10'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'QTY.'."(112).
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'BUDAT_CON'.
*  ls_fieldcat-outputlen = '17'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Confirmation Date'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'FST_ISH'.
*  ls_fieldcat-outputlen = '17'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'First Issue Date'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'LST_ISH'.
*  ls_fieldcat-outputlen = '17'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Last Issue Date'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'DEL_DAT'.
*  ls_fieldcat-outputlen = '17'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Delayed Days'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'BUDAT_IN'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Inspection Date'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'PRD_AMT'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Production Amt.'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'S_VAL'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Sales Value(DC)'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'WAERK'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Currency'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'SO_CURR'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'SO Exchange Rate'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'KURSK'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Current Exchange Rate'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.
  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'S_VAL_LC'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Sales Value(LC)'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'NETPR'.
*  ls_fieldcat-outputlen = '8'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Rate'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'STPRS'.
*  ls_fieldcat-outputlen = '13'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Standard Cost'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'ZSERIES'.
*  ls_fieldcat-outputlen = '10'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Series'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'ZSIZE'.
*  ls_fieldcat-outputlen = '8'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Size'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'MOC'.
*  ls_fieldcat-outputlen = '8'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'MOC'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'TYPE'.
*  ls_fieldcat-outputlen = '10'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Type'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'LGORT'.
*  ls_fieldcat-outputlen = '12'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Storage Loc.'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'AEDAT'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'MRP Date'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'FTRMI'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'Order Create Date'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

  GV_POS = GV_POS + 1.
  LS_FIELDCAT-FIELDNAME = 'CURR_DATE'.
*  ls_fieldcat-outputlen = '15'.
  LS_FIELDCAT-TABNAME   = 'GT_FINAL'.
  LS_FIELDCAT-SELTEXT_M = 'File Create Date'.
  LS_FIELDCAT-COL_POS   = GV_POS.
*  ls_fieldcat-hotspot   = 'X'.
  APPEND LS_FIELDCAT TO CT_FIELDCAT.
  CLEAR LS_FIELDCAT.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  DOWNLOAD
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DOWNLOAD .
  TYPE-POOLS TRUXS.
  DATA: IT_CSV TYPE TRUXS_T_TEXT_DATA,
        WA_CSV TYPE LINE OF TRUXS_T_TEXT_DATA,
        HD_CSV TYPE LINE OF TRUXS_T_TEXT_DATA.

*  DATA: lv_folder(150).
  DATA: LV_FILE(30).
  DATA: LV_FULLFILE TYPE STRING,
        LV_DAT(10),
        LV_TIM(4).
  DATA: LV_MSG(80).

  CALL FUNCTION 'SAP_CONVERT_TO_TXT_FORMAT'
*   EXPORTING
*     I_FIELD_SEPERATOR          =
*     I_LINE_HEADER              =
*     I_FILENAME                 =
*     I_APPL_KEEP                = ' '
    TABLES
      I_TAB_SAP_DATA       = GT_FINAL
    CHANGING
      I_TAB_CONVERTED_DATA = IT_CSV
    EXCEPTIONS
      CONVERSION_FAILED    = 1
      OTHERS               = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  PERFORM CVS_HEADER USING HD_CSV.

*  lv_folder = 'D:\usr\sap\DEV\D00\work'.
  LV_FILE = 'ZSU_PRD.TXT'.

*  CONCATENATE P_FOLDER '\' SY-DATUM SY-UZEIT LV_FILE
  CONCATENATE P_FOLDER '/' SY-DATUM SY-UZEIT LV_FILE
    INTO LV_FULLFILE.

  WRITE: / 'ZSU_PRD Download started on', SY-DATUM, 'at', SY-UZEIT.
  OPEN DATASET LV_FULLFILE
    FOR OUTPUT IN TEXT MODE ENCODING DEFAULT.  "NON-UNICODE.
  IF SY-SUBRC = 0.
DATA lv_string_1645 TYPE string.
DATA lv_crlf_1645 TYPE string.
lv_crlf_1645 = cl_abap_char_utilities=>cr_lf.
lv_string_1645 = hd_csv.
LOOP AT it_csv INTO wa_csv.
CONCATENATE lv_string_1645 lv_crlf_1645 wa_csv INTO lv_string_1645.
  CLEAR: wa_csv.
ENDLOOP.
TRANSFER lv_string_1645 TO lv_fullfile.
    CONCATENATE 'File' LV_FULLFILE 'downloaded' INTO LV_MSG SEPARATED BY SPACE.
    MESSAGE LV_MSG TYPE 'S'.
  ENDIF.

*************************************************SECOND FILE ***************************************


  CALL FUNCTION 'SAP_CONVERT_TO_TXT_FORMAT'
*   EXPORTING
*     I_FIELD_SEPERATOR          =
*     I_LINE_HEADER              =
*     I_FILENAME                 =
*     I_APPL_KEEP                = ' '
    TABLES
      I_TAB_SAP_DATA       = IT_FINAL
    CHANGING
      I_TAB_CONVERTED_DATA = IT_CSV
    EXCEPTIONS
      CONVERSION_FAILED    = 1
      OTHERS               = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  PERFORM CVS_HEADER USING HD_CSV.

*  lv_folder = 'D:\usr\sap\DEV\D00\work'.
  LV_FILE = 'ZSU_PRDCOPY.TXT'.

*  CONCATENATE P_FOLDER '\' LV_FILE
  CONCATENATE P_FOLDER '/' LV_FILE
    INTO LV_FULLFILE.

  WRITE: / 'ZSU_PRD Download started on', SY-DATUM, 'at', SY-UZEIT.
  OPEN DATASET LV_FULLFILE
    FOR OUTPUT IN TEXT MODE ENCODING DEFAULT.  "NON-UNICODE.
  IF SY-SUBRC = 0.
DATA lv_string_1683 TYPE string.
DATA lv_crlf_1683 TYPE string.
lv_crlf_1683 = cl_abap_char_utilities=>cr_lf.
lv_string_1683 = hd_csv.
LOOP AT it_csv INTO wa_csv.
CONCATENATE lv_string_1683 lv_crlf_1683 wa_csv INTO lv_string_1683.
  CLEAR: wa_csv.
ENDLOOP.
TRANSFER lv_string_1683 TO lv_fullfile.
    CONCATENATE 'File' LV_FULLFILE 'downloaded' INTO LV_MSG SEPARATED BY SPACE.
    MESSAGE LV_MSG TYPE 'S'.
  ENDIF.


ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  CVS_HEADER
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_HD_CSV  text
*----------------------------------------------------------------------*
FORM CVS_HEADER  USING    PD_CSV.
  DATA: L_FIELD_SEPERATOR.
  L_FIELD_SEPERATOR = CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
  CONCATENATE 'MRP Controller'
              'Brand'
              'Sales Order No.'
              'Line Item'
              'Sales Office'
              'Material No.'
              'Item Description'
              'Long Description'
              'Production Order Type'
              'Customer Name'
              'Production Date'
              'SO QTY.'
              'Delivery Date'
              'Customer Item Code'
              'Production Order No.'
              'QTY.'
              'Confirmation Date'
              'Inspection Date'
              'Production Amt.'
              'Rate'
              'Standard Cost'
              'Series'
              'Size'
              'MOC'
              'Type'
              'Storage Loc.'
              'MRP Date'
              'Order Release Date'
              'Currency'
              'Current Exchange Rate'
              'Sales Value(DC)'
              'Sales Value(LC)'
              'Sales Order Type'
              'SO Exchange Rate'
              'FILE CREATED DATE'
              'First Issue Date'
              'Last Issue Date'
              'Delayed Days'
              INTO PD_CSV
              SEPARATED BY L_FIELD_SEPERATOR.

ENDFORM.
