*&---------------------------------------------------------------------*
*&  Include           ZSD_PENDING_SO_SELSCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
SELECT-OPTIONS   :  S_DATE FOR  WA_VBAK-ERDAT OBLIGATORY ,
                    S_MATNR FOR WA_VBAP-MATNR,
                    S_KUNNR FOR WA_VBAK-KUNNR,
                    S_VBELN FOR WA_VBAP-VBELN.
SELECTION-SCREEN END OF BLOCK B2.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-002.
PARAMETERS OPEN_SO  RADIOBUTTON GROUP CODE DEFAULT 'X' USER-COMMAND CODEGEN.
PARAMETERS ALL_SO  RADIOBUTTON GROUP CODE.
SELECTION-SCREEN END OF BLOCK B3.

SELECT-OPTIONS:  S_KSCHL   FOR  WA_KONV-KSCHL NO-DISPLAY .
SELECT-OPTIONS:  S_STAT   FOR  WA_JEST1-STAT NO-DISPLAY .

SELECTION-SCREEN BEGIN OF BLOCK B5 WITH FRAME TITLE TEXT-074 .
PARAMETERS P_DOWN AS CHECKBOX.
PARAMETERS P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/Delval/Saudi'. "'E:\delval\Saudi'.
SELECTION-SCREEN END OF BLOCK B5.

SELECTION-SCREEN :BEGIN OF BLOCK B4 WITH FRAME TITLE TEXT-075.
SELECTION-SCREEN  COMMENT /1(60) TEXT-076.
SELECTION-SCREEN COMMENT /1(70) TEXT-077.
SELECTION-SCREEN COMMENT /1(70) TEXT-078.
SELECTION-SCREEN COMMENT /1(70) TEXT-079.
SELECTION-SCREEN: END OF BLOCK B4.


DATA WA_KSCHL LIKE S_KSCHL.
DATA WA_JEST LIKE S_STAT.
CLEAR: WA_KSCHL , WA_JEST.




WA_KSCHL-SIGN = 'I'.
WA_KSCHL-OPTION = 'EQ'.
WA_KSCHL-LOW = 'ZPRO'.
APPEND WA_KSCHL TO S_KSCHL.

WA_KSCHL-SIGN = 'I'.
WA_KSCHL-OPTION = 'EQ'.
WA_KSCHL-LOW = 'VPRS'.
APPEND WA_KSCHL TO S_KSCHL.

WA_JEST-SIGN = 'I'.
WA_JEST-OPTION = 'EQ'.
WA_JEST-LOW = 'E0001'.
APPEND WA_JEST TO S_STAT.

WA_JEST-SIGN = 'I'.
WA_JEST-OPTION = 'EQ'.
WA_JEST-LOW = 'E0002'.
APPEND WA_JEST TO S_STAT.

WA_JEST-SIGN = 'I'.
WA_JEST-OPTION = 'EQ'.
WA_JEST-LOW = 'E0003'.
APPEND WA_JEST TO S_STAT.
