*&---------------------------------------------------------------------*
*&  Include           ZSU_DELIVERY_CHALLAN_SS
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK ORG WITH FRAME TITLE TEXT-001.
PARAMETERS: P_BUKRS TYPE  BUKRS OBLIGATORY  DEFAULT 'SU00' MODIF ID BU.
SELECT-OPTIONS: S_WERKS FOR T001W-WERKS OBLIGATORY NO INTERVALS DEFAULT 'SU01' MODIF ID BU,
                S_LIFNR FOR LFA1-LIFNR NO INTERVALS.



SELECTION-SCREEN  END OF BLOCK ORG.


SELECTION-SCREEN BEGIN OF BLOCK SEL WITH FRAME TITLE TEXT-002.
SELECT-OPTIONS:S_MBLNR FOR MKPF-MBLNR ,
               S_DATE  FOR MKPF-BUDAT.

SELECTION-SCREEN  END OF BLOCK SEL.



SELECTION-SCREEN BEGIN OF BLOCK OPT WITH FRAME TITLE TEXT-003.
PARAMETERS: MOD_CRE TYPE C AS CHECKBOX.

SELECTION-SCREEN  END OF BLOCK OPT.



AT SELECTION-SCREEN OUTPUT.
LOOP AT SCREEN.
  IF SCREEN-GROUP1 = 'BU'.
    SCREEN-INPUT = '0'.
    MODIFY SCREEN.
  ENDIF.
ENDLOOP.


START-OF-SELECTION.

*  PERFORM GET_DATA.
*  PERFORM PROCESS_DATA.
*  if mod_cre is initial.
*  PERFORM DISPLAY_DATA.
*  endif.
