*&---------------------------------------------------------------------*
*&  Include           ZSU_SALES_ORDER_CONFIRM_SS
*&---------------------------------------------------------------------*


SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
*SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : P_VBELN TYPE VBAK-VBELN.
PARAMETERS : P_TEXT TYPE ZSU_HEADING-ztext  MATCHCODE OBJECT ZSU_HEADING.
PARAMETERS  text1 TYPE char255.
*SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1.

*
if text1 is NOT INITIAL.
   EXPORT TEXT1 TO MEMORY ID 'SER'.
   SUBMIT ZORD_CONF_UAE_CUST_REQ WITH P_VBELN EQ P_VBELN.
ENDIF.
if p_text is NOT INITIAL.
   EXPORT P_text TO MEMORY ID 'SER1'.
   SUBMIT ZORD_CONF_UAE_CUST_REQ WITH P_VBELN EQ P_VBELN.
ENDIF.
