

TYPES : BEGIN OF TY_BSAK,
          BUKRS TYPE BSAK-BUKRS,
          LIFNR TYPE BSAK-LIFNR,
          AUGBL TYPE BSAK-AUGBL,
          GJAHR TYPE BSAK-GJAHR,
          BELNR TYPE BSAK-BELNR,
          BLART TYPE BSAK-BLART,
          DMBTR TYPE BSAK-DMBTR,
          BUDAT TYPE BSAK-BUDAT,
          WRBTR TYPE BSAK-WRBTR,
        END OF TY_BSAK.

TYPES : BEGIN OF TY_BSIK,
          BUKRS TYPE BSIK-BUKRS,
          BELNR TYPE BSIK-BELNR,
          GJAHR TYPE BSIK-GJAHR,
          BUDAT TYPE BSIK-BUDAT,
          DMBTR TYPE BSIK-DMBTR,
          AUGBL TYPE BSIK-AUGBL,
          BLART TYPE BSIK-BLART,
          REBZG TYPE BSIK-REBZG,
          WRBTR TYPE BSAK-WRBTR,
        END OF TY_BSIK.

        TYPES : BEGIN OF TY_BSIK_N,
        BUKRS TYPE  BSIK-BUKRS,
        BELNR TYPE  BSIK-BELNR,
        GJAHR TYPE  BSIK-GJAHR,
        BUDAT TYPE  BSIK-BUDAT,
        DMBTR TYPE  BSIK-DMBTR,
        AUGBL TYPE  BSIK-AUGBL,
        BLART TYPE  BSIK-BLART,
        REBZG TYPE  BSIK-REBZG,
        WRBTR TYPE BSAK-WRBTR,
        XBLNR TYPE BSIK-XBLNR,
                END OF TY_BSIK_N.

TYPES : BEGIN OF TY_BSIK1,
          BUKRS TYPE BSIK-BUKRS,
          BELNR TYPE BSIK-BELNR,
          GJAHR TYPE BSIK-GJAHR,
          BUDAT TYPE BSIK-BUDAT,
          DMBTR TYPE BSIK-DMBTR,
          AUGBL TYPE BSIK-AUGBL,
          BLART TYPE BSIK-BLART,
          REBZG TYPE BSIK-REBZG,
          WRBTR TYPE BSAK-WRBTR,
        END OF TY_BSIK1.

        TYPES : BEGIN Of ty_sum,
                BUKRS TYPE BSEG-BUKRS,
                BELNR TYPE BSEG-BELNR,
                GJAHR TYPE BSEG-GJAHR,
                DMBTR TYPE BSEG-DMBTR,
                ZTERM TYPE BSEG-ZTERM,
                ZFBDT TYPE BSEG-ZFBDT,
                END OF ty_sum.

    TYPES : BEGIN OF TY_FINAL1,
            BELNR TYPE BSEG-BELNR,
            ZFBDT TYPE BSEG-ZFBDT,
            DMBTR TYPE BSEG-DMBTR,
            GV_sum1 TYPE BSEG-DMBTR,
            XBLNR TYPE BSIK-XBLNR,
            END OF TY_FINAL1.
