*&---------------------------------------------------------------------*
*&  Include           ZSU_FI_PAYMENT_VOUCHER_DEC
*&---------------------------------------------------------------------*

TABLES : BKPF,BSEG.

TYPES : BEGIN OF TY_BKPF,
          BUKRS TYPE BKPF-BUKRS,
          BELNR TYPE BKPF-BELNR,
          GJAHR TYPE BKPF-GJAHR,
          BLART TYPE BKPF-BLART,
          BLDAT TYPE BKPF-BLDAT,
          BUDAT TYPE BKPF-BUDAT,
          XBLNR TYPE BKPF-XBLNR,
          USNAM TYPE BKPF-USNAM,
          WAERS TYPE BKPF-WAERS,
          HWAER TYPE BKPF-HWAER,
        END OF TY_BKPF.

DATA : IT_BKPF TYPE TABLE OF  TY_BKPF,
       WA_BKPF TYPE TY_BKPF.

TYPES : BEGIN OF TY_BSEG,
          BUKRS TYPE BSEG-BUKRS,
          BELNR TYPE BSEG-BELNR,
          GJAHR TYPE BSEG-GJAHR,
          BUZEI TYPE BSEG-BUZEI,
          BUZID TYPE BSEG-BUZID,
          AUGBL TYPE BSEG-AUGBL,
          KOART TYPE BSEG-KOART,
          LIFNR TYPE BSEG-LIFNR,
          ZLSCH TYPE BSEG-ZLSCH,
          DMBTR TYPE BSEG-DMBTR,
          WRBTR TYPE BSEG-WRBTR,
          SGTXT TYPE BSEG-SGTXT,
        END OF TY_BSEG.

DATA   : IT_BSEG TYPE TABLE OF TY_BSEG,
         WA_BSEG TYPE TY_BSEG.

TYPES : BEGIN OF TY_LFA1,
          LIFNR TYPE LFA1-LIFNR,
          LAND1 TYPE LFA1-LAND1,
          NAME1 TYPE LFA1-NAME1,
          ORT01 TYPE LFA1-ORT01,
          STRAS TYPE LFA1-STRAS,
          PSTLZ TYPE LFA1-PSTLZ,
        END OF TY_LFA1.

DATA : IT_LFA1 TYPE TABLE OF TY_LFA1,
       WA_LFA1 TYPE TY_LFA1.

TYPES : BEGIN OF TY_T042Z,
          LAND1 TYPE T042Z-LAND1,
          ZLSCH TYPE T042Z-ZLSCH,
          TEXT1 TYPE T042Z-TEXT1,
        END OF TY_T042Z.

DATA : IT_T042Z TYPE TABLE OF TY_T042Z,
       WA_T042Z TYPE TY_T042Z.

TYPES : BEGIN OF TY_LFBK,
          LIFNR TYPE LFBK-LIFNR,
          BANKS TYPE LFBK-BANKS,
          BANKL TYPE LFBK-BANKL,
          BANKN TYPE LFBK-BANKN,
        END OF TY_LFBK.

DATA : IT_LFBK TYPE TABLE OF TY_LFBK,
       WA_LFBK TYPE TY_LFBK.

TYPES : BEGIN OF TY_BSAK,
          BUKRS TYPE BSAK-BUKRS,
          LIFNR TYPE BSAK-LIFNR,
          AUGBL TYPE BSAK-AUGBL,
          GJAHR TYPE BSAK-GJAHR,
          BELNR TYPE BSAK-BELNR,
          BLART TYPE BSAK-BLART,
          DMBTR TYPE BSAK-DMBTR,
          BUDAT TYPE BSAK-BUDAT,
        END OF TY_BSAK.

DATA : IT_BSAK TYPE TABLE OF TY_BSAK,
       WA_BSAK TYPE TY_BSAK.

TYPES : BEGIN OF TY_BSIK,
          BUKRS TYPE BSIK-BUKRS,
          BELNR TYPE BSIK-BELNR,
          GJAHR TYPE BSIK-GJAHR,
          BUDAT TYPE BSIK-BUDAT,
          DMBTR TYPE BSIK-DMBTR,
          AUGBL TYPE BSIK-AUGBL,
          BLART TYPE BSIK-BLART,
          REBZG TYPE BSIK-REBZG,
          WRBTR TYPE BSIK-WRBTR,
          REBZJ TYPE BSIK-REBZJ,
        END OF TY_BSIK.

DATA : IT_BSIK TYPE TABLE OF TY_BSIK,
       WA_BSIK TYPE TY_BSIK.

*TYPES : BEGIN OF TY_BSIK1,
*          BUKRS TYPE BSIK-BUKRS,
*          BELNR TYPE BSIK-BELNR,
*          GJAHR TYPE BSIK-GJAHR,
*          BUDAT TYPE BSIK-BUDAT,
*        END OF TY_BSIK1.
*
*
*DATA : IT_BSIK1 TYPE TABLE OF TY_BSIK1,
*       WA_BSIK1 TYPE TY_BSIK1.


DATA : IT_FINAL TYPE  ZSUFI_PV1,
       WA_FINAL TYPE ZSU_FI_PAYMENT_VOUCHER.

DATA : FM_NAME           TYPE RS38L_FNAM,
       FORMNAME          TYPE TDSFNAME,
       CONTROL           TYPE SSFCTRLOP,        "CONTROL PARAMETERS
       OUT_OPT           TYPE SSFCOMPOP,
       RETURN1           TYPE SSFCRESCL,
       LS_COMPOSER_PARAM TYPE SSFCOMPOP,
       GS_CON_SETTINGS   TYPE SSFCTRLOP,
       LENGTH            TYPE I.

DATA : GS_CTRLOP  TYPE SSFCTRLOP,
       GS_OUTOPT  TYPE SSFCOMPOP,
       GS_OTFDATA TYPE SSFCRESCL.

DATA: LS_JOB_INFO  TYPE SSFCRESCL.

DATA : LV_AMOUNT TYPE DMBTR.
