
DATA:
  lv_amt TYPE pc207-betrg.
*BREAK-POINT.
CLEAR: GV_GST_WRD,GV_TOT_WRD.

*lv_amt = tot_tax.
lv_amt = grand_tot.    "GV_TOT_AMT.

GV_AMOUNT1 = lv_amt.

  CALL FUNCTION 'SPELL_AMOUNT'
  EXPORTING
    AMOUNT          = GV_AMOUNT1
*    CURRENCY        = gs_accounting_doc_hdr-waers
    CURRENCY        = P_WAERS
*   FILLER          = ' '
    LANGUAGE        = SY-LANGU
  IMPORTING
    IN_WORDS        = gv_AMOUNT2
 EXCEPTIONS
   NOT_FOUND       = 1
   TOO_LARGE       = 2
   OTHERS          = 3
    .
  IF sy-subrc <> 0.
* Implement suitable error handling here
  ENDIF.


if P_WAERS = 'USD'.
IF GV_AMOUNT2-DECWORD NE 'ZERO'.
 CONCATENATE  GV_AMOUNT2-word'DOLLARS' 'AND'
             GV_AMOUNT2-DECWORD'CENTS ' INTO net_amount SEPARATED BY SPACE.
 ELSEIF
    GV_AMOUNT2-DECWORD = 'ZERO' .
    CONCATENATE  GV_AMOUNT2-word'DOLLARS'
              INTO net_amount SEPARATED BY SPACE.

 ENDIF.
elseif P_WAERS = 'SAR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'ONLY' INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'AND' GV_AMOUNT2-DECWORD 'HALALAS ONLY' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'INR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE 'RUPEES' GV_AMOUNT2-WORD ' ONLY' INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE 'RUPEES' GV_AMOUNT2-WORD 'AND' GV_AMOUNT2-DECWORD 'PAISE' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'EUR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE  GV_AMOUNT2-WORD 'EURO'  INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'EURO AND' GV_AMOUNT2-DECWORD 'CENTS' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'CNY'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE  GV_AMOUNT2-WORD 'YUANS'  INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'YUANS AND' GV_AMOUNT2-DECWORD 'JIAOS' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'GBP'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE  GV_AMOUNT2-WORD 'POUNDS'  INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'POUNDS AND' GV_AMOUNT2-DECWORD 'PENNYS' INTO net_amount SEPARATED BY SPACE.
     endif.

endif.

*IF net_amount IS NOT INITIAL.
*gv_gst_wrd = net_amount.
*ENDIF.

CLEAR lv_amt.
*lv_amt = net_val.
 lv_amt = tot_tax.

GV_AMOUNT1 =  lv_amt .

CALL FUNCTION 'SPELL_AMOUNT'
EXPORTING
  AMOUNT          = GV_AMOUNT1
  CURRENCY        = P_WAERS
*  CURRENCY        = gs_accounting_doc_hdr-waers
*   FILLER          = ' '
  LANGUAGE        = SY-LANGU
IMPORTING
  IN_WORDS        = gv_AMOUNT2
 EXCEPTIONS
   NOT_FOUND       = 1
   TOO_LARGE       = 2
   OTHERS          = 3
  .
IF sy-subrc <> 0.
* Implement suitable error handling here
ENDIF.
*GV_AMOUNT5 = GV_AMOUNT2-WORD.
*amt2       = GV_AMOUNT2-DECWORD.



if P_WAERS = 'USD'.
IF GV_AMOUNT2-DECWORD NE 'ZERO'.
 CONCATENATE  GV_AMOUNT2-word'DOLLARS' 'AND'
             GV_AMOUNT2-DECWORD'CENTS ' INTO tax_amount SEPARATED BY SPACE.
 ELSEIF
    GV_AMOUNT2-DECWORD = 'ZERO' .
    CONCATENATE  GV_AMOUNT2-word'DOLLARS'
              INTO tax_amount SEPARATED BY SPACE.

 ENDIF.
elseif P_WAERS = 'SAR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'ONLY' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'AND'
     GV_AMOUNT2-DECWORD 'HALALAS ONLY' INTO tax_amount SEPARATED BY SPACE.
     endif.

 elseif P_WAERS = 'INR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE 'RUPEES' GV_AMOUNT2-WORD 'ONLY' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE 'RUPEES' GV_AMOUNT2-WORD 'AND'
     GV_AMOUNT2-DECWORD 'PAISE' INTO tax_amount SEPARATED BY SPACE.
     endif.

 elseif P_WAERS = 'EUR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'EURO' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'EURO AND'
     GV_AMOUNT2-DECWORD 'CENTS' INTO tax_amount SEPARATED BY SPACE.
     endif.

  elseif P_WAERS = 'CNY'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'YUANS' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'YUANS AND'
     GV_AMOUNT2-DECWORD 'JIAOS' INTO tax_amount SEPARATED BY SPACE.
     endif.

   elseif P_WAERS = 'GBP'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'POUNDS' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'POUNDS and'
     GV_AMOUNT2-DECWORD 'PENNYS' INTO tax_amount SEPARATED BY SPACE.
     endif.

endif.

*IF tax_amount IS NOT INITIAL.
*gv_tot_wrd = tax_amount.
*ENDIF.
