"Name: \PR:SAPLV60A\FO:USEREXIT_PRICING_PREPARE_TKOMP\SE:BEGIN\EI
ENHANCEMENT 0 ZSU_SD_VF01_VALIDATION.
IF SY-TCODE = 'VF01' AND SY-UCOMM = 'SICH' AND TVTA-VKORG = 'SU00'.                                    """ADDED BY  MOHSIN(102100)ON 01.02.2023.

DATA : lv_kwert type konv-KWERT,
       lv_kwert_tot type konv-KWERT,
       lv_kwert_SO type konv-KWERT,
       lv_kwert_PI TYPE KONV-KWERT,
       LV_KONV01_INV TYPE KONV-KWERT,
       LV_KONV01_ADV TYPE KONV-KWERT,
       LV_KONV01_TSO  TYPE KONV-KWERT,
       LV_RADV  TYPE KONV-KWERT,
       WA_KOMV TYPE KOMV,
       lv_kwert_TEMP TYPE KONV-KWERT,
       lv_kwert_ADV TYPE KONV-KWERT,
       LS_VBAP TYPE VBAP,
       ls_XKOMV TYPE  KOMV ,
       LT_XKOMV TYPE TABLE OF KOMV,
       LS_KOMV TYPE konv.

DATA: LT_VBFA TYPE STANDARD TABLE OF VBFA,
      WA_VBFA TYPE  VBFA,
      LT_VBFA01 TYPE STANDARD TABLE OF VBFA,
      IT_KONV TYPE STANDARD TABLE OF KONV,
      WA_KONV TYPE  KONV,
      LT_KONV01 TYPE TABLE OF  KONV,
      LT_KONV02 TYPE TABLE OF  KONV,
      WA_KONV01 TYPE  KONV,
      WA_KONV02 TYPE  KONV,
      IT_VBAK TYPE TABLE OF VBAK,
      WA_VBAK TYPE VBAK.

TYPES : BEGIN OF TY_VBAP_VBRK,
        KNUMV TYPE VBRK-KNUMV,
        POSNR TYPE VBRP-POSNR,
        MATNR TYPE VBRP-MATNR,
        END OF TY_VBAP_VBRK.

  DATA : IT_VBRK_VBRP TYPE TABLE OF TY_VBAP_VBRK,
         WA_VBRK_VBRP TYPE  TY_VBAP_VBRK.
*         LT_VBFA TYPE TABLE OF VBFA.
DATA : IT_VBRK_VBRP01 TYPE TABLE OF TY_VBAP_VBRK,
       IT_VBRK_VBRP02 TYPE TABLE OF KONV,
         WA_VBRK_VBRP01 TYPE  TY_VBAP_VBRK,
         WA_VBRK_VBRP02 TYPE  KONV.

 if vbrk-fkart = 'ZPI'.
*******************************************************
  SELECT * FROM VBFA INTO TABLE LT_VBFA WHERE VBELV = VBAK-VBELN AND VBTYP_N IN ( 'U' , 'M' ).     """INV AND PI

  SELECT A~KNUMV
         B~POSNR
         B~MATNR
      FROM VBRK AS A
      INNER JOIN VBRP AS B ON A~VBELN = B~VBELN
      INTO TABLE IT_VBRK_VBRP
      FOR ALL ENTRIES IN LT_VBFA
      WHERE A~VBELN = LT_VBFA-VBELN.

  SELECT * FROM KONV
            INTO TABLE LT_KONV01
            FOR ALL ENTRIES IN IT_VBRK_VBRP
            WHERE KNUMV = IT_VBRK_VBRP-KNUMV
            AND   KPOSN = IT_VBRK_VBRP-POSNR
*            AND   MATNR = IT_VBRK_VBRP-MATNR
            AND   KSCHL IN ('ZPR0','ZADV').

   READ TABLE LT_KONV01 INTO WA_KONV01 INDEX 1.
    LV_KONV01_INV = WA_KONV01-KWERT.

   LOOP AT LT_KONV01 INTO WA_KONV01 WHERE KSCHL = 'ZADV' .
      LV_KONV01_INV = LV_KONV01_INV  + WA_KONV01-KWERT.

   ENDLOOP.

********************************************************************SO

 READ TABLE LT_VBFA INTO WA_VBFA INDEX 1.

  SELECT A~KNUMV
         B~POSNR
         B~MATNR
      FROM VBAK AS A
      INNER JOIN VBAP AS B ON A~VBELN = B~VBELN
      INTO TABLE IT_VBRK_VBRP01
*      FOR ALL ENTRIES IN LT_VBFA
      WHERE A~VBELN = WA_VBFA-VBELV.


SELECT * FROM KONV INTO TABLE LT_KONV02
              FOR ALL ENTRIES IN IT_VBRK_VBRP01
              WHERE KNUMV = IT_VBRK_VBRP01-KNUMV
               AND  KPOSN =  IT_VBRK_VBRP01-POSNR
               AND  KSCHL = 'ZPR0'.

IF IT_VBRK_VBRP01 IS NOT INITIAL.
SELECT * FROM KONV INTO TABLE IT_VBRK_VBRP02
              FOR ALL ENTRIES IN IT_VBRK_VBRP01
              WHERE KNUMV = IT_VBRK_VBRP01-KNUMV
               AND  KPOSN =  IT_VBRK_VBRP01-POSNR
               AND  KSCHL = 'ZADV'.
*               AND KHERK = 'D' .

ENDIF.

  LOOP AT LT_KONV02 INTO WA_KONV02.

    LV_KONV01_TSO  = LV_KONV01_TSO  +  WA_KONV02-KWERT .

  ENDLOOP.

  DATA : IT_KOMV TYPE TABLE OF KOMV.

  LOOP AT XKOMV[] INTO wa_komv.
    IF wa_komv-KSCHL = 'ZADV' AND  wa_komv-KHERK = 'D'.
         LV_RADV = LV_RADV + wa_komv-KAWRT.
    ELSEIF wa_komv-KSCHL = 'ZADV' AND  wa_komv-KHERK = 'C'.
        LS_KOMV = wa_komv.
    ENDIF.
  ENDLOOP.


   IF LV_RADV IS NOT INITIAL.
     LV_KONV01_TSO = LV_KONV01_TSO - LV_RADV .
   ENDIF.

  IF SY-SUBRC = 0 .
    IF LS_KOMV-KBETR > LV_KONV01_TSO  .
         MESSAGE'AMOUNT EXCEED' TYPE 'E' DISPLAY LIKE 'E' .
    ENDIF.
  ENDIF.
ENDIF.
ENDIF.

ENDENHANCEMENT.
