*&---------------------------------------------------------------------*
*&  Include           ZSU_FI_PAYMENT_VOUCHER_SS
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

SELECT-OPTIONS : S_BELNR   FOR BKPF-BELNR OBLIGATORY,
                 S_BUDAT   FOR BKPF-BUDAT,
                 S_GJAHR   FOR BKPF-GJAHR OBLIGATORY.
PARAMETERS: P_BUKRS TYPE BKPF-BUKRS DEFAULT 'SU00' MODIF ID BU,
*            P_GJAHR TYPE BKPF-GJAHR OBLIGATORY,
            P_WAERS TYPE BKPF-WAERS OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-001.
PARAMETERS: R_FULL RADIOBUTTON GROUP RAD2 DEFAULT 'X', "Local
            R_ADV  RADIOBUTTON GROUP RAD2 , "USER-COMMAND flg.
            R_PART RADIOBUTTON GROUP RAD2.
SELECTION-SCREEN : END OF BLOCK B2.
