PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSU_PRCERT_TABLE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSU_PRCERT_TABLE-ZNO .
    FIELD ZSU_PRCERT_TABLE-BRAND .
    FIELD ZSU_PRCERT_TABLE-TEST_STD .
    FIELD ZSU_PRCERT_TABLE-ZSU_FROM .
    FIELD ZSU_PRCERT_TABLE-ZSU_TO .
    FIELD ZSU_PRCERT_TABLE-SHELL_TEST .
    FIELD ZSU_PRCERT_TABLE-HYDRO_SEAT_TEST .
    FIELD ZSU_PRCERT_TABLE-PNEUMATIC_TEST .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSU_PRCERT_TABLE-ZNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
