DATA: BEGIN OF ITAB OCCURS 0,
      TEXT(100),
      END   OF ITAB.



DATA:
  lv_amt TYPE pc207-betrg.

CLEAR: GV_GST_WRD,GV_TOT_WRD.

lv_amt = tot_tax.
gv_amount1 = lv_amt.

CALL FUNCTION 'SPELL_AMOUNT'
EXPORTING
  AMOUNT          = GV_AMOUNT1
  CURRENCY        = P_WAERS
*  CURRENCY        = gs_accounting_doc_hdr-waers
*   FILLER          = ' '
  LANGUAGE        = SY-LANGU
IMPORTING
  IN_WORDS        = gv_AMOUNT2
 EXCEPTIONS
   NOT_FOUND       = 1
   TOO_LARGE       = 2
   OTHERS          = 3
  .
IF sy-subrc <> 0.
* Implement suitable error handling here
ENDIF.
*GV_AMOUNT5 = GV_AMOUNT2-WORD.
*amt2       = GV_AMOUNT2-DECWORD.



if P_WAERS = 'USD'.
IF GV_AMOUNT2-DECWORD NE 'ZERO'.
 CONCATENATE  GV_AMOUNT2-word'DOLLARS' 'AND'
             GV_AMOUNT2-DECWORD'CENTS ' INTO tax_amount SEPARATED BY SPACE.
 ELSEIF
    GV_AMOUNT2-DECWORD = 'ZERO' .
    CONCATENATE  GV_AMOUNT2-word'DOLLARS'
              INTO tax_amount SEPARATED BY SPACE.

 ENDIF.
elseif P_WAERS = 'SAR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'ONLY' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'AND'
     GV_AMOUNT2-DECWORD 'HALALAS ONLY' INTO tax_amount SEPARATED BY SPACE.
     endif.

 elseif P_WAERS = 'INR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'RUPEES ONLY' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'RUPEES' 'AND'
     GV_AMOUNT2-DECWORD 'PAISE' INTO tax_amount SEPARATED BY SPACE.
     endif.

 elseif P_WAERS = 'EUR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'EURO' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'EURO AND'
     GV_AMOUNT2-DECWORD 'CENTS' INTO tax_amount SEPARATED BY SPACE.
     endif.

  elseif P_WAERS = 'CNY'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'YUANS' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'YUANS AND'
     GV_AMOUNT2-DECWORD 'JIAOS' INTO tax_amount SEPARATED BY SPACE.
     endif.

   elseif P_WAERS = 'GBP'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'POUNDS' INTO tax_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'POUNDS and'
     GV_AMOUNT2-DECWORD 'PENNYS' INTO tax_amount SEPARATED BY SPACE.
     endif.
endif.

IF tax_amount IS NOT INITIAL.
  gv_gst_wrd = tax_amount.
ENDIF.

*CALL FUNCTION 'ISP_CONVERT_FIRSTCHARS_TOUPPER'
*EXPORTING
*  input_string        = gv_gst_wrd
*  SEPARATORS          = ' '
*IMPORTING
*  OUTPUT_STRING       = gv_gst_wrd
*  .
SPLIT gv_gst_wrd AT '' INTO TABLE ITAB.
CLEAR gv_gst_wrd.

LOOP AT ITAB.
TRANSLATE ITAB-TEXT+0(1) TO UPPER CASE.
CONCATENATE gv_gst_wrd ITAB-TEXT INTO gv_gst_wrd SEPARATED BY ''.
ENDLOOP.

gv_gst_wrd = gv_gst_wrd+1.

clear itab.

lv_amt = net_val.

GV_AMOUNT1 = lv_amt.
  CALL FUNCTION 'SPELL_AMOUNT'
  EXPORTING
    AMOUNT          = GV_AMOUNT1
*    CURRENCY        = gs_accounting_doc_hdr-waers
    CURRENCY        = P_WAERS
*   FILLER          = ' '
    LANGUAGE        = SY-LANGU
  IMPORTING
    IN_WORDS        = gv_AMOUNT2
 EXCEPTIONS
   NOT_FOUND       = 1
   TOO_LARGE       = 2
   OTHERS          = 3
    .
  IF sy-subrc <> 0.
* Implement suitable error handling here
  ENDIF.


if P_WAERS = 'USD'.
IF GV_AMOUNT2-DECWORD NE 'ZERO'.
 CONCATENATE  GV_AMOUNT2-word'DOLLARS' 'AND'
             GV_AMOUNT2-DECWORD'CENTS ' INTO net_amount SEPARATED BY SPACE.
 ELSEIF
    GV_AMOUNT2-DECWORD = 'ZERO' .
    CONCATENATE  GV_AMOUNT2-word'DOLLARS'
              INTO net_amount SEPARATED BY SPACE.

 ENDIF.
elseif P_WAERS = 'SAR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'ONLY' INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE 'SAUDI RIYAL' GV_AMOUNT2-WORD 'AND' GV_AMOUNT2-DECWORD 'HALALAS ONLY' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'INR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE GV_AMOUNT2-WORD 'RUPEES ONLY' INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'RUPEES AND' GV_AMOUNT2-DECWORD 'PAISE' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'EUR'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE  GV_AMOUNT2-WORD 'EURO'  INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'EURO AND' GV_AMOUNT2-DECWORD 'CENTS' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'CNY'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE  GV_AMOUNT2-WORD 'YUANS'  INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'YUANS AND' GV_AMOUNT2-DECWORD 'JIAOS' INTO net_amount SEPARATED BY SPACE.
     endif.

elseif P_WAERS = 'GBP'.
      IF GV_AMOUNT2-DECWORD = 'ZERO'.
     CONCATENATE  GV_AMOUNT2-WORD 'POUNDS'  INTO net_amount SEPARATED BY SPACE.
*     ENDIF.
*     IF IN_WORDS-DECWORD IS NOT INITIAL.
     ELSE.
     CONCATENATE GV_AMOUNT2-WORD 'POUNDS AND' GV_AMOUNT2-DECWORD 'PENNYS' INTO net_amount SEPARATED BY SPACE.
     endif.

endif.

IF net_amount IS NOT INITIAL.
   gv_tot_wrd = net_amount .
ENDIF.




SPLIT gv_tot_wrd AT '' INTO TABLE ITAB.
CLEAR gv_tot_wrd.

LOOP AT ITAB.
TRANSLATE ITAB-TEXT+0(1) TO UPPER CASE.
CONCATENATE gv_tot_wrd ITAB-TEXT INTO gv_tot_wrd SEPARATED BY ''.
ENDLOOP.

gv_tot_wrd = gv_tot_wrd+1.

clear itab.
*CALL FUNCTION 'ISP_CONVERT_FIRSTCHARS_TOUPPER'
*EXPORTING
*  input_string        = gv_tot_wrd
*  SEPARATORS          = ' '
*IMPORTING
*  OUTPUT_STRING       = gv_tot_wrd




  .
