*
*LOOP AT IT_FINAL INTO WA_FINAL.
*
*ENDLOOP.
*
*SELECT   BUKRS,
*         AUGBL,
*         GJAHR,
*         BELNR,
*         BLART,
*         DMBTR,
*         BUDAT
*    FROM BSAD
*    INTO TABLE @DATA(IT_BSAD1)
*    WHERE AUGBL = @WA_FINAL-BELNR1
*    AND  BUKRS = 'SU00'
*    AND GJAHR = '2023'
*    AND BLART IN  ('DR','RV','DG').
*  BREAK-POINT.
*  SELECT BELNR ,
*         XBLNR
*    FROM BKPF
*    INTO TABLE @DATA(IT_BKPF)
*    FOR ALL ENTRIES IN @IT_BSAD1
*    WHERE BELNR = @IT_BSAD1-BELNR
*    AND GJAHR = @IT_BSAD1-GJAHR.
*
*  LOOP AT IT_BSAD1 INTO DATA(WA_BSAD1).
*
*  WA_FINAL1-BUDAT = WA_BSAD1-BUDAT.
*  IF  WA_BSAD1-BLART EQ 'DR' .
*   WA_FINAL1-BELNR = WA_BSAD1-BELNR.
*  ENDIF.
*
*  WA_FINAL1-DMBTR = WA_BSAD1-DMBTR.
*
*  IF WA_BSAD1-BLART EQ 'DG'.
* WA_FINAL1-DMBTR1 = WA_BSAD1-DMBTR.
*  ENDIF.
*READ TABLE IT_BKPF INTO DATA(WA_BKPF) WITH KEY BELNR = WA_BSAD1-BELNR.
*WA_FINAL1-XBLNR = WA_BKPF-XBLNR.
*
* APPEND WA_FINAL1 TO IT_FINAL1.
*  ENDLOOP.
*
* DELETE IT_FINAL1 WHERE BELNR EQ SPACE.
*
*
*GV_NET =  WA_FINAL1-DMBTR  -  WA_FINAL1-DMBTR1.










