*BREAK-POINT.
SELECT   BUKRS,
         AUGBL,
         GJAHR,
         BELNR,
         BLART,
         DMBTR,
         XBLNR,
         BUDAT,
         WRBTR
    FROM BSAD
    INTO TABLE @DATA(IT_BSAD1)
    WHERE AUGBL = @WA_FINAL-BELNR1
    AND  BUKRS = @WA_FINAL-BUKRS
    AND GJAHR = @WA_FINAL-GJAHR
    AND BLART IN  ('DR','RV','DG').

  SELECT BELNR ,
         XBLNR
    FROM BKPF
    INTO TABLE @DATA(IT_BKPF)
    FOR ALL ENTRIES IN @IT_BSAD1
    WHERE BELNR = @IT_BSAD1-BELNR
    AND GJAHR = @IT_BSAD1-GJAHR.
*BREAK-POINT.
   CLEAR : GV_NET,lv_sum,LV_TOTAL.

  LOOP AT IT_BSAD1 INTO DATA(WA_BSAD1) WHERE blart = 'DR'.

  WA_FINAL1-BUDAT = WA_BSAD1-BUDAT.
  WA_FINAL1-BELNR = WA_BSAD1-BELNR.
  WA_FINAL1-XBLNR = WA_BSAD1-XBLNR.
  WA_FINAL1-DMBTR = WA_BSAD1-DMBTR.
  WA_FINAL1-WRBTR = WA_BSAD1-WRBTR.

READ TABLE IT_BSAD1 INTO DATA(WA_BSAD2) WITH KEY BUKRS = WA_BSAD1-BUKRS
AUGBL = WA_BSAD1-AUGBL GJAHR = WA_BSAD1-GJAHR  XBLNR = WA_BSAD1-XBLNR
 BLART = 'DG'  .
IF SY-SUBRC IS INITIAL.
 WA_FINAL1-DMBTR1 = WA_BSAD2-DMBTR.
 WA_FINAL1-WRBTR1 = WA_BSAD2-WRBTR.
ENDIF.

GV_NET =  WA_FINAL1-DMBTR  -  WA_FINAL1-DMBTR1.
LV_OTH =  WA_FINAL1-WRBTR  -  WA_FINAL1-WRBTR1.
WA_FINAL1-LV_OTH = LV_OTH.
WA_FINAL1-GV_NET = GV_NET.
LV_TOTAL = LV_TOTAL + WA_FINAL1-LV_OTH.
   lv_sum = lv_sum + GV_NET.
 APPEND WA_FINAL1 TO IT_FINAL1.
CLEAR :LV_OTH,GV_NET.
  ENDLOOP.

    LOOP AT IT_BSAD1 INTO WA_BSAD1 WHERE blart = 'RV'.

      WA_FINAL1-BUDAT = WA_BSAD1-BUDAT.
      WA_FINAL1-BELNR = WA_BSAD1-BELNR.
      WA_FINAL1-XBLNR = WA_BSAD1-XBLNR.
      WA_FINAL1-DMBTR = WA_BSAD1-DMBTR.
      GV_NET =  WA_FINAL1-DMBTR  -  WA_FINAL1-DMBTR1.
      WA_FINAL1-GV_NET = GV_NET.



      READ TABLE IT_BSAD1 INTO WA_BSAD1 WITH KEY blart = 'DG'.
      IF SY-SUBRC IS INITIAL.
         WA_FINAL1-DMBTR1 = WA_BSAD1-DMBTR.
         WA_FINAL1-WRBTR1 = WA_BSAD1-WRBTR.
      ENDIF.


      GV_NET =  WA_FINAL1-DMBTR  -  WA_FINAL1-DMBTR1.
      WA_FINAL1-GV_NET = GV_NET.
      lv_sum = lv_sum + GV_NET.

     APPEND WA_FINAL1 TO IT_FINAL1.
      ENDLOOP.
