
TYPES : BEGIN OF TY_FINAL1,
          BELNR TYPE BSID-BELNR,
          BUDAT TYPE BSID-BUDAT,
          DMBTR TYPE BSID-DMBTR,
          DMBTR1 TYPE BSID-DMBTR,
          WRBTR TYPE BSID-WRBTR,
          XBLNR TYPE BKPF-XBLNR,
          GV_NET TYPE BSID-DMBTR,
          LV_SUM TYPE BSID-DMBTR,
          WRBTR1 TYPE BSID-WRBTR,
          LV_OTH TYPE BSID-WRBTR,
        END OF TY_FINAL1.






