
TYPES : BEGIN OF TY_BSID,
        BELNR TYPE BSID-BELNR,
        REBZG TYPE BSID-REBZG,
        BUDAT TYPE BSID-BUDAT,
        XBLNR TYPE BSID-XBLNR,
        DMBTR TYPE BSID-DMBTR,
        WRBTR TYPE BSID-WRBTR,
        DMBTR1 TYPE BSID-DMBTR,
        WRBTR1 TYPE BSID-WRBTR,
        END OF TY_BSID.

      TYPES: BEGIN OF TY_BSIK,
        BELNR  TYPE   BSID-BELNR,
        BUKRS  TYPE   BSID-BUKRS,
        GJAHR  TYPE   BSID-GJAHR,
        REBZG  TYPE   BSID-REBZG,
        REBZJ  TYPE   BSID-REBZJ,
        BUDAT  TYPE   BSID-BUDAT,
        DMBTR  TYPE   BSID-DMBTR,
        BUZEI  TYPE   BSID-BUZEI,
        WRBTR  TYPE   BSID-WRBTR,
        WRBTR1  TYPE   BSID-WRBTR,
        END OF TY_BSIK.








