"Name: \PR:SAPLV45U\FO:VBAK_BEARBEITEN\SE:END\EI
ENHANCEMENT 0 ZUS_GET_VBAP.
* BREAK-POINT.
**  IF  SY-TCODE EQ 'VA01'.
**    TABLES ZUS_VBAP.
**    TYPES : BEGIN OF TY_VBAP,
**           ZVBELN TYPE  ZUS_VBAP-ZVBELN,
**           ZBSTKD TYPE  ZUS_VBAP-ZBSTKD,
**           ZPOSEX TYPE  ZUS_VBAP-ZPOSEX,
**           END OF TY_VBAP.
**
**    DATA : IT_VBAP TYPE TABLE OF TY_VBAP,
**           WA_VBAP TYPE TY_VBAP.
**
**    wa_vbap-ZVBELN = vbap-VBELN.
**    wa_vbap-ZBSTKD = ZUS_VBAP-ZBSTKD.
**    wa_vbap-ZPOSEX = ZUS_VBAP-ZPOSEX.
**
**    INSERT WA_VBAP INTO TABLE IT_VBAP.
**
**  ENDIF.
ENDENHANCEMENT.
