types : BEGIN OF ty_DATA,
        MBLNR  TYPE MSEG-MBLNR,
        MATNR  TYPE MSEG-MATNR,
        MENGE  TYPE STRING,
        WERKS  TYPE MSEG-WERKS,
        lgort  TYPE MSEG-lgort,
        mjahr  TYPE MSEG-mjahr,
        ZEILE  TYPE STRING,
        BWART  TYPE MSEG-BWART,
        RATE   TYPE MSEG-dmbtr,
        END OF   ty_DATA.

TYPES : BEGIN OF ty_lfa1,
        NAME1 TYPE lfa1-NAME1,
        STRAS TYPE lfa1-STRAS,
        PSTLZ TYPE lfa1-PSTLZ,
        ORT01 TYPE lfa1-ORT01,
        END OF  ty_lfa1.

types : BEGIN OF ty_lineitem,
*         ZMATNR  TYPE zsub_challan-zmatnr,
         count  type string,
*         ZRATE  TYPE string,
         ZRATE  TYPE zsub_challan-ZRATE,"P decimals 2,
         mblnr  TYPE mseg-mblnr,
         ZEILE  TYPE mseg-ZEILE,
         MATNR  TYPE mseg-matnr,
*         MENGE  TYPE STRING,
         MENGE  TYPE P decimals 2,
         maktx   type makt-maktx,
*         value type STRING,
         value type P decimals 2,
         ZREMARKS TYPE ZREMARKS,
         ZSHIP_DATE TYPE ZSHIP_DATE,
        END OF ty_lineitem.
