*BREAK primus.

"""""Added by pankaj 23.09.2021

""""""commented by pankaj """"""""""""""


*CALL FUNCTION 'CONVERSION_EXIT_SDATE_OUTPUT'
*EXPORTING
*INPUT = IS_VBDKA-AUDAT
*IMPORTING
*OUTPUT = GV_SALE_DATE.
*
**TRANSLATE GV_SALE_DATE+2(1) TO LOWER CASE.
*CONCATENATE  GV_SALE_DATE+3(3) GV_SALE_DATE+0(2)
*             GV_SALE_DATE+7(4)
*             INTO GV_SALE_DATE SEPARATED BY '.'.
*
*
*CALL FUNCTION 'CONVERSION_EXIT_SDATE_OUTPUT'
*EXPORTING
*INPUT = WA_VBAK-VDATU
*IMPORTING
*OUTPUT = GV_SHIP_DATE.

""""""""""""""""""""""""""""""""""""""

*CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
*    EXPORTING
*      input         = IS_VBDKA-AUDAT
*   IMPORTING
*     OUTPUT        = GV_SALE_DATE
            .
*TRANSLATE GV_SALE_DATE+1(2) TO LOWER CASE.
*TRANSLATE GV_SALE_DATE+2(1) TO UPPER CASE.
CONCATENATE IS_VBDKA-AUDAT+4(2) IS_VBDKA-AUDAT+6(2)
             IS_VBDKA-AUDAT+0(4)
                INTO GV_SALE_DATE SEPARATED BY '.'.

*CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
*    EXPORTING
*      input         = WA_VBAK-VDATU
*   IMPORTING
*     OUTPUT        = GV_SHIP_DATE
            .
*TRANSLATE GV_SHIP_DATE+1(2) TO LOWER CASE.
*TRANSLATE GV_SHIP_DATE+2(1) TO UPPER CASE.
CONCATENATE  IS_VBDKA-AUDAT+4(2)  IS_VBDKA-AUDAT+6(2)
             IS_VBDKA-AUDAT+0(4)
                INTO GV_SHIP_DATE SEPARATED BY '.'.












