*&---------------------------------------------------------------------*
*&  Include           ZUS_MB5B_1_TOP
*&---------------------------------------------------------------------*

DATA : DT_BUDAT_LOW  TYPE MSEG-BUDAT_MKPF, " add by supriya on 05.09.2024
       DT_BUDAT_HIGH TYPE MSEG-BUDAT_MKPF.


TYPES :BEGIN OF TY_FINAL,
         MBLNR       TYPE MSEG-MBLNR,
         MJAHR       TYPE MSEG-MJAHR,
         ZEILE       TYPE MSEG-ZEILE,
         BWART       TYPE MSEG-BWART,
         MATNR       TYPE MSEG-MATNR,
         LGORT       TYPE MSEG-LGORT,
         WERKS       TYPE MSEG-WERKS,
         CPUDT_MKPF  TYPE MSEG-CPUDT_MKPF,
         CPUTM_MKPF  TYPE MSEG-CPUTM_MKPF,
         WAERS       TYPE MSEG-WAERS,
         BUDAT_MKPF  TYPE CHAR15,            "MSEG-BUDAT_MKPF,
         MTART       TYPE MARA-MTART,
         MATKL       TYPE MARA-MATKL,
         BRAND       TYPE MARA-BRAND,
         ZSERIES     TYPE MARA-ZSERIES,
         ZSIZE       TYPE MARA-ZSIZE,
         BTEXT       TYPE T156HT-BTEXT,
         AGEING      TYPE STRING,
         AGEING_DESC TYPE STRING,
         DT_BUDAT_LOW  TYPE CHAR15, "MSEG-BUDAT_MKPF, " add by supriya on 05.09.2024
         DT_BUDAT_HIGH TYPE CHAR15, "MSEG-BUDAT_MKPF,  " add by supriya on 05.09.2024
         MENGE       TYPE MSEG-MENGE,
         MENGE1      TYPE MSEG-MENGE,
         CL_STOCK    TYPE MSEG-MENGE,
         OP_STOCK    TYPE MSEG-MENGE,
         OP_VALUE    TYPE P DECIMALS 4,
         REC_VAL     TYPE P DECIMALS 4,
         ISS_VAL     TYPE P DECIMALS 4,
         CL_VALUE    TYPE P DECIMALS 4,
         STOCK       TYPE P DECIMALS 4,
         REC_QTY     TYPE MSEG-MENGE,
         ISS_QTY     TYPE MSEG-MENGE,
       END OF TY_FINAL.

TYPES :BEGIN OF TY_SUM,
         MATNR  TYPE MATNR,
         MENGE  TYPE MSEG-MENGE,
         MENGE1 TYPE MSEG-MENGE,
       END OF TY_SUM.

TYPES :BEGIN OF TY_SUM_NEW,
         MATNR  TYPE MSEG-MATNR,
         MENGE  TYPE MSEG-MENGE,
         MENGE1 TYPE MSEG-MENGE,
         SHKZG  TYPE MSEG-SHKZG,
         DMBTR  TYPE MSEG-DMBTR,
       END OF TY_SUM_NEW.

       TYPES :BEGIN OF TY_SUM_1,
         MATNR  TYPE MSEG-MATNR,
         MENGE  TYPE MSEG-MENGE,
         MENGE1 TYPE MSEG-MENGE,
         SHKZG  TYPE MSEG-SHKZG,
         DMBTR  TYPE MSEG-DMBTR,
       END OF TY_SUM_1.

TYPES :BEGIN OF TY_SUM1,
         MATNR  TYPE MATNR,
         MENGE  TYPE MSEG-MENGE,
         MENGE1 TYPE MSEG-MENGE,
       END OF TY_SUM1.

TYPES :BEGIN OF TY_SUM2,
         MATNR  TYPE MATNR,
         MENGE  TYPE MSEG-MENGE,
         MENGE1 TYPE MSEG-MENGE,
         SHKZG  TYPE MSEG-SHKZG,
         SOBKZ  TYPE MSEG-SOBKZ,
         DMBTR  TYPE MSEG-DMBTR,
       END OF TY_SUM2.

TYPES :BEGIN OF TY_SUM3,
         MATNR  TYPE MATNR,
         MENGE  TYPE MSEG-MENGE,
         MENGE1 TYPE MSEG-MENGE,
       END OF TY_SUM3.

TYPES :BEGIN OF TY_DOWN,
           REF_DATE    TYPE STRING,
           MATNR       TYPE MSEG-MATNR,
           WERKS       TYPE MSEG-WERKS,
           LGORT       TYPE MSEG-LGORT,
           MBLNR       TYPE MSEG-MBLNR,
           ZEILE       TYPE MSEG-ZEILE,
           BWART       TYPE MSEG-BWART,
           MTART       TYPE MARA-MTART,
           MATKL       TYPE MARA-MATKL,
           WAERS       TYPE MSEG-WAERS,
           BUDAT_MKPF  TYPE CHAR15,             "MSEG-BUDAT_MKPF,
           BRAND       TYPE MARA-BRAND,
           ZSERIES     TYPE MARA-ZSERIES,
           ZSIZE       TYPE MARA-ZSIZE,
           BTEXT       TYPE T156HT-BTEXT,
           AGEING      TYPE STRING,
           AGEING_DESC TYPE STRING,
           DT_BUDAT_LOW  TYPE STRING,"MSEG-BUDAT_MKPF, " add by supriya on 05.09.2024
           DT_BUDAT_HIGH TYPE string,"MSEG-BUDAT_MKPF,  " add by supriya on 05.09.2024
          OP_STOCK    TYPE STRING,
           MENGE       TYPE STRING,"MSEG-MENGE,
           MENGE1      TYPE STRING,"MSEG-MENGE,
           CL_STOCK    TYPE STRING,"MSEG-MENGE,
           OP_VALUE    TYPE STRING,"P DECIMALS 4,
           REC_VAL     TYPE STRING,"P DECIMALS 4,
           ISS_VAL     TYPE STRING,"P DECIMALS 4,
           CL_VALUE    TYPE STRING,"P DECIMALS 4,
*           REF_DATE    TYPE STRING,
           REF_TIME    TYPE STRING,

*
*'ZEILE'
*'BWART'
*'MTART'
*'MATKL'
*'WAERS'
*'BUDAT_MKPF'
*'BRAND'
*'ZSERIES'
*'ZSIZE'
*'BTEXT'
*'AGEING'
*'AGEING_DESC'
*'MENGE'
*'MENGE1'
*'CL_STOCK'
*'OP_STOCK'
*'OP_VALUE'
*'REC_VAL'
*'ISS_VAL'
*'CL_VALUE'
*         MBLNR       TYPE MSEG-MBLNR,
*         MJAHR       TYPE MSEG-MJAHR,
*         ZEILE       TYPE MSEG-ZEILE,
*         BWART       TYPE MSEG-BWART,
*         MATNR       TYPE MSEG-MATNR,
*         LGORT       TYPE MSEG-LGORT,
*         WERKS       TYPE MSEG-WERKS,
*         CPUDT_MKPF  TYPE MSEG-CPUDT_MKPF,
*         CPUTM_MKPF  TYPE MSEG-CPUTM_MKPF,
*         WAERS       TYPE MSEG-WAERS,
*         BUDAT_MKPF  TYPE MSEG-BUDAT_MKPF,
*         MTART       TYPE MARA-MTART,
*         MATKL       TYPE MARA-MATKL,
*         BRAND       TYPE MARA-BRAND,
*         ZSERIES     TYPE MARA-ZSERIES,
*         ZSIZE       TYPE MARA-ZSIZE,
*         BTEXT       TYPE T156HT-BTEXT,
*         AGEING      TYPE STRING,
*         AGEING_DESC TYPE STRING,
*         MENGE       TYPE MSEG-MENGE,
*         MENGE1      TYPE MSEG-MENGE,
*         CL_STOCK    TYPE MSEG-MENGE,
*         OP_STOCK    TYPE MSEG-MENGE,
*         OP_VALUE    TYPE P DECIMALS 4,
*         REC_VAL     TYPE P DECIMALS 4,
*         ISS_VAL     TYPE P DECIMALS 4,
*         CL_VALUE    TYPE P DECIMALS 4,
*         STOCK       TYPE P DECIMALS 4,
*         REC_QTY     TYPE MSEG-MENGE,
*         ISS_QTY     TYPE MSEG-MENGE,
*         REF_DATE    TYPE STRING,
*         REF_TIME    TYPE STRING,
       END OF TY_DOWN.


TYPES :BEGIN OF TY_BSIM,
         MATNR  TYPE BSIM-MATNR,
         MENGE  TYPE BSIM-MENGE,
         MENGE1 TYPE BSIM-MENGE,
         SHKZG  TYPE BSIM-SHKZG,
         DMBTR  TYPE BSIM-DMBTR,
       END OF TY_BSIM.

DATA : IT_BSIM TYPE TABLE OF TY_BSIM,
       WA_BSIM TYPE TY_BSIM.

DATA : IT_FINAL TYPE TABLE OF TY_FINAL,
       WA_FINAL TYPE TY_FINAL.

DATA : IT_DOWN TYPE TABLE OF TY_DOWN,
       WA_DOWN TYPE TY_DOWN.

*DATA : IT_SUM TYPE TABLE OF TY_SUM,
*       WA_SUM TYPE TY_SUM.

*DATA : IT_SUM1 TYPE TABLE OF TY_SUM1,
*       WA_SUM1 TYPE TY_SUM1.

DATA : IT_SUM2 TYPE TABLE OF TY_SUM2,
       WA_SUM2 TYPE TY_SUM2.

DATA : IT_SUM3 TYPE TABLE OF TY_SUM3,
       WA_SUM3 TYPE TY_SUM3.

DATA : IT_SUM_NEW TYPE TABLE OF TY_SUM_NEW,
       WA_SUM_NEW TYPE TY_SUM_NEW.

DATA : IT_SUM_NEW1 TYPE TABLE OF TY_SUM_NEW,
       WA_SUM_NEW1 TYPE TY_SUM_NEW.

DATA : IT_SUM_NEW2 TYPE TABLE OF TY_SUM_NEW,
       WA_SUM_NEW2 TYPE TY_SUM_NEW.

DATA : IT_SUM_NEW3 TYPE TABLE OF TY_SUM_NEW,
       WA_SUM_NEW3 TYPE TY_SUM_NEW.

DATA : IT_QTY TYPE TABLE OF TY_SUM_NEW,
       WA_QTY TYPE TY_SUM_NEW.

DATA : IT_QTY_NEW TYPE TABLE OF TY_SUM_1,
       WA_QTY_NEW TYPE TY_SUM_1.

DATA : IT_ISS1 TYPE TABLE OF TY_SUM_1,
       WA_ISS1 TYPE TY_SUM_1.

DATA : IT_IS1 TYPE TABLE OF TY_SUM_1,
       WA_IS1 TYPE TY_SUM_1.


DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
       GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA : FS_LAYOUT TYPE SLIS_LAYOUT_ALV.

DATA : LV_DAYS TYPE I.
DATA : GV_YEAR TYPE I.
DATA : GV_YEAR1 TYPE N.
DATA : LV_YEAR TYPE N.
DATA : C_BUDAT TYPE BUDAT.
