*&---------------------------------------------------------------------*
*&  Include           ZUS_MB5B_1_SS
*&---------------------------------------------------------------------*
TABLES : MSEG,MARA.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
SELECT-OPTIONS   :
                    S_MATNR FOR MSEG-MATNR,
                    S_WERKS FOR MSEG-WERKS DEFAULT 'US01',
                    S_LGORT FOR MSEG-LGORT NO-DISPLAY ,
                    S_BWART FOR MSEG-BWART NO-DISPLAY ,
                    S_MTART FOR MARA-MTART NO-DISPLAY,
                    S_BUDAT FOR MSEG-BUDAT_MKPF OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B2.
SELECTION-SCREEN END OF BLOCK B1.


SELECTION-SCREEN BEGIN OF BLOCK B5 WITH FRAME TITLE ABC .
PARAMETERS P_DOWN AS CHECKBOX.
PARAMETERS : P_FOLDER LIKE RLGRAP-FILENAME DEFAULT 'E:\DELVAL\USA' MODIF ID NEE.
SELECTION-SCREEN END OF BLOCK B5.

SELECTION-SCREEN :BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-003.
SELECTION-SCREEN  COMMENT /1(60) TEXT-004.
SELECTION-SCREEN: END OF BLOCK B3.

AT SELECTION-SCREEN.

LOOP AT S_BUDAT.
IF S_BUDAT-HIGH IS INITIAL.
MESSAGE 'Posting Date is require' TYPE 'E'.
ENDIF.
ENDLOOP.
