"Name: \PR:SAPMV45A\FO:USEREXIT_MOVE_FIELD_TO_VBAP\SE:BEGIN\EI
ENHANCEMENT 0 ZVA01_MARA_LVORM_ENHANCEMENT.
*BREAK-POINT.

*TYPES : BEGIN OF VBAP,
*        MATNR TYPE VBAP-MATNR,
*        POSNR TYPE VBAP-POSNR,
*****        END OF VBAP.
****DATA : it_VBAP TYPE TABLE OF VBAP,
****       WA_VBAP TYPE VBAP.
****
*****TYPES : BEGIN OF MARA,
*****        MATNR TYPE MARA-MATNR,
*****        LVORM TYPE MARA-LVORM,
*****        END OF MARA.
****
****DATA : WA_MARA TYPE MARA,
****       IT_MARA TYPE TABLE OF MARA.
****
****TYPES : BEGIN OF FINAL,
****        MATNR TYPE VBAP-MATNR,
****        LVORM TYPE MARA-LVORM,
****        END OF FINAL.
****
****DATA : WA_FINAL TYPE FINAL,
****       IT_FINAL TYPE TABLE OF FINAL.
****
****DATA LV_VAR TYPE STRING.
****
****IF SY-TCODE = 'VA01'." AND MATNR = VBAP-MATNR AND POSNR = VBAP-POSNR.
****
****
****LOOP AT XVBAP[] INTO DATA(WA_XVBAP)."IT_VBAP INTO WA_VBAP WHERE MATNR = VBAP-MATNR AND POSNR = VBAP-POSNR.
****
****  SELECT *
****  FROM VBAP
****  INTO TABLE IT_VBAP
****  WHERE MATNR = WA_XVbAP-MATNR
****  AND   POSNR = WA_XVBAP-POSNR.
****
****  IF IT_VBAP IS NOT INITIAL.
****SELECT *
****  FROM MARA
****  INTO TABLE IT_MARA
****  WHERE MATNR = VBAP-MATNR.
****    ENDIF.
****
*****  WA_FINAL-MATNR = WA_VBAP-MATNR.
****  READ TABLE IT_MARA INTO WA_MARA WITH KEY MATNR = WA_XVBAP-MATNR .
****    IF SY-SUBRC = 0.
****  WA_FINAL-LVORM = WA_MARA-LVORM.
****  IF WA_MARA-LVORM = 'X'.
****    IF SY-SUBRC = 0.
****      CONCATENATE 'MATERIAL' WA_XVBAP-MATNR 'IS FLAG FOR DELETION' INTO LV_VAR SEPARATED BY SPACE.
****      MESSAGE LV_VAR TYPE 'E'.
****    ENDIF.
****  ENDIF.
****   ENDIF.
****  ENDLOOP.
****  CLEAR WA_XVBAP.
****ENDIF.

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""Added by Pranit 25.03.2024

IF SY-TCODE = 'VA01' or SY-TCODE = 'VA02'.

TYPES : BEGIN OF TY_MARA,
        MATNR TYPE MARA-MATNR,
        LVORM TYPE MARA-LVORM,
        END OF TY_MARA.

DATA : WA_MARA TYPE TY_MARA,
      WA_MAst TYPE TY_MARA,
       IT_MARA TYPE TABLE OF TY_MARA.

TYPES : BEGIN OF TY_MARC,
        MATNR TYPE MARC-MATNR,
        WERKS TYPE MARC-WERKS,
        LVORM TYPE MARC-LVORM,
        END OF TY_MARC.

 DATA : WA_MARC TYPE TY_MARC,
        IT_MARC TYPE TABLE OF TY_MARC.

DATA LV_VAR TYPE STRING.
DATA LV_VAR1 TYPE STRING.

SELECT SINGLE MATNR
              LVORM
  FROM MARA
  INTO WA_MARA
  WHERE MATNR = VBAPIN-MATNR.

SELECT  MATNR
        WERKS
        LVORM
  FROM MARC
  INTO TABLE IT_MARC
  WHERE MATNR = VBAPIN-MATNR.

  IF WA_MARA-LVORM = 'X'.
    IF SY-SUBRC = 0.
    CONCATENATE 'MATERIAL' VBAPIN-MATNR 'IS FLAG FOR DELETION AT CLIENT LEVEL' INTO LV_VAR SEPARATED BY SPACE.
    MESSAGE LV_VAR TYPE 'E'.
    ENDIF.
  ENDIF.

    LOOP AT IT_MARC INTO WA_MARC.

      IF VBAP-werks EQ WA_MARC-WERKS.
    IF WA_MARC-LVORM = 'X' .
    CONCATENATE 'MATERIAL' VBAPIN-MATNR 'IS FLAG FOR DELETION AT PLANT LEVEL' INTO LV_VAR SEPARATED BY SPACE.
    MESSAGE LV_VAR TYPE 'E'.
   ENDIF.
      ENDIF.

    ENDLOOP.
    ENDIF.
"""""""""""""""""""""""""""""""""""""""""""""""""""""""Ended by Pranit 25.03.2024""""""""""""""""""""""""""""""""""""""""""

ENDENHANCEMENT.
