"Name: \PR:SAPMV60A\FO:CUST_HEAD_ACTIVATE\SE:BEGIN\EI
ENHANCEMENT 0 ZVEHICAL_NO.
************************Added by PB 18.05.2019********************************

TABLES: ZVEHICALNO_TABLE.
DATA:I_VEHICAL TYPE TABLE OF ZVEHICALNO_TABLE.
*  BREAK-POINT.
IF SY-TCODE = 'VF01' OR SY-TCODE = 'VF02' OR SY-TCODE = 'VF03'.

  LOOP AT SCREEN.
  IF SCREEN-NAME EQ 'TABSTRIP_TAB06'.
    GS_CUST_TAB-HEAD_CAPTION = 'Vehicle Data'.
   GS_CUST_TAB-HEAD_PROGRAM  = 'ZVEHICLE_DETAILS_NEW'.
   GS_CUST_TAB-HEAD_DYNPRO = '5001'.

   IF GS_CUST_TAB-HEAD_DYNPRO IS NOT INITIAL.
SCREEN-INPUT = 1.
   SCREEN-ACTIVE = 1.
    SCREEN-INVISIBLE = 0.

     MODIFY SCREEN.

     TABSTRIP_TAB06 = GS_CUST_TAB-HEAD_CAPTION.
     ENDIF.
*TABSTRIP_TAB06 = GS_CUST_TAB-HEAD_CAPTION.
*     IMPORT ls_veh TO i_vehical FROM MEMORY ID 'ABCD'.  "ADD
     ENDIF.

     ENDLOOP.
ENDIF.

******************************************************************************
ENDENHANCEMENT.
