PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZTBCONTROL_VD'
  MODULE ZTBCONTROL_VD_INIT.
*&SPWIZARD: MODULE ZTBCONTROL_VD_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTBCONTROL_VD_CHANGE_COL_ATTR.
  LOOP AT   G_ZTBCONTROL_VD_ITAB
       INTO G_ZTBCONTROL_VD_WA
       WITH CONTROL ZTBCONTROL_VD
       CURSOR ZTBCONTROL_VD-CURRENT_LINE.
*&SPWIZARD:   MODULE ZTBCONTROL_VD_CHANGE_FIELD_ATTR
    MODULE ZTBCONTROL_VD_MOVE.
    MODULE ZTBCONTROL_VD_GET_LINES.
  ENDLOOP.

* MODULE STATUS_5000.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZTBCONTROL_VD'
  LOOP AT G_ZTBCONTROL_VD_ITAB.
    CHAIN.
      FIELD ZVEHICALNO_TABLE-SR_NO.
      FIELD ZVEHICALNO_TABLE-VEHICAL_NO.
      FIELD ZVEHICALNO_TABLE-QUANTITY.
      FIELD ZVEHICALNO_TABLE-UNIT_OF_MEASURE.
    ENDCHAIN.

    MODULE USER_COMMAND_5000.
  ENDLOOP.
  MODULE ZTBCONTROL_VD_USER_COMMAND.
*&SPWIZARD: MODULE ZTBCONTROL_VD_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTBCONTROL_VD_CHANGE_COL_ATTR.
