"Name: \PR:SAPMV60A\EX:FCODE_BEARBEITEN_01\EN:OIH_SAPMV60A\SE:END\EI
ENHANCEMENT 0 ZVEHICAL_NO1.
BREAK PRIMUSABAP.
IF FCODE = 'TABC_INSR' OR FCODE = 'TABC_DELE' OR FCODE = 'TABC_DMRK' OR FCODE = 'TABC_MARK'
  OR FCODE = 'TABC_P++' OR FCODE = 'TABC_P+' OR FCODE = 'TABC_P-' OR FCODE = 'TABC_P--'.
   CLEAR FCODE.
   FCODE = 'ENT1'.
ENDIF.
ENDENHANCEMENT.
