PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TABC'
  MODULE TABC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABC_CHANGE_COL_ATTR.
  LOOP AT   I_VEHICAL
       INTO S_VEHICAL
       WITH CONTROL TABC
       CURSOR TABC-CURRENT_LINE.
    MODULE TABC_GET_LINES.
*&SPWIZARD:   MODULE TABC_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_5001.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TABC'
  LOOP AT I_VEHICAL.
    CHAIN.
      FIELD S_VEHICAL-SR_NO.
      FIELD S_VEHICAL-VEHICAL_NO.
      FIELD S_VEHICAL-QUANTITY.
      FIELD S_VEHICAL-UNIT_OF_MEASURE.
      MODULE TABC_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD S_VEHICAL-SEL
      MODULE TABC_MARK ON REQUEST.
  ENDLOOP.
  MODULE TABC_USER_COMMAND.
*&SPWIZARD: MODULE TABC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TABC_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_5001.
