"Name: \PR:SAPMV60A\FO:PAI_6001\SE:BEGIN\EI
ENHANCEMENT 0 ZVEHICAL_NO.
*BREAK PRIMUSABAP.
IF FCODE = 'TABC_INSR' OR FCODE = 'TABC_DELE' OR FCODE = 'TABC_DMRK' OR FCODE = 'TABC_MARK'
  OR FCODE = 'TABC_P++' OR FCODE = 'TABC_P+' OR FCODE = 'TABC_P-' OR FCODE = 'TABC_P--'.
   CLEAR FCODE.
   FCODE = 'ENT1'.
ENDIF.
ENDENHANCEMENT.
