PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC1'
  MODULE TC1_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC1_CHANGE_COL_ATTR.
  LOOP AT   LT_FINAL
       INTO LS_FINAL
       WITH CONTROL TC1
       CURSOR TC1-CURRENT_LINE.
    MODULE TC1_GET_LINES.
*&SPWIZARD:   MODULE TC1_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_1000.
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_1000.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC1'
  LOOP AT LT_FINAL.

    CHAIN.
      FIELD LS_FINAL-VBELN.
      FIELD LS_FINAL-VHILM_KU.
    endchain.
    FIELD LS_FINAL-MARK
      MODULE TC1_MARK ON REQUEST.
  ENDLOOP.
  MODULE TC1_USER_COMMAND.
*&SPWIZARD: MODULE TC1_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC1_CHANGE_COL_ATTR.

