PROCESS BEFORE OUTPUT.
 MODULE STATUS_2000.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC2'

*&SPWIZARD: MODULE TC2_CHANGE_COL_ATTR.
  LOOP AT   LT_FINAL1
       INTO LS_FINAL1
       WITH CONTROL TC2
       CURSOR TC2-CURRENT_LINE.
    MODULE TC2_GET_LINES.
*&SPWIZARD:   MODULE TC2_CHANGE_FIELD_ATTR
  ENDLOOP.
   MODULE TC2_CHANGE_TC_ATTR.


*
PROCESS AFTER INPUT.

 MODULE USER_COMMAND_2000.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC2'
  LOOP AT LT_FINAL1.
    CHAIN.
      FIELD LS_FINAL1-MARK.
      FIELD LS_FINAL1-ZLMAT.
      FIELD LS_FINAL1-ZMATQN.
      MODULE TC2_MODIFY ON CHAIN-REQUEST.
    endchain.
  ENDLOOP.
  MODULE TC2_USER_COMMAND.
*&SPWIZARD: MODULE TC2_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC2_CHANGE_COL_ATTR.
